### ISSUE TITLE
Incorrect handling of a few specific regular expressions

### ISSUE THREAD

**Issue by Qantas94Heavy** [nodeca/js-yaml#123]
When you do something like

```
!!js/regexp /efe/g/g
```

This is an invalid JavaScript RegExp literal, however it gets parsed like the following:

```
new RegExp('/efe/g', 'g');
```

Should this not be treated literally, like in other examples such as this?

```
!!js/regexp blahblahblah
```

I think it should be treated as the following:

```
new RegExp('/efe/g/g');
```

**Comment by isaacs** [comment]
I'm seeing a test failure related to this issue.

```
> yaml.load('!!js/regexp /fo/g/g')
/fo\/g/g
> process.versions
{ http_parser: '2.3.0',
  node: '1.4.2',
  v8: '4.1.0.21',
  uv: '1.4.2',
  zlib: '1.2.8',
  ares: '1.10.0-DEV',
  modules: '43',
  openssl: '1.0.1k' }
```

It seems like it is expecting `'/fo/g/g'` instead of `'/fo\/g/g'`

**Comment by isaacs** [comment]
Indeed, this is working on Node 0.10, but not on 0.12 or io.js 1.x.  A change to the V8 RegExp toString method, perhaps?

**Comment by puzrin** [comment]
Just installed 0.12, deleted node_modules & installed again.

`make test` is ok. Ubuntu 14.04 LTS.

**Comment by isaacs** [comment]
Ah, sorry, you're right, it's only in io.js, not in node 0.12.  Almost certainly due to a V8 change.  `AssertionError: /fo\/g/g == '/fo/g/g'`.

**Comment by isaacs** [comment]
```
$ nave use 0.12 node -p 'require("./").load("!!js/regexp /fo/g/g")'
/fo/g/g

$ nave use 1.5 node -p 'require("./").load("!!js/regexp /fo/g/g")'
/fo\/g/g
```

**Comment by isaacs** [comment]
Confirmed:

```
$ nave use 0.12 node -p '[new RegExp("fo/g", "g").toString(), /fo\/g/g.toString()]'
[ '/fo/g/g', '/fo\\/g/g' ]

$ nave use 1.5 node -p '[new RegExp("fo/g", "g").toString(), /fo\/g/g.toString()]'
[ '/fo\\/g/g', '/fo\\/g/g' ]
```

Apparently, the `toString()` of a `new RegExp(...)` used to be different from the `toString()` method on a RegExp literal.

I think it's clear that js-yaml's *behavior* is fine, it's just the test that is getting confused, since it's checking the toString value.  Would you be open to a PR to make the test a bit smarter?

**Comment by puzrin** [comment]
> I think it's clear that js-yaml's behavior is fine, it's just the test that is getting confused, since it's checking the toString value. Would you be open to a PR to make the test a bit smarter?

Are you sure, that it's not v8 embedding bug, like typed arrays in 0.10.31? I remember [many lulz](https://github.com/nodeca/pako/issues/36), because broken v8 -> `pako` crashed -> browserify's zlib shim crashed -> ton's of dependencies crashed.

If you are 100% sure that it's not v8 bug - then PR with fix is welcome, of cause.

**Comment by puzrin** [comment]
Created #172. It's certaintly very bad. that tests fails on iojs.

**Comment by puzrin** [comment]
Could you advice, is it already safe to use iojs in production? Or iojs & node.js will join back soon? I'm confused with what's happenning.

**Comment by isaacs** [comment]
Many people are starting to use io.js in production.  It's quite technically sound at this point, and at least as good any other version of Node.  But it's never really "safe" to run any software in production, so manage your risks appropriately, and don't get mad at me when you find a bug ;)

On this particular issue, if and when io.js and Node reunite (which I am personally pushing for), *eventually* node will be using the newer V8 which changes the RegExp.toString behavior, so it's worth accommodating for it in the test to prevent the spurious failure.
