### ISSUE TITLE
Rework YAMLException class

### ISSUE THREAD

**Issue by dervus** [nodeca/js-yaml#153]
- It should inherit from standard Error and SyntaxError (questionable) classes.
- It should be splitted into YAMLError, YAMLSyntaxError (questionable), and YAMLWarning classes.
- It should provide more machine-readable information.
- It should be used by the dumper as well.

**Comment by puzrin** [comment]
Class inheritance solved by https://github.com/nodeca/js-yaml/commit/35ece745aa3fb9293c0d3576390644da9cba78ad. Other changes will break api and are postponed until next major version bump.

**Comment by rlidwka** [comment]
Closing as outdated. I think most of it is implemented already.
