### ISSUE TITLE
Is there a way to dump literal scalar style?

### ISSUE THREAD

**Issue by wolfgangschoeffel** [nodeca/js-yaml#159]
Really cool library! I like yaml very much. Especially because it is possible to embed html using the literal scalar style like:

```yaml
content: |
    <p>Some paragraph</p><br>
    <p>Another paragraph</p>
````

Is it possible to dump yaml in that style wtih js-yaml? I know there are already related issues but I could not really find the answer to my question there.
Thanks.

**Comment by dervus** [comment]
Not yet. PRs are welcome however. See #158 and referenced issues for details.
