### ISSUE TITLE
ISO/IEC 10646 support

### ISSUE THREAD

**Issue by cuihq** [nodeca/js-yaml#160]
The js-yaml is not support ISO/IEC 10646, please fix it.

>YAML’s double-quoted style uses familiar C-style escape sequences. Non-printable 16-bit Unicode and 32-bit (ISO/IEC 10646) characters are supported with escape sequences such as “\u003B” and “\U0000003B”.
-- [yaml 1.2 spec](http://www.yaml.org/spec/1.2/spec.html)

I pass the yaml file below to it。

```yaml
cat: "\U0001F431" # CAT FACE
dog: "\U0001F436" # DOG FACE
```
Unfortunately, It wouldn't work well.

```javascript
var doc = yaml.safeLoad(fs.readFileSync('nature.yml', 'utf-8'));
console.log(doc);
```

The console show:
> cat: '',dog: ''

I want:
> "cat"=>"🐱", "dog"=>"🐶",

**Comment by dervus** [comment]
It is an issue with String.fromCharCode function. It limited to 16-bit codepoints. Seems like we should replace it with [String.fromCodePoint](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint), which is part of ECMAScript 6. As I can see it's not yet supported by Node without --harmony flag, but is supported by io.js. However, it seems to be polyfillable.

**Comment by puzrin** [comment]
I thought we did it many time ago.

@dervus https://github.com/fontello/fontello/blob/master/client/_lib/utils.js no need to use fromCodePoint - it's implementation is too heavy

**Comment by dervus** [comment]
@puzrin OK, I'll use that implementation from Fontello.

**Comment by cuihq** [comment]
:+1:

**Comment by puzrin** [comment]
Published.
