### ISSUE TITLE
Read from stream instead of a file

### ISSUE THREAD

**Issue by DJPillowhead** [nodeca/js-yaml#162]
Hi All,

Is there any way to use this module to get the input from a stream? 
I get a yaml in a http response and i'd like to convert it to an object on the file without writing it out to a file first...

Any ideas?

Thanks!

**Comment by dervus** [comment]
Reading from a stream is not possible. Reading from a file is also not possible. JS-YAML can work only with plain strings.

**Comment by DJPillowhead** [comment]
"usage: js-yaml [-h] [-v] [-c] [-t] file

Positional arguments:
  file           File with YAML document(s)"

It seems to me that it waits for a file as an input. And checking in loader.js I saw something like this too. What am I missing here?

**Comment by dervus** [comment]
This is help string of our CLI utility. If you're going to use JS-YAML as a library, you must read "API" section of the README.

**Comment by DJPillowhead** [comment]
I see it now, got it! Thanks!
