### ISSUE TITLE
Can't parse !!bool 'yes'

### ISSUE THREAD

**Issue by Kagami** [nodeca/js-yaml#165]
Hi. Great module but `!!bool type` seems to be not working correctly.

I get this error:
```
JS-YAML: cannot resolve a node with !<tag:yaml.org,2002:bool> explicit tag at line 7, column 16:
    i: !!bool 'yes'
```
for this input:
```
i: !!bool 'yes'
```

But `!!bool 'true'`/`!!bool 'false'` parsed correctly.

**Comment by dervus** [comment]
y/n/yes/no/on/off are deprecated since YAML 1.2. You can use only true and false.

**Comment by puzrin** [comment]
@Kagami those aliases are legacy shit. Try to dig ancient 1.0.0 version, it should support those, if you can't live without.

**Comment by Kagami** [comment]
Thanks. No, I don't actually need this aliases, just saw them in http://yaml.org/type/bool.html and didn't check the latest spec.
