### ISSUE TITLE
Throw a warning for duplicate keys 

### ISSUE THREAD

**Issue by mohsen1** [nodeca/js-yaml#166]
In [Swagger Editor](https://github.com/swagger-api/swagger-editor) people edit large YAML files and sometimes they mistakenly repeat a key in an object. JSYAML just overrides the first key with second one with no errors or warnings. It would be very helpful if JSYAML was throwing an error or a warning for duplicate keys so I could inform user about the issue.

To be clear, here is an example of duplicate keys:

```yaml
one: 1
one: 2
```
this will be parsed to `{one: 2}`

**Comment by dervus** [comment]
Thanks for pointing this out. Actually it looks like a bug because YAML spec demands that a mapping key must be unique in contrast to JSON (MUST vs SHOULD). However, I dimly remember that there was some reason for current behavior. I must find it out.
