### ISSUE TITLE
Regexp test fails on iojs

### ISSUE THREAD

**Issue by puzrin** [nodeca/js-yaml#172]
https://github.com/nodeca/js-yaml/issues/123#issuecomment-77672153

```
$ nave use 0.12 node -p '[new RegExp("fo/g", "g").toString(), /fo\/g/g.toString()]'
[ '/fo/g/g', '/fo\\/g/g' ]

$ nave use 1.5 node -p '[new RegExp("fo/g", "g").toString(), /fo\/g/g.toString()]'
[ '/fo\\/g/g', '/fo\\/g/g' ]
```

`.toString()` works differently. Is is normal or v8 bug?

**Comment by isaacs** [comment]
Technically it is a v8 bug *fix*, and should have behaved that way all along.  But since we can't go back in time, the test should probably allow either result.
