### ISSUE TITLE
Unknown Error on package installation

### ISSUE THREAD

**Issue by ambrumyan** [nodeca/js-yaml#175]
Below is error trace

npm ERR! Error: UNKNOWN, symlink '../esprima/bin/esparse.js'
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! path ../esprima/bin/esparse.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0

**Comment by puzrin** [comment]
delete `node_modules` and install again, that's npm bug.

**Comment by ambrumyan** [comment]
Doesn't help

**Comment by ambrumyan** [comment]
Other packages are installed well , only problem with js-yaml

**Comment by puzrin** [comment]
See path to file in error log. Make sure that you delete `node_modules` that contain it. Or delete this one manually. Seems you are in nested folder.

`npm install js-yaml` - just tested in clear folder.

**Comment by ambrumyan** [comment]
Tried, doesn't helps, I updated npm to 2.7.0 too , but same problem

**Comment by puzrin** [comment]
I think it's better to report your case in npm with description how to reproduce, that's not js-yaml bug. You can see closed tickets, such reports happened several times, but all those are related to npm.

Also try to search in google https://www.google.ru/search?q=npm+install+symlink+error, may be you will find recipe there.

**Comment by ambrumyan** [comment]
ok Thanks
