### ISSUE TITLE
Impossible to parse a value %..% (not wrapped in quotes)

### ISSUE THREAD

**Issue by jdespatis** [nodeca/js-yaml#178]
`js-yaml` yells if I give this YAML to it:

```
foo: %bar%
```

Everything is fine if I wrap the `%bar%` in quotes (`foo: "%bar%"`)

I've been told that wrapping in quotes was mandatory in YAML 1.0, but is no more mandatory in YAML 1.2
Do you confirm ? if yes, `js-yaml` should accept those values (with no quotes)

**Comment by puzrin** [comment]
% is directive start symbol. It must be quoted. Search % in http://www.yaml.org/spec/1.2/spec.html

**Comment by jdespatis** [comment]
thanks @puzrin
