### ISSUE TITLE
Junk at the beginning of first tag

### ISSUE THREAD

**Issue by diegoefe** [nodeca/js-yaml#179]
Using it inside of node v0.12.2 (on windows XP), I get junk (unicode sequence \uFEFF) at the beginning of the first tag.
Run with node pru.js
pru.js:
```javascript
yaml = require('js-yaml');
fs = require('fs');

try {
    var doc = yaml.safeLoad(fs.readFileSync('./pru.yaml', 'utf8'));
    for(var p in doc) {
        if('accion'==p.substr(1, p.length-1)) {
            //for(var c=0; c<p.length; ++c) {
            //   console.log("'" + p[c] +"' -> "+ p.charCodeAt(c));  
            //}
            var manual='\uFEFFaccion';
            console.log("'"+p+"' y '"+manual+"' "+
                        ((manual == p) ? "are equal" : "are different"));
        }
    }
}
catch (e) {  console.log(e); }
```
pru.yaml
```yaml
accion: castellano
abr: es
languages:
  en: inlgés
  es: español
  it: italiano
  ru: ruso
```
This is the first contribution so please excuse me if this is inapropiate or no the right place and form
Diego

**Comment by dervus** [comment]
That \uFEFF looks like a BOM. JS-YAML works only with JavaScript strings, which are abstracted from such low-level encoding details. I'm not sure, but it looks like you're either:

1. Reading the file using wrong encoding.
2. Reading UTF-8 encoded file with BOM by some reason, and Node's filesystem API does not expect UTF-8 files to contain BOM.

**Comment by puzrin** [comment]
@dervus , may be we could strip BOM automatically?

**Comment by dervus** [comment]
Maybe, but first I'd want to know why there is a BOM inside JS string? It does not make sense for me.

**Comment by puzrin** [comment]
I guess, if file was edited in Win editor, it could add BOM.

**Comment by dervus** [comment]
BOM does not make sense for UTF-8 files. I'm not sure why we should handle stupid behavior of Notepad.

**Comment by puzrin** [comment]
It will not cost us anything, IMHO, and will help to avoid new tickets.

**Comment by diegoefe** [comment]
First of all, I'm very sorry guys, I behave like a total newbie!
Yes, It's notepad++.
Yes, It was the BOM in UTF-8

Sorry, again.

**Comment by dervus** [comment]
https://github.com/joyent/node/issues/1918

@puzrin , honestly, I don't like the idea, but it seems legit... I'll think about it when I'll finally dedicate some time for JS-YAML development.

**Comment by ixti** [comment]
IMO it's not YAML loader responsibility to sanitize strings..
