### ISSUE TITLE
[writer] Improve dump style determination for strings

### ISSUE THREAD

**Issue by dervus** [nodeca/js-yaml#183]
In general there are still some cases when we can and probably should use plain scalar style for strings when dumping. So we should not unnecessarily quote URIs for example.

http://www.yaml.org/spec/1.2/spec.html#id2788859

**Comment by jhartman86** [comment]
Is there currently a way to achieve this with the style map options? Another use case would be in a #cloud-init file, for example.
sudo: ['ALL=(ALL) ...']
where currently, there doesn't seem to be a way to output ['ALL...'] without it being wrapped in quotes.

**Comment by dervus** [comment]
Style map is completely unrelated thing. It controls representation style within a node, not node's style itself.

**Comment by ewaltman** [comment]
👍

**Comment by puzrin** [comment]
Close as "endless"
