### ISSUE TITLE
Getting information from object

### ISSUE THREAD

**Issue by phase** [nodeca/js-yaml#184]
I'm loading [this file](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml) and I want to get the `color` value of each language and put it into an array. Currently I have:

```javascript
yaml = require('js-yaml');
var languages = yaml.safeLoad(languages_yml); //languages_yml is a string of the file

function Language(color){
  this.klass = 'Language';
  this.color = color
}
```

**Comment by puzrin** [comment]
What it the question?

**Comment by phase** [comment]
@puzrin How can I get the `color` value of each language and put it into an array?

**Comment by puzrin** [comment]
`#xxxxxx` -> `Number`: `parseInt(color.slice(1), 16)`

You keep colors as strings in yaml.

**Comment by phase** [comment]
@puzrin I have `js-yaml` stored in `languages`, how could I get it out of that?

**Comment by puzrin** [comment]
Load yaml file as you did. You will get a simple javascript object.  Then iterate it with lodash, for example, and convert string content of color property to number as i explained above.

Sorry, but your question is not related tho this repo anyhow.
