### ISSUE TITLE
Parsing error: can not read a block mapping entry

### ISSUE THREAD

**Issue by josiahsprague** [nodeca/js-yaml#185]
I'm experiencing a weird parsing error. I have the following in a YAML file;
```
/music/{release}:
  title: "&middot; &bull; {{resources.title}} &middot; BLAH BLAH &middot; &bull; &middot;"
  og:type: music.album
  image: resources.image.source
  canonical: /music/{release}
```
And I'm getting the following error from JS-YAML;
```
JS-YAML: can not read a block mapping entry; a multiline key may not be an implicit key at line 3, column 10:
      og:type: music.album
```
I can't figure out why this is happening. Is my YAML syntax correct? Any other ideas?

**Comment by puzrin** [comment]
`og:type` -> `'og:type'`

@dervus it's strange, but i don't see error in [demo](http://nodeca.github.io/js-yaml/#yaml=L211c2ljL3tyZWxlYXNlfToKICB0aXRsZTogIiZtaWRkb3Q7ICZidWxsOyB7e3Jlc291cmNlcy50aXRsZX19ICZtaWRkb3Q7IEJMQUggQkxBSCAmbWlkZG90OyAmYnVsbDsgJm1pZGRvdDsiCiAgb2c6dHlwZTogbXVzaWMuYWxidW0KICBpbWFnZTogcmVzb3VyY2VzLmltYWdlLnNvdXJjZQogIGNhbm9uaWNhbDogL211c2ljL3tyZWxlYXNlfQ==). It appears only if i add space (`og:_type:`)

@josiahsprague need more details about your envoronment - engine/browser/os version, where you got this error.

**Comment by puzrin** [comment]
@josiahsprague i can't reproduce your problem in node.js & iojs.

```
npm install -g js-yaml
js-yaml <your_file>
```

You need to prepare full gist example or test repo.

**Comment by puzrin** [comment]
Closed - timed out. Add example if need to reopen.
