### ISSUE TITLE
Double quotes, simple quotes, no quotes...

### ISSUE THREAD

**Issue by borisschapira** [nodeca/js-yaml#193]
Is is ok that the behaviour is different whether we wrote this in YAML : 

```
quotes: 
      - "«\xA0"
      - "\xA0»"
      - "‹\xA0"
      - "\xA0›"
```

or this :

```
quotes: 
      - '«\xA0'
      - '\xA0»'
      - '‹\xA0'
      - '\xA0›'
```

On the latter, the backslash is escaped, causing the special character not to be interpreted.

**Comment by puzrin** [comment]
Yes. That's all described in spec http://www.yaml.org/spec/1.2/spec.html#id2786942

**Comment by borisschapira** [comment]
Thanks for the info !
