### ISSUE TITLE
JSON output?

### ISSUE THREAD

**Issue by rblakeley** [nodeca/js-yaml#195]
Using `{ schema: yaml.JSON_SCHEMA }` is not affecting the output at all. Keys are not wrapped in quotes at all and values are wrapped in single quotes. I expected both to be wrapped in double quotes (valid JSON). Am I misunderstanding the purpose of the `schema` option?

**Comment by puzrin** [comment]
It defines list of supported types, not formatting. You need `JSON.stringify()` for json format.
