### ISSUE TITLE
Values looking like dates are coerced to Date objects

### ISSUE THREAD

**Issue by saibotsivad** [nodeca/js-yaml#198]
For example if I have

```yaml
key: 2015-07-09
```

it gets coerced to a date object. After reading the YAML docs, and looking at the [timestamp](http://yaml.org/type/timestamp.html) type, I would have expected the above example to be a string, and the type `!!timestamp` to be required for date coercion. E.g.,

```yaml
key: !!timestamp 2002-12-14
```

This does coerce correctly to a date object, but I do not think that coercing the first example to a date object is not a correct implementation of the specs.

Am I misunderstanding the YAML docs wrong, or was this a conscious decision on the part of the js-yaml developers?

**Comment by puzrin** [comment]
http://www.yaml.org/spec/1.2/spec.html#id2761292

Works as required.

**Comment by saibotsivad** [comment]
Whoops, I missed that in the docs. Thanks for the fast response and link! :+1:
