### ISSUE TITLE
Error.captureStackTrace not available in Firefox

### ISSUE THREAD

**Issue by vogelsgesang** [nodeca/js-yaml#204]
The latest release broke exception handling in Firefox, since Error.captureStackTrace which was introduced in commit acb734f8daf9ce8094b3f48d0b8d92b832a42153 is not available in Firefox.

**Comment by puzrin** [comment]
Thanks for info. A there a better ways of error subclassing (except loosing stacktrace in some browsers)?

**Comment by vogelsgesang** [comment]
Unfortunately, I am not aware of a better solution, so far I did not even know that the problem of error subclassing existed.

bfbaf125767c35ea78fe80f4fd9894308d769222 is the best solution I am aware of. Thanks for your fast response and the fix.

**Comment by sindresorhus** [comment]
https://github.com/floatdrop/capture-stack-trace

**Comment by puzrin** [comment]
@sindresorhus thanks for info!

**Comment by puzrin** [comment]
Should be fixed.
