### ISSUE TITLE
Is It Possible to Preserve Object Key Order?

### ISSUE THREAD

**Issue by jon49** [nodeca/js-yaml#208]
I am parsing a Swagger file (paths) and it is not preserving the order of the keys. Is there a setting I could use to preserve the order?

From the docs and issues I haven't seen any mention of it.

**Comment by puzrin** [comment]
Could you provide minimal example?

**Comment by jon49** [comment]
Embarrassing. Apparently `Object.getOwnPropertyNames(paths)` isn't preserving the order.

**Comment by Zlatkovsky** [comment]
You can control the output, however.  See the "sortKeys" property (which can take in either a boolean for true/false (alphabetical) or a function):  https://github.com/nodeca/js-yaml/blob/master/README.md

Example where you can see it used:  https://github.com/nodeca/js-yaml/blob/c76b837cacc69de6b86a0781db31a9bb7a193875/test/units/sort-keys.js

**Comment by mingwli** [comment]
@puzrin Is it possible to access the object being sorted in sortKeys()? e.g. The keys don't needed to be sorted if parent has a flag noSort set to true.
