### ISSUE TITLE
Source file position information

### ISSUE THREAD

**Issue by buttim** [nodeca/js-yaml#211]
Is there a way to extract source file position for a certain token?
If not how hard would it be to modify it in order to add the info?

This feature would be of great value for applications in need to signal errors in the source file

**Comment by puzrin** [comment]
Only for erros & warnings https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/exception.js#L24 . For arbitrary tokens that would require full rewrite and is not planned.

**Comment by buttim** [comment]
Thank you, puzrin. Are you aware of any other js library that does such a thing?

**Comment by puzrin** [comment]
i don't know
