### ISSUE TITLE
Following the documentation, get strange behaviour

### ISSUE THREAD

**Issue by Skahrz** [nodeca/js-yaml#214]
Here's my yaml :

```yaml
node:
  port:80
  nbProcesses:8
```
And here's my code :

```javascript
let file = fs.readFileSync('src/conf/server.yml', 'utf8');
let conf = yml.load(file);
console.log(conf);
```

And here's the (strange output), In fact, node properties acts like string in that case
```
{ node: 'port:80 nbProcesses:8' }
```

**Comment by puzrin** [comment]
[spaces missed](http://nodeca.github.io/js-yaml/#yaml=bm9kZToKICBwb3J0OjgwCiAgbmJQcm9jZXNzZXM6OAoKCm5vZGUyOgogIHBvcnQ6IDgwCiAgbmJQcm9jZXNzZXM6IDg=)
