### ISSUE TITLE
Only strings should be folded

### ISSUE THREAD

**Issue by puzrin** [nodeca/js-yaml#217]
Currently dumper will fold functions & regexes too. That can cause errors. It seems, folding should be restricted to strings only.

---

@isaacs , since you promoted this feature to dumper & implemented it, i need your opinion. Do you have cases when folding needed for something more than plain strings? Will it affect you if i restrict foltder to strings only?

**Comment by isaacs** [comment]
Restricting folding to strings should be fine, as far as I can see.  If I'd known it would affect other types, I would have added that restriction up front, sorry about the oversight!

**Comment by puzrin** [comment]
No problem. That's not critical since nobody noticed it 6 months after release :)
