### ISSUE TITLE
Inconsistent floating-point format between `safeLoad` and `safeDump`

### ISSUE THREAD

**Issue by BigstickCarpet** [nodeca/js-yaml#220]
According to the [YAML spec for floating-points](http://yaml.org/type/float.html), I should be able to specify numbers using scientific notation format.  For example:

```yaml
foo: 5e-324
```

But js-yaml's `safeLoad()` method parses this as a *string* property, rather than a *number*.   The `safeDump()` method serializes floating-point numbers using scientific notation format, so it seems logical that the `safeLoad()` method should correctly de-serialize them.

```javascript
var obj1 = {foo: 5e-324};
var str = yaml.safeDump(obj1);
var obj2 = yaml.safeLoad(str);

// obj1 === {foo: 5e-324}      <--- number
// obj2 === {foo: "5e-324"}    <--- string
```

**Comment by puzrin** [comment]
Support of scientific format os not missed https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/float.js#L6-L11

Looks like dumper error - [missed dot](http://nodeca.github.io/js-yaml/#yaml=Zm9vOiA1LmUtMzI0CmJhcjogNWUtMzI0).

**Comment by BigstickCarpet** [comment]
:+1: Thanks for the tip about the dot.  Much appreciated!

So I guess the actual issue here is that the `safeDump` method doesn't serialize floats properly, such that they can survive a round-trip of JSON -> YAML -> JSON

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/float.js#L91 native JS serializer is not compatiblel with expected in YAML, as you found.

It think, this can be healed with regexp (search `e` without dot before, and add `.` somewhere)

**Comment by puzrin** [comment]
Should be fixed by https://github.com/nodeca/js-yaml/commit/27cfd26d7733ad8eb2f2fc778dff84dd1239fc7a. If you have some time - please test a master.
