### ISSUE TITLE
Light library version suitable for addons

### ISSUE THREAD

**Issue by minj** [nodeca/js-yaml#226]
I wanted to explore using this library in a Firefox addon. It loads and works just fine which is rather surprising since few do without additional hacking.

However, Mozilla's validator complains about a few severe issues that prevent automatic signing:

---
**Access to the `Function` global**
**Warning**: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.
```js
  /*eslint-disable no-new-func*/
  return new Function(params, source.slice(body[0] + 1, body[1] - 1));
}
```
---
**`setTimeout` called in potentially dangerous manner**
**Warning**: In order to prevent vulnerabilities, the `setTimeout` and `setInterval` functions should be called only with function expressions as their first argument.
```js
}
var timeout = setTimeout(cleanUpNextTick);
draining = true;
```
```js
if (!draining) {
    setTimeout(drainQueue, 0);
}
```
---

All `eval`-type constructs are evil and are not accepted in Google Chrome either AFAIK (CSP). Personally, I don't see a sane use case for such atrocities in a YAML library, of all things, but I'm sure that it's my limited imagination that is in the wrong here.

Anyway, it would be lovely to have a 'light' version without these attack vectors. My first impression was that one does not simply remove those exports since they are dependencies for others...

**Comment by puzrin** [comment]
settimeout is not used at all, and fn constructor is used only in unsafe load for appropriate data type. If you don't use it, CSP will not be a problem. There is nothing to fix.

**Comment by minj** [comment]
Funny conclusion. 

Add-on validation is a crude static analysis, you see. This library is not usable since those LOCs are flagged and prevent automatic add-on signing.  So this is a problem and it is 'something to fix'.

**Comment by puzrin** [comment]
I'm not familiar with analyzer you use and what you analyzed. This info is a bit useless to do anything. If you need any actions - please refer to lines that cause problems.

**Comment by minj** [comment]
It's not what *I use* that matters. It's all about Mozilla. They did make an npm package yesterday but it's broken for me. In any case you can use the [web interface](https://addons.mozilla.org/en-US/developers/addon/validate).

What 'I analyzed' is my add-on with your library injected. I think you can take any xpi file from addons.mozilla.org and just append it to them (xpi=zip) to test. In any case it won't do you much go since I already posted everything relevant in comment 1.

Here's a screenshot if you don't believe me: http://i.imgur.com/aIPp1Aj.png

**Comment by puzrin** [comment]
Could you explain how do you include this package into your project?

**Comment by minj** [comment]
I took the [js-yaml.js](https://github.com/nodeca/js-yaml/blob/master/dist/js-yaml.js) dist file designed for including in browsers.

FF addons have a `Services.scriptloader.loadSubScript` function that can load js files  in [arbitrary scopes](https://github.com/minj/foxtrick/blob/2d75a0dc29ef2fe1a1d64e7f18c22bd646b1755a/content/bootstrap-firefox.js#L267). I then take it off of `module.exports` and use it as I need.

**Comment by puzrin** [comment]
Ah, i see now, setTimeout was added by browserify wrapper. Seems options should be tuned.

Is in nessesary to use browserified file or you can work with "native" npm sources?

**Comment by minj** [comment]
Well there is no such thing as `require` here so I would need to write a custom loader it seems. In any case I find that having each library in a single file is very neat.

**Comment by puzrin** [comment]
Ok, i undertand. Nobody expected serious use of browserified build - it was mostly for demo page.

I can easily fix warning with setTimeout, because that's a browserification garbage. But i would not like to create a separate build without [this file](https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/js/function.js). Need to think how to organize it.

May be you could patch 1 line with script, if you keep separate copy in your project anyway? Or it's very inconvenient?

**Comment by minj** [comment]
Sure, I don't mind much having a patched 'private' version but I do not think I can dedicate the time for maintaining and updating a project fork in a timely manner. That's why I decided to open a issue here first.

**Comment by puzrin** [comment]
Now should be without `setTimeout()` warning (regression in 3.4).

About eval warning - i still suggest to strip 1 line in your local copy. That can be automated. I don't like to create an additional build until more of such requests come. If you are not alone with this problem, then such build will be done.

Ok?

**Comment by minj** [comment]
Removing js/function include does the job. Library still works and the validator does not complain :joy:  

@puzrin, out of curiosity, which version of browserify do you use? I get a somewhat different output :)

**Comment by puzrin** [comment]
10.1.3

**Comment by minj** [comment]
Alright I created a fork at https://github.com/minj/js-yaml

If it's up to me this issue can be closed.

**Comment by minj** [comment]
Thank you for your help.
