### ISSUE TITLE
Trailing new line symbols in literal notation

### ISSUE THREAD

**Issue by DiamondeX** [nodeca/js-yaml#234]
Zero or more trailing new line symbols in literal notation in yml are converted to exactly one trailing new line symbol in json. So, having this yml file (indent spaces are visualized with middle dot symbol for readability):
```yml
LINEBREAK_AT_THE_END: |
··Linebreak at the end
··
TWO_LINEBREAKS_AT_THE_END: |
··Two linebreaks at the end
··
··
NO_LINEBREAKS: |
··No linebreaks
ZERO: Zero
```
you will have json like this:
```json
{
  "LINEBREAK_AT_THE_END": "Linebreak at the end\n",
  "TWO_LINEBREAKS_AT_THE_END": "Two linebreaks at the end\n",
  "NO_LINEBREAKS": "No linebreaks\n",
  "ZERO": "Zero"
}
```
Any suggestions on how to deal with this at least with some workaround?

**Comment by DiamondeX** [comment]
As denoted here: http://www.yaml.org/spec/1.2/spec.html#id2777534
"A block style construct is terminated when encountering a line which is less indented than the construct"
and this is what we expect in such case

**Comment by buttim** [comment]
Seems like this problem totally disrupts the functionality of depending libraries like yawn-yaml

**Comment by dervus** [comment]
There is no workarounds, there is special syntax for that in YAML:
``` yaml
foo: |-
  hello
  world

bar: 42
```
``` javascript
{ foo: 'hello\nworld', bar: 42 }
```

See http://www.yaml.org/spec/1.2/spec.html#id2793718
