### ISSUE TITLE
Unable to use safeLoadAll

### ISSUE THREAD

**Issue by SimitTomar** [nodeca/js-yaml#237]
Hi, 

I am new to javascript and Yaml so please excuse my ignorance in this regard. I have multiple Yaml files and trying to load them all once by using the safeLoadAll option but struggling with it.

This is what I have tried:

var yaml = require('js-yaml');
var fs = require("fs");

var data = ['firstFile.yml', secondFile.yml'];

try {
    var allData = yaml.safeLoadAll(fs.readFileSync(data));
    console.log(allData);
}

catch (e){
console.log(e);
}

I am able to load one file at a time but load multiple is of course not working and throwing an error 'Path must be a string'. not too sure how should I pass the 2 files so that they get loaded.

Also, is there a way through which I can verify Duplicate entries in the 2 Yaml files once they have been loaded successfully.

Please suggest.

Thanks
Simit

**Comment by puzrin** [comment]
You need to read those one-by one. safeLoadAll needed when __one__ yaml file contains __multiple__ documents.

**Comment by BouchaaraAdil** [comment]
@puzrin you need to elaborate more on readme with examples
