### ISSUE TITLE
Remove inherit dependency and use Object.create for inheritance

### ISSUE THREAD

**Issue by gyandeeps** [nodeca/js-yaml#239]
Would you be open to removing the module `inherit` and use [`Object.create`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Classical_inheritance_with_Object.create()) to provide inheritance at this place: https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/exception.js#L30
This is the only place `inherit` module is getting used.

Why I am proposing this is because of the license issue which we have seen for `inherit` and because of that we had to pin down version of `js-yaml` in eslint library. 
`inherit` has not been released in over 2 years now so i am not sure when that would happen.
Ref: https://github.com/eslint/eslint/issues/4553

If this is accepted then I will send a PR.

Thanks

CC: @puzrin

**Comment by puzrin** [comment]
I have no objection to replace `inherit` with anything that works and has fallback for old browsers. This module was taken as most popular, to replace one from the node.

As far as i see, browserify has this code https://github.com/substack/node-browserify/blob/2009e65becbac3ceb82ec6c7b53736aa3195d023/builtins/util.js#L279-L312

**Comment by puzrin** [comment]
released

**Comment by gyandeeps** [comment]
Awesome. Thanks a lot for a quick response. :+1:
