### ISSUE TITLE
Incorrect duplicated key exception

### ISSUE THREAD

**Issue by Pchelolo** [nodeca/js-yaml#242]
After updating to 3.5 version I've started to receive an incorrect exception while using `safeLoad` on this file: https://github.com/wikimedia/restbase/blob/master/sys/post_data.yaml

The exception is: `YAMLException: duplicated mapping key at line 24, column 1:\n    \n    ^\n    at generateError`

Seems like empty lines are considered as mapping keys now, which is clearly incorrect.

**Comment by puzrin** [comment]
[link](http://nodeca.github.io/js-yaml/#yaml=c3dhZ2dlcjogJzIuMCcKaW5mbzoKICB2ZXJzaW9uOiAnMS4wLjAnCiAgdGl0bGU6IFJFU1RCYXNlIHBvc3QgZGF0YSBzdG9yYWdlIG1vZHVsZQogIGRlc2NyaXB0aW9uOiBSZXZpc2lvbmVkIHBvc3QgZGF0YSBzdG9yYWdlIHdpdGggSFRUUCBpbnRlcmZhY2UsIGJhY2tlZCBieSB0YWJsZSBzdG9yYWdlCnBhdGhzOgogIC97YnVja2V0fToKICAgIGdldDoKICAgICAgb3BlcmF0aW9uSWQ6IGdldEJ1Y2tldEluZm8KICAgIHB1dDoKICAgICAgb3BlcmF0aW9uSWQ6IGNyZWF0ZUJ1Y2tldAoKICAve2J1Y2tldH0vOgogICAgZ2V0OgogICAgICBvcGVyYXRpb25JZDogbGlzdEJ1Y2tldAoKICAve2J1Y2tldH0ve2tleX17L3RpZH06CiAgICBnZXQ6CiAgICAgIG9wZXJhdGlvbklkOiBnZXRSZXZpc2lvbgoKICAve2J1Y2tldH0vOgogICAgcHV0OgogICAgICBvcGVyYXRpb25JZDogcHV0UmV2aXNpb24K)

Lines 13 & 21 have duplicated keys. Error point to end of duplicated key.

**Comment by timwis** [comment]
Just in case anyone else gets here from a google search, I got this error because I had tab indentation mixed in with space indentation due to a copy and paste
