### ISSUE TITLE
Please use semver conventions - Addition of validation is a breaking change

### ISSUE THREAD

**Issue by Fannon** [nodeca/js-yaml#245]
Hello!

First let me thank you for this very helpful library! I use it a lot!

I've just had the issue that some yaml files I was using internally had duplicate keys. With one of the latest minor releases, this started to throw an expection where there was none before. Since NPM installs minor updates by default, just a NPM update caused one of my NPM modules to stop working. Of course I should have try catched js-yaml in the first place, so I'm the first one to blaim for this problem.

But it would be nice if breaking features would get a majour version bump, as semver suggests. Or use feature flags the optionally enable those potentially breaking features.

Thanks!
Simon

**Comment by puzrin** [comment]
Semver does not give you 100% guarantee, that nothing will be broken. It's always possible to write code such way than even patch number change with break it.

I consider throwing on dupes as bugfix, not as feature. Duplicated keys are prohibited both in JSON & in YAML.

**Comment by Fannon** [comment]
Ok, only fair.

**Comment by puzrin** [comment]
I mean, we did not introduced feature "throw exceptions". We could throw those before, but forgot to throw on dupes.

**Comment by hulbert** [comment]
FWIW this caused our usage of eslint (which relies on `js-yaml`) to break unpredictably on new builds.
