### ISSUE TITLE
expose YAML parsing information [new feature]

### ISSUE THREAD

**Issue by ahgittin** [nodeca/js-yaml#248]
Would be nice if this library could expose intermediate methods for working with the parse tree -- in particular text offsets for model items (including malformed) and comments.

This would allow an API user to edit model content while maintaining a YAML source in synch bidirectionally, with comments and unrelated whitespace preserved.  Also if YAML is malformed in places, the errors could be limited to those sections while nicely handling other sections.  [snakeyaml](snakeyaml.org) is a nice implementation of this (in Java).

I appreciate that this is a significant addition to the scope of this project but I think this is the most complete JS YAML implementation so I'm interested if it's on the roadmap or all or if not whether there might be appetite for it.

**Comment by puzrin** [comment]
That's impossible with current architecture and is not on roadmap, sorry.

**Comment by ahgittin** [comment]
Darn!  :)  Thanks.

**Comment by ahgittin** [comment]
@puzrin a `state.listener` proved a very simple addition sufficient to enable a caller to get the parse tree.  it's low-level but would be really useful for us if you'd consider it!

PR'd in #249.

Just 3 lines of actual code, plus several tests.

**Comment by puzrin** [comment]
I tend to accept it, see comments in PR - some polish needed.

Note, that current architecture was optimized for speed - that's why it may look strange (compared to official yaml parser approach). I think, it can be improved, but experiments require too much of time.
