### ISSUE TITLE
Incorrect duplicated mapping key

### ISSUE THREAD

**Issue by Hanspagh** [nodeca/js-yaml#251]
For some reason I get a duplicated mapping key error for this yaml on the wrong line
The error is at ownershipCost and not at constructionYear
[link](http://nodeca.github.io/js-yaml/#yaml=c3dhZ2dlcjogIjIuMCIKaW5mbzoKICB2ZXJzaW9uOiAiMC4wLjEiCiAgdGl0bGU6IHNhZXJ2aWNlCiMgYmFzZVBhdGggcHJlZml4ZXMgYWxsIHJlc291cmNlIHBhdGhzCmJhc2VQYXRoOiAvdjEKIwpzY2hlbWVzOgogIC0gaHR0cHMKIyBmb3JtYXQgb2YgYm9kaWVzIGEgY2xpZW50IGNhbiBzZW5kIChDb250ZW50LVR5cGUpCmNvbnN1bWVzOgogIC0gYXBwbGljYXRpb24vanNvbgojIGZvcm1hdCBvZiB0aGUgcmVzcG9uc2VzIHRvIHRoZSBjbGllbnQgKEFjY2VwdHMpCnByb2R1Y2VzOgogIC0gYXBwbGljYXRpb24vanNvbgojIGNvbXBsZXggb2JqZWN0cyBoYXZlIHNjaGVtYSBkZWZpbml0aW9ucwpkZWZpbml0aW9uczoKICBSZWFsRXN0YXRlQnVkZ2V0OgogICAgcmVxdWlyZWQ6CiAgICAgIC0gaG9tZUlkCiAgICAgIC0gYmJyTnVtYmVyCiAgICAgIC0gaG9tZVNpemUKICAgICAgLSBob21lVHlwZQogICAgICAtIG93bmVyc2hpcENvc3QKICAgICAgLSBjb25zdHJ1Y3Rpb25ZZWFyCiAgICAgIC0gcG9zdGFsQ29kZQogICAgICAtIHByaWNlCiAgICAgIC0gZW5lcmd5TGFiZWwKICAgIHByb3BlcnRpZXM6CiAgICAgIGhvbWVJZDoKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgYmJyTnVtYmVyOgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICBob21lU2l6ZToKICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgIGhvbWVUeXBlOgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICBvd25lcnNoaXBDb3N0OgogICAgICAgIHR5cGU6IGludGVnZXIKICAgICAgb3duZXJzaGlwQ29zdDoKICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgIGNvbnN0cnVjdGlvblllYXI6CiAgICAgICAgdHlwZTogaW50ZWdlcgogICAgICBwb3N0YWxDb2RlOgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICBwcmljZToKICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgIGVuZXJneUxhYmVsOgogICAgICAgIHR5cGU6IHN0cmluZyAgICAg)

**Comment by dervus** [comment]
dup https://github.com/nodeca/js-yaml/issues/243
