### ISSUE TITLE
Colon in the flow context

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#252]
If I try to parse this document
```
- {1 :2}
- {1:2}
- {1: 2}
- {1:"2"}
```

I get the following result:
```
[ { '1 :2': null },
  { '62': null },
  { '1': 2 },
  { '1:"2"': null } ]
```

I think nothing from the result is correct. We have the same challenge in SnakeYAML. Unfortunately, we had to prohibit to use colon (:) in the flow context.

**Comment by puzrin** [comment]
What's the problem in? Data is parsed according to yaml spec.

**Comment by dervus** [comment]
@puzrin I'm not sure about others, but `{1:2}` to `{ '62': null }` is... wow. Flow collection parser needs work for sure.

**Comment by puzrin** [comment]
See http://nodeca.github.io/js-yaml/#yaml=eyBmb286IDE6MiB9

{ foo: 1:2 } => { foo: 62 } - that's some shit about base60 in int, and i guess it's ok

https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/int.js

**Comment by dervus** [comment]
Ah, right. However, I'm not sure if `1:2` is really supposed to be interpreted as a single scalar. Normally in YAML key-value connector is `:` + whitespace, but for JSON compatibility they make an exception in flow collection style. I'm not sure if that exception applies to key-value pairs with plan scalar as a key though.

**Comment by puzrin** [comment]
Ok. Let's keep it to clarify sometime. But that's not a high-priority bug.

**Comment by asomov** [comment]
Sorry guys. This is confusing. I should have created separate issues. I must say that YAML 1.2 is very counter-intuitive in this case.
I think you can safely close this issue until I myself understand how it should work.

By the way, why the first scalar is string and the second scalar is integer ?
{1: 2} => { '1': 2 }

P.S. Great job guy ! You have a good result implementing YAML 1.2.
Do you have a mailing list for general questions ?
I am busy implementing YAML 1.2 in SnakeYAML and I use your parser as a reference implementation.

**Comment by puzrin** [comment]
> Do you have a mailing list for general questions ?

No.

- There are generic IRC channel for yaml spec devs, dig yaml site for contacts.
- You can also try to create ticket with specific question about js-yaml implementation, but be sure to show in title that this is not a bugreport.
- If you do yaml parser implementation - note, that this parser has a couple of unresolved issues due design errors. We had no time to one more parser rewrite :) . Be careful to not take those bugs into your implementation. All details are available inside issues.

**Comment by asomov** [comment]
Thank you for the clarifications.

**Comment by dervus** [comment]
@asomov The biggest problem with current JS-YAML design came from attempt to mix element parsing and tree structure building into one-pass process for sake of performance. This caused hard bugs, which still aren't fixed. I see ways to fix them and keep one-pass pass architecture anyway, but splitting it into two passes would clearly made JS-YAML much less complicated and buggy in the first place.

**Comment by asomov** [comment]
Well, we are considering also to sacrifice the recommended process to achieve better performance.
What would you recommend ? Is it worth to try to implement one-pass parsing ?

**Comment by puzrin** [comment]
Nobody can say exactly, until you try and run benchmark. We had no time to try everything.

**Comment by dervus** [comment]
I believe that two-pass (element parser/tree builder) or even three-pass (lexer/element parser/tree builder) designs may be about the same as one-pass in performance if implementation is good. I actually had a plan for that as JS-YAML 4.0, but I don't actively work on this project anymore.
