### ISSUE TITLE
YAML 1.2 spec: Example 8.2. Block Indentation Indicator

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#253]
When I try to parse example 8.2 at http://www.yaml.org/spec/1.2/spec.html#Block
I got:

```
[ 'detected\n',
  '\n\n# detected\n',
  '\n explicit\n',
  '\n\t\ndetected\n' ]
```

But according to the canonical form last two lines must not get a leading '\n':

```
%YAML 1.2

---
!!seq [
  !!str "detected\n",
  !!str "\n\n# detected\n",
  !!str "·explicit\n",
  !!str "\t·detected\n",
]
```

**Comment by dervus** [comment]
For fix squad reference:

1. Seems like explicit indent identifier adds a linefeed to begin of result.
2. Folding works wrong when concatenating line "\t" with "foo". Expected: "\t foo"; actual: "\t\nfoo".

**Comment by dervus** [comment]
Second part is still not clear. @aepsilon pointed that it's possible spec bug in #278

> For part 2 of #253, it appears the spec has an error.
>
> `' \t'` is a more-indented line according to the grammar, since `\t` is `s-white`.
> > [177] s-nb-spaced-text(n) ::= s-indent(n) s-white nb-char*
>
> (Rule [175] for folded lines doesn't match)
> Therefore join with a newline.
>
> LibYAML 0.1.5 agrees.
> It throws an error on the example, but if you specify indent with` >1`, it also produces `'\t\ndetected\n'`.

I think this need further investigation. I'll need to review that part of the spec by myself as well.

**Comment by asomov** [comment]
too old
