### ISSUE TITLE
YAML 1.2 spec: Example 8.13 (leading \n)

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#254]
The example 8.13 defines (according to the canonical YAML) a leading LF.

```
>
 folded
 line

 next
 line
   * bullet

   * list
   * lines

 last
 line

# Comment
```
Canonical:
```
%YAML 1.2
---
!!str "\n\
      folded line\n\
      next line\n\
      \  * bullet\n
      \n\
      \  * list\n\
      \  * lines\n\
      \n\
      last line\n"
```
The leading \n is missing in JS-YAML demo:
`'folded line\nnext line\n  * bullet\n\n  * list\n  * lines\n\nlast line\n'`

**Comment by asomov** [comment]
I am not sure that this is a bug. May be the canonical YAML must be fixed.

**Comment by dervus** [comment]
This is really a spec's bug. See https://github.com/yaml/yaml-spec/issues/2

**Comment by dervus** [comment]
I opened an issue in YAML spec repo: https://github.com/yaml/yaml-spec/issues/24
