### ISSUE TITLE
How to test YAML 1.2 compliance

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#255]
Hi, 
this is just a question. 
How do you test  YAML 1.2 compliance ? Do you copy-and-paste  the examples into the test suite ?
I would like to know it to see how we can also implement YAML 1.2 (for statically compiled language)

**Comment by puzrin** [comment]
We initially taken tests from lib-yaml, then added manually the rest after rewrite and bugfixes. Yaml 1.2 was in somewhere in the middle of rewrite phases.

I don't know if compliance suites are available.

**Comment by asomov** [comment]
Well, in SnakeYAML we took the same approach for YAML 1.1 - the compliance tests were taken from PyYAML.
Now I wanted to do the same with YAML 1.2 - copy-and-paste examples from specification and compare the result of parser with the canonical result from the spec. Unfortunately, the spec has a lot of small bugs which does not allow to use the examples "as is". 
I wonder how to continue: to wait until all the issues (https://github.com/yaml/yaml/issues) are resolve or just create and maintain my own test suite.
