### ISSUE TITLE
YAML 1.2 spec Example 8.17: unexpected null

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#256]
The "Example 8.17. Explicit Block Mapping Entries"
```
? explicit key # Empty value
? |
  block key
: - one # Explicit compact
  - two # block value

```
is parsed as 
`{ 'explicit key': null, 'block key\n': [ 'one', 'two' ] }`
but the canonical form is:
```
%YAML 1.2
---
!!map {
  ? !!str "explicit key"
  : !!str "",
  ? !!str "block key\n"
  : !!seq [
    !!str "one",
    !!str "two",
  ],
}
```
As you can see the value of  "explicit key" is expected to be empty string, but it is parsed as null.

(BTW, SnakeYAML also parses it as null, it is unclear if it a bug in spec or in implementation)

**Comment by dervus** [comment]
Well, what we have for first pair's value is an empty node. From YAML spec:

> YAML allows the node content to be omitted in many cases. Nodes with empty content are interpreted as if they were plain scalars with an empty value. Such nodes are commonly resolved to a “null” value.

So null is resolved value. For canonical representation it's an empty string, since there're no nulls there. AFAIK it's not possible to disable null "resolving" in JS-YAML, but this isn't a practical use-case, and JS-YAML is all about practical use.

**Comment by asomov** [comment]
I found the answer: it depends on the schema. If Schema allows 'null' value it should be used. 
Is it possible to configure  js-yaml to use failsafe schema ? (where the null value is not supported):
http://www.yaml.org/spec/1.2/spec.html#id2802346

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#safeload-string---options- see options

**Comment by asomov** [comment]
Thank you. Wow, you have done a lot !

**Comment by dervus** [comment]
@asomov JS-YAML have support for schemas, but the API we have for it doesn't allow to implement some non-practical schema features, and therefore we have only pseudo-support for failsafe schema, and it will only prevent `null` to be resolved as null, but empty nodes will continue to be null.

**Comment by asomov** [comment]
I think I will also sacrifice YAML 1.2 (confusing) purity for practical cases. 
I will check how it is done here, and if it matches my expectation I will just do the same.
At least if somebody tries to parse YAML with both parsers they will get the same result.
(BTW, I am not aware of any other available YAML 1.2 parser - js-yaml is the only one)

**Comment by dervus** [comment]
Actually there's reference implementation in Haskell: http://hackage.haskell.org/package/YamlReference

**Comment by asomov** [comment]
Well, I could not make it work at all.
