### ISSUE TITLE
Example 8.18. Implicit Block Mapping Entries = fails to parse

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#257]
The "Example 8.18. Implicit Block Mapping Entries"

```
plain key: in-line value
 :  # Both empty
"quoted key":
- entry
```

 fails with an error:

```
bad indentation of a mapping entry at line 2, column 2:
     :  # Both empty
     ^
```

**Comment by eemeli** [comment]
This is not a parser bug, it's intended behaviour. [Example 18.8](https://yaml.org/spec/1.2/spec.html#id2798896) in the spec uses the `°` glyph to represent empty scalars, i.e. it's not meant to have a character representation in the YAML source. This is explained in section 7.2 of the spec, [Empty Nodes](https://yaml.org/spec/1.2/spec.html#id2786563):
>In the examples, empty scalars are sometimes displayed as the glyph “°” for clarity. Note that this glyph corresponds to a position in the characters stream rather than to an actual character.

Other parsers also fail with the same input, as they should:

```js
import YAML from 'yaml'

const src = `
plain key: in-line value
 :  # Both empty
"quoted key":
- entry\n`

YAML.parse(src)
  // throws YAMLSemanticError:
  // Nested mappings are not allowed in compact mappings

**Comment by puzrin** [comment]
Thanks for clarification!
