### ISSUE TITLE
[writer] Shorthandable tags are not shorthanded

### ISSUE THREAD

**Issue by diegonc** [nodeca/js-yaml#258]
Hello

I'm using this library to parse a configuration format where I added some custom types. These custom types are constructed and represented through some types I'm writing. All of the types are collected in a custom schema. (By the way, schemas work great and makes the library very extensible :)

Below I copy the input I'm parsing:

```
d: !!lp/fnref log
```

And this is the output I get after loading the YAML text and dumping the data structure

```
d: !<tag:yaml.org,2002:lp/fnref> log
```

Is there anyway I can tell `js-yaml` to dump tag names in the short representation I used in the input?

**Comment by dervus** [comment]
This is not implemented. By the way, we should had an improvement-ticket for this since 2.0 release. Forgotten stuff. Let it be such a ticket then.

**Comment by rlidwka** [comment]
Fixed in https://github.com/nodeca/js-yaml/commit/a583097bbce25e2938e76f89b42e5fdabc9d6c60 (currently in `dev` branch).
