### ISSUE TITLE
YAML 1.2: Example 8.21. Block Scalar Nodes

### ISSUE THREAD

**Issue by asomov** [nodeca/js-yaml#259]
Example 8.21. Block Scalar Nodes
```
literal: |2
  value
folded:
   !foo
  >1
 value
```
is parsed as:
`{ literal: '\nvalue\n', folded: ' value\n' }`
But the canonical YAML:
```
%YAML 1.2
---
!!map {
  ? !!str "literal"
  : !!str "value",
  ? !!str "folded"
  : !<!foo> "value",
}
```
As you can see both "value"s do not have a trailing \n, but it was added by the js-yaml parser.

**Comment by dervus** [comment]
This is a spec's bug. See https://github.com/yaml/yaml-spec/issues/2
