### ISSUE TITLE
Invalid JSON parses without error

### ISSUE THREAD

**Issue by whitlockjc** [nodeca/js-yaml#262]
Right now I'm currently using `YAML.safeLoad` on some JSON that is structurally invalid.  It's got a trailing comma like this:

```js
{
  "key": {

  },
}
```

If I use `JSON.parse` on this, I get an error.  With `YAML.safeLoad`, I do not.  I am not sure where I stand on this but I have a user that would expect an error to be thrown so I figured I'd bring it up.  Thoughts?

**Comment by dervus** [comment]
This is valid YAML through. If you need to validate a JSON document, you must use a JSON parser for that.

**Comment by whitlockjc** [comment]
Thanks.  I figured that was the case but I wanted to make sure.
