### ISSUE TITLE
Get line and column numbers for specific path

### ISSUE THREAD

**Issue by zanona** [nodeca/js-yaml#264]
Hello there,
I am trying to retrieve the column and line numbers for a specific path provided to a yaml document but I am not sure if it's possible to retrieve that information with js-yaml?

with https://github.com/connec/yaml-js/ I can use the `compose` method and walk through the created JSON tree analysing `tag`, `value`, `start_mark` and `end_mark` however I was really looking forward to use js-yaml instead since it  feels much faster.

Thank you in advance

**Comment by puzrin** [comment]
No, we do not create AST, that's not possible now.

**Comment by szhyvotov** [comment]
Hi there! Any updates on this?
