### ISSUE TITLE
Can we use 1.1 spec parser version

### ISSUE THREAD

**Issue by yuvalmorad** [nodeca/js-yaml#265]
Hi
Can we use this OS as 1.1 yaml parser?
Regards
Yuval

**Comment by puzrin** [comment]
Old version, 1.0.0 should understand yaml 1.1.

**Comment by yuvalmorad** [comment]
Hi
We found this option in the wiki
 legacy  (default: false) - makes the loader to expect YAML 1.1 documents if such documents have no explicit %YAML directive.
Is it valid for 1.1 yaml spec.
By the way is tab forbidden ONLY in 1.1 in Yaml?

**Comment by dervus** [comment]
`legacy` option as well as explicit %YAML 1.1 directive just makes the loader to throw a warning if you're using non-ASCII line breaks in the document.

The parser is written against 1.2 spec, and that's it. 1.2 is backward-compatible with 1.1 in most ways — the most noticeable difference is Boolean literals. I'm not sure why are you so bothered about this.

**Comment by dervus** [comment]
> By the way is tab forbidden ONLY in 1.1 in Yaml?

There's no such thing as "forbidden". In 1.2 Tab is considered as content, i.e. not indentation. I'm not familiar with 1.1 on this.

**Comment by kaizer200** [comment]
> By the way is tab forbidden ONLY in 1.1 in Yaml? 

> 

Hi dervus; 
I disagree with your comment
check yaml spec 1.2 ,[ section 5.5-white space charecters](http://www.yaml.org/spec/1.2/spec.html#id2775170)
in 1.2 spec, **tab** and space are considered whitespace characters and CAN be used for indentation.

Quoting from [section: 6.2. Separation Spaces](http://www.yaml.org/spec/1.2/spec.html#id2778241):
> Outside indentation and scalar content, YAML uses white space characters for separation between tokens within a line. Note that such white space may safely include tab characters

> 

further more, quoting from [section: 6.1 Indentation Spaces](http://www.yaml.org/spec/1.2/spec.html#id2777534):

> In YAML block styles, structure is determined by indentation. In general, indentation is defined as a zero or more space characters at the start of a line

> 

Yaml spec 1.2 direct the "space characters" from the quote above  to section 5.5 - defining these spaces as  **tabs**  and spaces.

In contrast to spec 1.2, spec 1.1 state the opposite to tab characters:
check yaml spec 1.1, [section 5.5. Miscellaneous Characters](http://yaml.org/spec/1.1/#id871856):

> An ignored space character outside scalar content. Such spaces are used for indentation and separation between tokens. To maintain portability, **tab characters must not be used** in these cases..

> 

Spec 1.1 also gives example 5.12 with code using tab which stated as Error. The same example is use in spec 1.2 section 5.5 - and in it is OK.
You can also check [section 6.3 (Separation spaces)](http://yaml.org/spec/1.1/#separation space/) in yaml spec 1.1

**Comment by dervus** [comment]
Indentation is defined by `s-indent` rule. `s-indent` is defined as `s-space × n` where `s-space` is strictly 0x20 codepoint. This parser is written against format grammar definition in the spec, not general description.
