### ISSUE TITLE
[writer] can we remove deprecated boolean strings ?

### ISSUE THREAD

**Issue by jeromew** [nodeca/js-yaml#266]
I saw in the dumper that there is an array

````js
var DEPRECATED_BOOLEANS_SYNTAX = [
  'y', 'Y', 'yes', 'Yes', 'YES', 'on', 'On', 'ON',
  'n', 'N', 'no', 'No', 'NO', 'off', 'Off', 'OFF'
];
````

I was wondering when this deprecation was introduced and if we could remove it altogether. This code adds unwanted quotes around "y" keys for example.

Thanks for your input. I could send a PR removing this.

If you want to keep compatibility ( write a 1.2 file, but read with a 1.0/1.1 reader), maybe it could be possible to add a dump option specifying which version of reader we target.

**Comment by dervus** [comment]
An option for disabling this backward-compatibly mode seems OK. Something like `ignoreLegacy` with default: false. @puzrin Any ideas on betetr option name?

**Comment by dervus** [comment]
Better name: `noLegacy`

**Comment by ixti** [comment]
IMO `compatMode` makes more sense in this case.

**Comment by puzrin** [comment]
IMHO unnecessary quoting is rare and saving quotes do not worth breaking compatibility.

`noLegacy` would be fine for 3.x

**Comment by dervus** [comment]
Since all options must default to false, `noCompatMode` is another variant.

**Comment by jeromew** [comment]
Ok, so a `noCompatMode: true` (default false) would mean that we target the most recent yaml version (whatever that is).

I will prepare a PR for this.
