### ISSUE TITLE
JS-YAML tries to load lib/js-yaml/schema/.js with SystemJS

### ISSUE THREAD

**Issue by olee** [nodeca/js-yaml#270]
After updating js-yaml, it tries to load `lib/js-yaml/schema/.js` because of `lib/js-yaml/schema/core.js` requiring the invalid file `var Schema = require('.js');`.

**Comment by puzrin** [comment]
Not sure i understand you right. Could you point to exact line with error? May be you try to use node files in browser instead of browserified version?

**Comment by olee** [comment]
That might be it.
The weird thing is that it worked before updating...

**Comment by puzrin** [comment]
Please provide minimal example how to reproduce,

**Comment by puzrin** [comment]
Close - seems not related to this project.
