### ISSUE TITLE
nbsp character breaks json conversion

### ISSUE THREAD

**Issue by zanona** [nodeca/js-yaml#273]
Apparently when having nbsp chars as separator, causes js-yaml to parse the document incorrectly.

For example: (nbsp character is between `region: Ceredigion`

```yaml
{ city: Aberaeron, region: Ceredigion }
```
```yaml
{ city: Aberaeron, region:☠Ceredigion } #visual representation
```

```json
{
  "city": "Aberaeron",
  "region: Ceredigion": null
},
```

Apparently when converting with [yamljs](https://github.com/jeremyfa/yaml.js) the document is parsed correctly independently of the `nbsp` char, generating:

```json
{
  "city": "Aberaeron",
  "region": "Ceredigion"
},
```

**Comment by puzrin** [comment]
All is done according to YAML 1.2 spec, yamljs is not reference parser.
