### ISSUE TITLE
Other repos have trouble with `browser: { buffer: false }`

### ISSUE THREAD

**Issue by wesleyb-io** [nodeca/js-yaml#275]
These are links to two Github issues showing unexpected trouble handling the `package.json` value `browser: { buffer: false }`:

- https://github.com/aurelia/webpack-plugin/issues/12
- https://github.com/jaredallard/nexe/issues/148#issuecomment-156815985

Here is documentation I could find on the `browser` property, or the lack thereof:

- https://github.com/defunctzombie/package-browser-field-spec
- https://docs.npmjs.com/files/package.json (no `browser` property mentioned)

Is `{ buffer: false }` a documented value?

**Comment by puzrin** [comment]
As far as i remember, that var was to avoid buffer shims add by `browserify`. Need to check what happens without it.

**Comment by puzrin** [comment]
> Is { buffer: false } a documented value?

That means "return `{}` when `require('buffer')`" for browserify.

I've changed workaround for Buffer use.
