### ISSUE TITLE
Number values get rounded

### ISSUE THREAD

**Issue by theganyo** [nodeca/js-yaml#277]
A scalar in the yaml of:

```
value: 8421999999999995999
```

Will be represented as a rounded number value of `8421999999999996000` in the Javascript once parsed.

Please see: https://github.com/apigee-127/magic/issues/21 for more information.

Thanks!

**Comment by puzrin** [comment]
http://stackoverflow.com/a/307200

That's JS restriction, not parser bug.

**Comment by theganyo** [comment]
Yes, and I pointed that out in the other thread. That said, I respectfully disagree that one should so cavalierly write off confusing and platform-specific behavior in the parsing of a platform-independent format. Arbitrary rounding is not part of the YAML spec and misrepresents the actual value specified. A simple load and dump of any given YAML should create equivalent YAML and this fails that simple test.

I would suggest that there are a number of ways this could be handled better including: warnings, errors, or adaptive behavior depending on the actual value in the YAML.

**Comment by puzrin** [comment]
> I would suggest that there are a number of ways this could be handled better including: warnings, errors, or adaptive behavior depending on the actual value in the YAML.

That may be resonable, but need an issue with clear suggestion. Current one just says about problem that can not be fixed anyhow.

**Comment by confuser** [comment]
@puzrin The main premise of using YAML for configuration files is that they provide static values. Having large integers being rounded without any warnings causes unexpected behaviour, regardless of the fact JS only supports 32bit integer operations. The fix for this would be to interpret it as a string, which is how many other JS Yaml based parsers handle this.

**Comment by puzrin** [comment]
JS has known limitations, for example with types `set` & `pair`. As i said - create an issue with your suggestions and refer to other implementations/spec as proof for possible workarounds.

**Comment by qgustavor** [comment]
How about handling this adding a option similat to [mysql's](https://github.com/mysqljs/mysql) `bigNumberStrings`? When this option is enabled numbers larger than `Number.MAX_SAFE_INTEGER` (and lower than `Number.MIN_SAFE_INTEGER`) are returned as strings instead of numbers.
