### ISSUE TITLE
Completion callback for loadAll

### ISSUE THREAD

**Issue by WorldMaker** [nodeca/js-yaml#285]
It would be most useful for working in async promises or [observables](http://reactivex.io/documentation/observable.html) if `loadAll` and `safeLoadAll` also accepted a callback for when the stream of documents has ended.

For completeness, it might also be useful to have a callback for errors.

Glancing at the implementation I'm also a little bit surprised that the documents aren't emitted immediately as they finish parsing, as you would suppose from the public API.

**Comment by puzrin** [comment]
All methods are sync and there are no plans to change that.

**Comment by WorldMaker** [comment]
Then why even pretend to have an async API at all? Why not just export loadDocuments directly instead of having an iterator callback?

Looking at the code, making it more async shouldn't even be that more complicated than the existing code. Does this mean you won't even accept PRs and I should expect to hard fork for async?

**Comment by puzrin** [comment]
There are NO async API here. Iterator != async. That's more like `array.forEach(...)`

**Comment by damonomad** [comment]
> All methods are sync and there are no plans to change that.

An async API would be nice. 

> Does this mean you won't even accept PRs and I should expect to hard fork for async?

I'd certainly be willing to contribute to async API, as well.

**Comment by puzrin** [comment]
IMHO you ask very strange things. Parser is completely synk. The only place where yielding could be useful in theory is parse huge multidoc streams, but i guess nobody use such things on practice. And that can be organized with simple wrapper for current implementation.

**Comment by WorldMaker** [comment]
Multi-doc streams is exactly my use case. It would be nice to pass in a NodeJS `Readable` stream and get documents as they arrive, observable style.

**Comment by dervus** [comment]
Parser accepts only String as input. In theory it's possible to add support for some king of streaming objects and therefore async API, but this would be much harder than it may seem due to current implementation.

**Comment by puzrin** [comment]
@WorldMaker if you don't have 500MB inputs, it doesn't worth to overcomplicate things, seriously. Doing wrapper for stream interface does not require current API change.

**Comment by WorldMaker** [comment]
@puzrin Size isn't the only performance consideration, there's also speed/latency. That's one of the reasons I picked YAML over alternatives like plain old JSON because it's syntax was built to support fast stream parsing and the ability to deal with chunks (documents) with somewhat low latency, parsed relatively quickly as soon as they come in. My mistake was in assuming the most well know implementation in this language was designed for that (as the spec certainly encourages it). Certainly I can do my own parsing (chunking input on my own from the stream by regexing around for `---` and `...` and some more complicated things), but it seems silly to me to wrap a parser in a mini-parser rather than just fixing the parser.

**Comment by puzrin** [comment]
I'm not sure if it's possible to do true document-level streaming with current architecture. When we designed this parser, we intentionally dropped such mode because it's almost never needed.

**Comment by arthurlacoste** [comment]
For other users who want to use this powerful lib with an async way, I found this wrapper:
https://github.com/jonschlinkert/read-yaml

But really, Promise &/or callbacks are really needed to be implemented here, the hell of try{}catch is done now. Let us hope it is gone forever.

**Comment by puzrin** [comment]
`Promise.resolve().then(() => yaml.safeLoad(...))`

:)
