### ISSUE TITLE
Exclamation mark or Node Tags are breaking the serialization

### ISSUE THREAD

**Issue by oscarsan** [nodeca/js-yaml#289]
When using Node Tags as defined in the YAML specs [here](http://www.yaml.org/spec/1.2/spec.html#id2784064) the serialization is throwing an exception

In the sample

    %YAML 1.2
    ---
    !XL.Handler
    Configuration: 
      Beacon: 
        UseBuzzer: True
      WidthAdjustment: 
        EnableWidthAdjustment: False
        ConveyorWidth: 1150
        ConveyorWidthOffset: 2000

Im getting a 

unknown tag !<!XL.Handler> at line 11, column 1:

**Comment by dervus** [comment]
You must define a type for that tag as shown in custom_types example: https://github.com/nodeca/js-yaml/tree/master/examples

**Comment by oscarsan** [comment]
Thanks, need much less than in the example, but it works

	    var ConfigYamlType = new jsyaml.Type('!XL.Handler', {
  		  kind: 'mapping',
  		  construct: function (data) {
    			return data;
  		  }
	    });
	    var CONFIG_SCHEMA = jsyaml.Schema.create([ ConfigYamlType ]);
	    var loaded = jsyaml.load(response, { schema: CONFIG_SCHEMA });


It is just enough in this case to return the data.
