### ISSUE TITLE
[writer]Surround string by double quote instead of simple

### ISSUE THREAD

**Issue by AlaricCalmette** [nodeca/js-yaml#290]
I would like to be able to take a json object like this :

```
{
    translation:
        { 
            key: 'this_is_a_key',
            value: 'this is a value'
        }
}
```

and output a yml file like this :

```
- translation :
    key: "this_is_a_key"
    value: "this is a value"
```

I've tried several method but was only able to achieve either

```
- translation :
    key: this_is_a_key
    value: this is a value
```

or 

```
- translation :
    key: '"this_is_a_key"'
    value: '"this is a value"'
```

note that in the latter this is not three quotes but a single quote followed by a double quote

Is there any way to do this with this module?

**Comment by dervus** [comment]
There's no settings for this at the moment. The dumper tries to choose "minimal" possible scalar style to represent each particular string.

Ability to specify preferred scalar styles would be nice addition though. Contributions on this matter are welcomed.

**Comment by AlaricCalmette** [comment]
Okay thanks for the answer, will see if i can contribute.

**Comment by xavier630** [comment]
Any news on this feature?

**Comment by ratacat** [comment]
I'd appreciate this too!

**Comment by rlidwka** [comment]
Fixed by https://github.com/nodeca/js-yaml/commit/7b256d7612a4c29cdf5dfd48a15e01c8dbbb5291 in **dev** branch, gonna be released later.

```js
console.log(require('js-yaml').dump({ key: "this_is_a_key" }, { quotingType: '"', forceQuotes: true }))
// outputs:
// key: "this_is_a_key"
```
