### ISSUE TITLE
Linebreaks being stripped

### ISSUE THREAD

**Issue by Naatan** [nodeca/js-yaml#293]
Take the following code snippet:

```
Foobar: >
  block of text

  Double linebreak
```

When converted to JSON it becomes:

```
{ Foobar: 'block of text\nDouble linebreak\n' }
```

While it should have become:

```
{ Foobar: 'block of text\n\nDouble linebreak\n\n' }
```

It appears to be treating double linebreaks as one.

**Comment by dervus** [comment]
It shouldn't. What you're writing of is behaviour of literal block scalar, the `|`. Also mind default trailing lines chomping method, which is the same for both literal and folded block scalars.
