### ISSUE TITLE
Mapping value indicator (":") and flow context

### ISSUE THREAD

**Issue by bd82** [nodeca/js-yaml#295]
Hello.

I think I may have found a slight deviation from the spec:

In [7.4.2. Flow Mappings](http://yaml.org/spec/1.2/spec.html#id2790832)
The use of ": " is defined as:
```
c-ns-flow-map-separate-value(n,c)	::=	“:” /* Not followed by an
       ns-plain-safe(c) */
```

ns-plain-safe(c) definition is dependent on the specific flow context.

```
[127] ns-plain-safe(c)	::=	
   c = flow-out  ⇒ ns-plain-safe-out
   c = flow-in   ⇒ ns-plain-safe-in
   c = block-key ⇒ ns-plain-safe-out
   c = flow-key  ⇒ ns-plain-safe-in	

[128]	ns-plain-safe-out	::=	ns-char	 
[129]	ns-plain-safe-in	::=	ns-char - c-flow-indicator
```

In [7.4. Flow Collection Styles](http://yaml.org/spec/1.2/spec.html#id2790088) the flow-out and flow-in are defined as: 
```
A flow collection may be nested within a block collection
(flow-out context), nested within another flow collection (flow-in context)
```

My understanding of this is the **c-flow-indicators** are only allowed to **immediately** follow a colon in a **nested** flow (flow-in) context. 

So while the following is legal YAML:
```yaml
# ":" followed by flow indicator "}"  inside another flow collection (flow-in).
- [1, {a:} ,3]
```

The following is **not** valid YAML:
```yaml
# ":" followed by flow indicator "}"  inside a block collection (flow-out).
- {a:}
```

However with JSYaml's online demo **both** of these are valid.

I'm not 100% sure I understood this correctly as YAML's is somewhat overcomplicated 😞 ...
Is this a real bug or a misunderstand on my part?

**Comment by dervus** [comment]
I spent some time trying to get all this into mind, but I came to conclusion that I have no fucking idea.

Sorry, but this issue tracker is intended for concrete bug reports and patch submissions. If you have questions like this, better ask them on YAML mailing list or IRC.

**Comment by puzrin** [comment]
[pyyaml demo](http://yaml-online-parser.appspot.com/?yaml=-+%7Ba%3A%7D%0A&type=json) shows the same as js-yaml demo.

@bd82 we do not keep spec in mind and can not consult about it. It's better to make preliminary comparisons at your side or contact yaml authors via IRC.
