### ISSUE TITLE
Tab after dash accepted as valid separator in collection elements

### ISSUE THREAD

**Issue by adrianth** [nodeca/js-yaml#297]
The following is parsed as valid YAML (replace [TAB] with an actual tab character):

```
collection:
  - element 1
  -[TAB]element 2
```

**Comment by dervus** [comment]
It does seem to conform the spec: http://www.yaml.org/spec/1.2/spec.html#c-l-block-seq-entry(n)
What's wrong?

**Comment by adrianth** [comment]
Ok, I figured out what is happening. I am consuming the YAML data in a Java application and leveraging the [SnakeYAML ](https://bitbucket.org/asomov/snakeyaml) library for parsing. However, they are still at [YAML 1.1](http://yaml.org/spec/1.1/current.html#id931893), which apparently only accepts space after the dash:

> Each block sequence entry is denoted by a leading “-” indicator, separated by spaces from the entry node.

Never mind, then. Thanks for looking into this.
