### ISSUE TITLE
Incorrect handling of datetime keys

### ISSUE THREAD

**Issue by adius** [nodeca/js-yaml#309]
```js
yaml.safeLoad(
`2016-01-01 12:34:56.789: foo
2016-01-02 12:34:56.789: bar
`)
```

and

```js
yaml.safeLoad(
`? 2016-01-01 12:34:56.789
: foo
? 2016-01-02 12:34:56.789
: bar
`)
```

yield

```js
{
  'Fri Jan 01 2016 12:34:56 GMT+0000 (UTC)': 'foo',
  'Sat Jan 02 2016 12:34:56 GMT+0000 (UTC)': 'bar'
}
```

but should yield

```js
new Map([
  [new Date('2016-01-01T12:34:56.789Z'): 'foo'],
  [new Date('2016-01-02T12:34:56.789Z'): 'bar']
])
```

… or at least

```js
{
  '2016-01-01T12:34:56.789Z': 'foo',
  '2016-01-01T12:34:56.789Z': 'bar'
}
```

or

```js
{
  '2016-01-01 12:34:56.789': 'foo',
  '2016-01-01 12:34:56.789': 'bar'
}
```

**Comment by puzrin** [comment]
That's not date-specific issue. Objects as keys are not supported due JS limitations. And probably will not. We discussed maps somewhere in other issue.

**Comment by adius** [comment]
That's why I added the "at least" part 😉

I guess this would be the best solution for the time being:
```js
{
  '2016-01-01 12:34:56.789': 'foo',
  '2016-01-01 12:34:56.789': 'bar'
}
```

**Comment by puzrin** [comment]
I think we can not define "right" `.toString()` for every possible object. Don't see reason to make exclusion for `Date`.

**Comment by adius** [comment]
Well, actually JavaScript has already a YAML serializer integrated: `JSON.stringify()` (as JSON is a subset of YAML).
Therefore we should use `JSON.stringify()` instead of `.toString()` and `JSON.stringify(new Date('2016-01-01T12:34:56.789Z'))` yields `2016-01-01T12:34:56.789Z` and not `Fri Jan 01 2016 12:34:56 GMT+0000 (UTC)`

**Comment by puzrin** [comment]
I think it's better to continue discuss everything in #169.

ok?

**Comment by adius** [comment]
Yes, I guess that's a good idea.

I just realized that `'2016-01-01 12:34:56.789': 'foo'` would be even worse as it's still incorrect (still a String instead of a Date object), but it's harder to spot.
At the moment one at least immediately realizes that something is wrong…
