### ISSUE TITLE
Consider separating CLI from main package.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [nodeca/js-yaml#314]
The five most popular dependants of `js-yaml`, [`eslint`](https://www.npmjs.com/package/eslint), [`istanbul`](https://www.npmjs.com/package/istanbul), [`svgo`](https://www.npmjs.com/package/svgo), [`grunt`](https://www.npmjs.com/package/grunt), and [`cosmiconfig`](https://www.npmjs.com/package/cosmiconfig) do not seem to use the CLI.  Would it be reasonable to move the CLI for `js-yaml` to another package, something like `js-yaml-cli`?  Excluding the `argparse` dependency would save ~140 KB.

**Comment by puzrin** [comment]
1. That's not convenient for maintenance
2. I don't like arguments about abstract size save on server.
