### ISSUE TITLE
Quoting error cited as indentation error

### ISSUE THREAD

**Issue by alapidas** [nodeca/js-yaml#315]
Trying to parse the document:
```
blah: 
  - "He said "Hi!" to his friends"
```
gives the following error:
```
bad indentation of a sequence entry at line 2, column 15:
      - "He said "Hi!" to his friends"
                  ^
```
This is really a quoting issue (inner quotes need to be escaped).  Is it possible to have the Error that gets thrown reflect that, instead of calling it an indentation error?

**Comment by puzrin** [comment]
No, that's not possible to guess right error without significant parser rewrite.
