### ISSUE TITLE
Support glob in `CLI`

### ISSUE THREAD

**Issue by evilebottnawi** [nodeca/js-yaml#318]

**Comment by puzrin** [comment]
It's not clear what exactly do you mean and why this should be in CLI.

**Comment by evilebottnawi** [comment]
@puzrin i am use `npm` scripts for linting and testing and it would be convenient to scan all files for validity using `"lint:yaml": "js-yaml '**/*.yaml' -c"`

**Comment by puzrin** [comment]
That's a specific case, and i think it would be better move it to external script or shell command instead. There are no plans to make js-yaml CLI too clever, sorry.

**Comment by puzrin** [comment]
See https://github.com/eslint/eslint/blob/master/package.json#L10 for example.

**Comment by evilebottnawi** [comment]
@puzrin when the project is a small try to avoid the use `Makefile.js` and use only `npm` scripts, probably easier to make an additional package

**Comment by puzrin** [comment]
I also try to avoid custom CLI scripts, but do not worry when this way is more simple https://github.com/nodeca/unhomoglyph/blob/master/package.json#L18.

**Comment by circa10a** [comment]
`find . -name "*.yaml" -exec js-yaml {} \;` is an alternative to put in npm scripts.
