### ISSUE TITLE
Syntax error in array [,] parsed as [null]

### ISSUE THREAD

**Issue by mayacoda** [nodeca/js-yaml#321]
Hello,

I'm using js-yaml in a code editor that supports json and yaml user input and then transforms the content (if it is valid) into javascript objects for further manipulation. 

I've encountered the following bug: If an array contains an extra comma `,`, instead of throwing an exception for invalid yaml or json, the parser transforms the value into `null`. Although I include several other options, this is the simplest case in which the error occurs.

**Code snippet:**
```javascript
var yaml = require('js-yaml');

var result = yaml.safeLoad('[,,]');
```

**Expected:** 
YAMLException is thrown

**Actual:**
```javascript
result === [null, null]
```

**Comment by puzrin** [comment]
Seems to be a bug. libyaml-based parsers return error

- http://yaml-online-parser.appspot.com/
- http://ben-kiki.org/ypaste/

@dervus ?

**Comment by rlidwka** [comment]
Fixed in https://github.com/nodeca/js-yaml/commit/adfee179ba85e5a2d2023f010d586b7209fdb083 (currently in dev branch, gonna be released as js-yaml 4 later).
