### ISSUE TITLE
Force js-yaml to 1.1 mode

### ISSUE THREAD

**Issue by JeffUberman** [nodeca/js-yaml#322]
I'm upgrading from js-yaml v3.2.7 to x3.7.0, but need yaml to be parsed to 1.1 spec. My understanding is that docker compose supports yaml 1.1. Is there a way to force js-yaml to parse to yaml 1.1?

**Comment by puzrin** [comment]
yaml 1.1 support was dropped many years ago. You can try old 0.3 version. Or use http://nodeca.github.io/js-yaml/ to check your yaml files, may be problem is not there.

**Comment by JeffUberman** [comment]
Ok, thanks so much for the response!

**Comment by JeffUberman** [comment]
Following up on this: Is there a way to force js-yaml NOT to include the `>-` multiline character tag? I had a previous version (v3.2.7) that did not include this; however, in upgrading to v3.7, `>-` is now included.

**Comment by puzrin** [comment]
We do not support syntax control on such level. Goal is to properly implement latest yaml spec (now 1.2).

If you find that spec is implemented with bug, please post code sample how to reproduce, expected result and reference to spec what is wrong.

**Comment by JeffUberman** [comment]
Ok, thank you for the clarification and for taking the time to respond!
