### ISSUE TITLE
Support YAML maps and sets to ES6/ES2015 Maps and Sets

### ISSUE THREAD

**Issue by js-choi** [nodeca/js-yaml#329]
js-yaml current converts YAML `!!map` and `!!set` data structures to JavaScript objects with enumerated keys. It would make sense and be useful to optionally convert YAML `!!map`s and `!!set`s to ES6 / ECMAScript 2015 `Map`s and `Set`s instead; they would also support non-string keys and be convertible back to YAML `!!map`s and `!!set`s.

**Comment by puzrin** [comment]
Seems dupe of #169.

I this request "just for fun" of you have real use-cases when maps/sets required?

**Comment by js-choi** [comment]
It's not a very complicated use case. My codebases (many of which involve wide-breadth tree manipulation) use Maps and Sets already, and I would like to be able to serilaize and deserialize those data into YAML without allocating unnecessary objects returned by js-yaml. I would also use the YAML to interchange the data with old non-JS programs, which sometimes do use non-string keys.

**Comment by puzrin** [comment]
It doesn't matter if use case is complicated or not. It make sense if use case is valuable for others and follows yaml spirit. I understand that it's technically possible to use maps & sets in DB. But in general, it's not a great idea to use yaml for DB serialization. Yaml is intended first to be human readable.

Also, as you can see from 169, there are bad side effects with maps.

In short - situation with maps/sets is known, but there are no plans to modify current behaviour in nearest future.

**Comment by js-choi** [comment]
My use case does not involve YAML for entire databases, but rather interchanging JavaScript objects, many of which are Maps and Sets, between programs and serializing them into a format that can be read and edited by human users. These are primarily for configuration files with complex data, such as specifying chains of tasks in syntactic data structures that form a DSL. These configuration files need to be able to distinguish sequences, sets, and maps. There are similar use cases for general graph serialization. In other programming languages such as Python and Clojure, I've used YAML as well as [EDN](edn-format.org) and [Transit](https://github.com/cognitect/transit-format) for similar uses.

Having said all that, if adding support for Maps and Sets would induce side effects that affect existing users of this library, then I understand being adverse to doing so. I had assumed that it would be a matter of adding an opt-in mode while keeping previous behavior the same. Thank you for considering and responding to this issue; I will find another solution.

**Comment by puzrin** [comment]
Problem is that yaml makes no difference between hashes (JS objects with simple keys) and maps. Option can only force to use maps everywhere, not in specific cases. But that makes result ugly for JS, as discussed in #169.

Sets are postponed, because maps are less important than maps.

To move forward, need to invent good solution what to do with maps, if people wish to work with hashes in most cases (even when maps used in some places of document).

**Comment by js-choi** [comment]
To be technical, the YAML specification does not require that non-tagged mapping nodes (i.e., those with the implicit `?` non-specific tag) have the same type as mapping nodes tagged with `!!map` (`tag:yaml.org,2002:map`) or even the `!` non-specific tag. (For more on non-specific tags, see also [§ 3.3.2 Resolved Tags, first paragraph](http://www.yaml.org/spec/1.2/spec.html#tag/non-specific/) and [§ 6.9.1 Node Tags, Non-Specific Tags](http://www.yaml.org/spec/1.2/spec.html#id2784064).) Instead, non-tagged mapping nodes’ types are determined by the application schema’s tag resolution.

This provides easy, standard ways to distinguish objects from maps. For instance, the Mozilla Developer Network gives the following example for ES Maps:

    var myMap = new Map();

    var keyString = 'a string',
        keyObj = {},
        keyFunc = function() {};

    // setting the values
    myMap.set(keyString, "value associated with 'a string'");
    myMap.set(keyObj, 'value associated with keyObj');
    myMap.set(keyFunc, 'value associated with keyFunc');

…which requires distinguishing between `Map`s and generic objects.

Under an opt-in schema, that `Map` might be written as the following:

    ! a string: value associated with 'a string'
      {}: value associated with keyObj
      !!js/function 'function() {}': value associated with keyFunc

…whose non-specific tags would then resolve to:

    !map
      !str a string: value associated with 'a string'
      !!js/object {}: value associated with keyObj
      !!js/function 'function() {}': value associated with keyFunc

In this schema, `?`-tagged YAML mappings (i.e., non-tagged mappings) resolve into ES Maps. A user might opt into this schema the usual way:

    const YAML = require('js-yaml');
    YAML.load(`...`, { schema: YAML.ES_CORE_SCHEMA });

However, the *default* schema (`DEFAULT_SAFE_SCHEMA`) would remain the same for backwards compatibility; no existing users’ code would be affected as far as I could tell.

In any case, if there is little demand for this, then that is fine. I’m figuring out a solution myself. Thanks again for the response. I'll close this issue for now.

**Comment by puzrin** [comment]
You can split out tagged maps (!!map), but problem still remains with default (untagged) mapping notation. AFAIK, YAML spec allows maps there too. And it's not clear what to do there.

It's possible to use auto-detect, but you'll get another side effect - yaml.load(yaml.save) / yaml.save(yaml.load) will change result sometime. + possible performance loss (need more deep changes to optimize).

I think it's possible to invent something, but that requires to spend some time and talk with spec authors on IRC. Nobody did it yet and i have no plans to do it myself in nearest future. If anyone ever provides solid resolution for pending spec issues (how to do), i will try to allocate resources for implementation (coding).

**Comment by js-choi** [comment]
I understand—it’s reasonable for you to have no plans to implement this. I’m still confused about some of the comments about the specification, though; would you mind clarifying what you mean for me?

I’m uncertain how there would be a problem with untagged (i.e., `?` non-specific tagged) mappings. In the schema proposed above, untagged (`?` non-specific tagged) mappings would *always* resolve to plain JavaScript objects. However, `!` non-specific tagged mappings would *always* resolve to `tag:yaml.org,2002:map`, which would correspond to JavaScript `Map`s (in this schema).

Indeed, the function of the `!` non-specific tag is to “quote” a node, ‘allow[ing] the author of a YAML character stream to effectively “disable” the tag resolution process. By explicitly specifying a “!” non-specific tag property, the node would then be resolved to a “vanilla” sequence, mapping, or string, according to its kind.’). No dynamic auto-detection based on keys or whatever would be required.

As far as I can tell, the above would be deterministic, and round-trip conversion would be lossless. It would be just another YAML schema.

Furthermore, there would be no performance regression for existing code: the schema would be opt-in; the default schema would remain `DEFAULT_SAFE_SCHEMA`. `DEFAULT_SAFE_SCHEMA` would still resolve both `?`- and `!`-non-specifically-tagged mappings (as well as all other mappings with tags resolved into `tag:yaml.org,2002:map`) as plain JavaScript objects.

My apologies if I’m misunderstanding something. Thanks in advance, and thank you again for js-yaml.

**Comment by puzrin** [comment]
See [example](http://nodeca.github.io/js-yaml/#yaml=WyBhLCBiIF06IFsgYywgZCBd)

AFAIK, it should be a map. Adding maps support only for `!!map` looks strange IMHO. I think, not supporting maps looks more "logical" than partial support (in terms of following specification).

That should be discussed with spec authors.

/cc @ingydotnet

Other spec-related issues are marked as [uncertain](https://github.com/nodeca/js-yaml/issues?q=is%3Aissue+is%3Aopen+label%3Auncertain)
