### ISSUE TITLE
Float cast broke the file parsing

### ISSUE THREAD

**Issue by mattiaocchiuto** [nodeca/js-yaml#333]
Hello, I'm trying to load a yml file having a float cast (example below) but the script end with an error.

```
test:
	name: !!float 2550
```

I've double checked in the online parser (https://nodeca.github.io/js-yaml/) but it still return the same error.
Does I'm doing something wrong?

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=dGVzdDoKICBuYW1lOiAhIWZsb2F0ICIyNTUwLjAi

Seems to be a bug. When number has dot, that works

```
test:
  name: !!float "2550.0"
```

/cc @dervus

**Comment by puzrin** [comment]
Example 10.7 from spec

```
negative: !!float -1
zero: !!float 0
positive: !!float 2.3e4
infinity: !!float .inf
not a number: !!float .nan
```

First 3 lines fail. Ups...
