### ISSUE TITLE
How not to quite a string in safeDump()

### ISSUE THREAD

**Issue by wzhliang** [nodeca/js-yaml#336]
I'm not sure how js-yaml decide to quite a string or not. I have a YAML object that has arrays, map, etc. Sometimes, the value is quoted:

     key: 'value'

and sometimes, it's not:

     key: value

How to make sure it doens't quote the string?

[EDIT] I think what happens is that js-yaml looks at a string and try to see if it's **indeed** a string and add quotes when it sees fits. 2 situation I've seen: a string that starts with a `{`, or a string that start with a digit. Not sure if this is helping.

**Comment by puzrin** [comment]
Strings are quoted when content can be resolved back as not string, or when some special chars exists. In other words - quotes appears when content can not be loaded back without those.

It's better to look into source code for details https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/dumper.js

**Comment by Bergmaier** [comment]
@puzrin Is it possible to force a specific string format using the `styles` option?

**Comment by puzrin** [comment]
no
