### ISSUE TITLE
How do I run js-yaml?

### ISSUE THREAD

**Issue by Rui90** [nodeca/js-yaml#341]
Hi, I followed the steps that you posted in the first page and I endeded up with the following folder settings that you can find on this picture:

[Picture - Imgur](http://imgur.com/a/3Uxn7)

Folders definitions and paths are being referred by my **index.yaml**

I already tried to execute the following commands:

```
node js-yaml index.yaml
node index.js index.yaml
js-yaml index.yaml 

```
But nothing happens, I do not understand how to use it.

**Comment by puzrin** [comment]
- If you install with `-g`, then `js-yaml -h` should work (i just checked it).
- If you install locally, without `-g`, then `./node_modules/.bin/js-yaml -h` should work.
