### ISSUE TITLE
Option to omit space between array elements

### ISSUE THREAD

**Issue by felixfbecker** [nodeca/js-yaml#346]
We like to encode objects and arrays to query parameters using YAML. The parser is able to parse this correctly:

![image](https://cloud.githubusercontent.com/assets/10532611/25774286/d1d5f0d8-328c-11e7-9e20-164b8bd8a18e.png)

But unfortunately, the dumper always adds unneeded spaces between array elements:

![image](https://cloud.githubusercontent.com/assets/10532611/25774341/53018a8c-328d-11e7-9469-010f01bb52ac.png)

We don't encode `[]` for prettiness and browsers can handle them fine (PHP has used them forever), but spaces of course do need to be encoded, which is not very pretty.

Here are the options I am currently using to output single line YAML:
```js
yaml.safeDump(value, { flowLevel: 0, indent: 0, lineWidth: Infinity, noCompatMode: true, sortKeys: true })
```
It would be great to have an option for omitting these non-required spaces / emitting "minimized" YAML.

**Comment by puzrin** [comment]
IMHO that's a madness to use yaml parser/dumper such way :). It's not intended for URL encoding. Goal of dumper is to create pretty human-readable result. May be it creates something close to your wishes... by accident... but that's not enougth to add as official option.

I tend to reject as "out of project scope", but if i miss something important, please explain.

**Comment by felixfbecker** [comment]
Well, what is the project scope? According to the readme:

> This is an implementation of YAML, a human-friendly data serialization language.

Good applications should have readable, human friendly URLs, at the same time complicated applications have complicated data to serialize in the URL. A clear use case for a human-friendly data serialization language.

Basic `key=value` encoding doesn't fill that need, the data model is too basic. Some applications use styles like `array[]=1&array[]=2` to encode nested structures but that bloats quickly and doesn't achieve the goal of good readability.

JSON can encode nested data, but results in bloated output and lots of reserved characters because of the required quotes everywhere.

YAML sits perfectly in-between, supporting all data structures of JSON with the simplicity of basic, unquoted `key=value` pairs.

It fits directly into the project scope imo. It doesn't create something close to what I want by accident, it creates something close to what I want because what I want (a human friendly yet powerful data serialisation) is exactly what this project offers (a human friendly yet powerful data serialisation) 🙂 .

I understand that you don't want to commit to maintaining a lot of code for rare use cases, but I imagine the implementation and maintenance cost of this to be minimal. There are already great options to control the line breaking behaviour, I don't think an option to omit the added space in this single case (array elements) would hurt.

**Comment by puzrin** [comment]
Ok, PR with condensed flow mode support will be accepted.

**Comment by puzrin** [comment]
Closing to keep tracker clear. But if anyone decide to create PR - that will be accepted.
