### ISSUE TITLE
Option for custom duplicate key handling

### ISSUE THREAD

**Issue by dennisreimann** [nodeca/js-yaml#348]
This is more a question than an issue: There is the `json` option, which allows for duplicate keys. It changes the regular behaviour to overwrite previously defined keys instead of throwing an error.

I would like to discuss/propose a change that would extend the `json` option – or maybe better yet introduce a new option – to define a function that allows for a custom handling of duplicate keys.
Use case: The `json` option overwrites keys completely and one would like to deep merge the existing structure with a partial one, which is the value of the duplicate key.

This logic could be implemented with a check for an already defined `_result[keyNode]` here:
https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/loader.js#L309
It would then call the function provided via the option with `_result[keyNode]` (current value) and `valueNode` (new value, in the described use case the one that gets merged into the current value) and return the merged result.

My intent is to discuss the idea and possible implications of it, which I might not be aware of. Thanks! :)

**Comment by puzrin** [comment]
Duplicated keys are not allowed by standard. `json` option is an exclusion with direct meaning - emulation of `JSON.parse()` behaviour. It's not expected to be extended et al.

If you need to merge configs - do it separate. No need to intrude into parser logic.

**Comment by dennisreimann** [comment]
Thanks for the fast reply. I can understand the concern, that's why I wanted to discuss this before sending a pull request. 

The downside of separating I see in this case is inconvenience, as the user has to define two separate sets of data that can then be merged after being parsed/loaded individually. Or is there a better way?

**Comment by puzrin** [comment]
IMHO, in general, it's bad idea to create complicated monolithic things. Yaml parser has enough mess, no need to make it more horrible :).

Later, you may wish to merge configs of different formats (XML/JSON for example), or change merge rules. Without strict separation every change will give you more problems, than you win with single module.

I know, many "novices", impressed by yaml custom classes, tend to use yaml as programming language. I think, that's a road to nowhere. Yaml was overengineered. I would recommend limit it's use to basic things - human readable simple object.

**Comment by dennisreimann** [comment]
Alright, thanks for your thoughts on that 👍
