### ISSUE TITLE
CLI no longer provides location of error

### ISSUE THREAD

**Issue by woodyrew** [nodeca/js-yaml#351]
The CLI behaviour has changed between node `v6` and `v7`.

Node `v6` with trace (`-t`) option - **Error and location**:
```
$ `npm bin`/js-yaml -t src/index.md
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 7, column 12:
    description: "Enterprise Content Management ... 
               ^
    at generateError (...
```

Node `v7` with trace (`-t`) option - **No useful information**:
```
$ `npm bin`/js-yaml -t src/index.md
Error
    at generateError (...
```

Node `v7` with compact (`-c`) option - **Error only**:
```
`npm bin`/js-yaml -c src/index.md
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key
```

I assume this is due to Node no longer providing the same level of detail for errors?
Is there a way to get the location of the error again in `v7`?

**Comment by puzrin** [comment]
Interesting. I don't use CLI and don't track what happens there.

Seems to be a bug.
