### ISSUE TITLE
Cannot parse & and * from JSON to YAML

### ISSUE THREAD

**Issue by fullammo** [nodeca/js-yaml#354]
Hey! 
I want to parse my json object to yaml format, and i come across some dificulties. If i enter the '&' sign to my string in a json property value, it parses the yaml with a single quatation mark, and it also applies to '*' sign and URLs ':' sign and the '[]' signs are causing this problem too , and it is not a valid YAML. I would really appriciate your help.

`var json = { collector: '&collectorip 192.168.1.1' }` this parses after a dump to this:

`collector: '&collectorip 192.168.1.1'` and i would like to get rid of the single quation marks without any hacks.
is it possible? :)

Thanks in advance,
fullammo

**Comment by puzrin** [comment]
[No](http://nodeca.github.io/js-yaml/#yaml=Y29sbGVjdG9yOiAmY29sbGVjdG9yaXAgMTkyLjE2OC4xLjEKCmNvbGxlY3RvcjI6ICcmY29sbGVjdG9yaXAgMTkyLjE2OC4xLjEn)

**Comment by fullammo** [comment]
Is there any way i can skip these charachters to be checked?

**Comment by puzrin** [comment]
No, we follow spec. Quotes are skipped only when possible. As you can see in example, your source without quotes be wrong after load.

**Comment by fullammo** [comment]
Okey, but this doesnt work the other way around. How do i specify in my JSON object anchors and other charachters?

**Comment by puzrin** [comment]
I think you need read yaml spec and play with demo, because your questions are not related to this project directly.
