### ISSUE TITLE
Wrongly assumes implicit mapping pair when colon is missing

### ISSUE THREAD

**Issue by adamvoss** [nodeca/js-yaml#355]
Input
```js
safeLoad("{a:a}")
```
Output
```json
{ 'a:a': null }
```

I believe the above should Error.  I cannot find anything in the spec saying the colon (`:`) is optional in a mapping.

The spec says (emphasis mine),
> "Note that the value may be completely empty **since its existence is indicated by the “:”**.

Then again [Flow Mapping Separate Values](http://www.yaml.org/spec/1.2/spec.html#id2791704) shows this omission when there are multiple are multiple entries in the map...

**Comment by puzrin** [comment]
What's wrong with it? `:` is allowed in key name. If you miss space after `:`, it's considered as part of key.

**Comment by adamvoss** [comment]
Sorry, I see how that was confusing and I should have simplified my example.

I had expected to need:
```js
safeLoad("{key:}")
```
rather than
```js
safeLoad("{key}")
```
to get the output:
```json
{ "key": null }
```

That is how I was reading [www.yaml.org/spec/1.2/spec.html#id2791704](http://www.yaml.org/spec/1.2/spec.html#id2791260), which I quoted above. Though, I may have missed the path through the grammar that lets the value be empty without the colon.

**Comment by puzrin** [comment]
I still don't understand you. Please use http://nodeca.github.io/js-yaml/ to create all samples with comments (good and bad) and provide a permalink.

http://nodeca.github.io/js-yaml/#yaml=LSB7IGtleSB9Ci0geyBrZXk6IH0=

**Comment by adamvoss** [comment]
http://nodeca.github.io/js-yaml/#yaml=LSB7IH0gIyBWYWxpZAotIHsga2V5IH0gIyBFcnJvciBleHBlY3RlZCBoZXJlLCB3aHkgaXMgbnVsbCBpbmZlcmVkIGFzIGEgdmFsdWU/Ci0geyBrZXk6IH0gIyBUaGlzIGJlaGF2ZXMgYXMgZXhwZWN0ZWQKLSB7IDoga2V5IH0gIyBUaGlzIGJlaGF2ZXMgYXMgZXhwZWN0ZWQ=

**Comment by puzrin** [comment]
Thanks, understand now.

@dervus could you comment?

**Comment by puzrin** [comment]
@adamvoss BTW, http://yaml-online-parser.appspot.com/ - this site is built with pyyaml (with libyaml behind), and libyaml is reference implementation. It returns the same result for `{ key }` -> `{ key: null }`

**Comment by adamvoss** [comment]
Thanks for the resource!  I can believe I just failed at reading the grammar, so closing.  The sentence I was looking at may add confusion, but I also know that it is associated with the example so not normative, plus logically it doesn't preclude not having the colon (though natural speech might interpret it that way).

**Comment by adamvoss** [comment]
For future readers, `libyaml` may have been the reference implementation for YAML 1.1, but according to [yaml.org](http://yaml.org/) it appears the reference implementation for YAML 1.2 is a Haskell implementation, [YamlReference](http://hackage.haskell.org/cgi-bin/hackage-scripts/package/YamlReference).  Interacting with the reference implementation in your browser can be done at http://ben-kiki.org/ypaste/
