### ISSUE TITLE
How to dump empty key value to yaml?

### ISSUE THREAD

**Issue by whitecolor** [nodeca/js-yaml#356]
Need to get from js:
```yaml
volumes:
  data-volume:
```
not
```yaml
volumes:
  data-volume: null
```
not
```yaml
volumes:
  data-volume: ''
```
?

**Comment by puzrin** [comment]
empty value == null in yaml.

No way to define such dumping style. Other styles can be tweaked via options https://github.com/nodeca/js-yaml#safedump-object---options-

**Comment by whitecolor** [comment]
Ok, `null` works for me, thanks) Why not allow this with `undefined` by default?

**Comment by puzrin** [comment]
There are no such thing as `undefined` in yaml. This package implements spec, not just generating pretty texts :)

**Comment by whitecolor** [comment]
@puzrin isn't there a way just to ignore `undefined` fields while dumping?

**Comment by puzrin** [comment]
Right now - no. Dumper expects you to provide correct (dumpable) source.

There is reasonable suggestion https://github.com/nodeca/js-yaml/issues/339, but it's not implemented.

**Comment by whitecolor** [comment]
Ok, currently I worked it around by using `JSON.parse(JSON.stringify(obj))` which removes `undefined`.

**Comment by elitan** [comment]
How did you get your docker-compose.yaml file to work with `: null` @whitecolor ?

**Comment by Rachit-gaur** [comment]
> Ok, `null` works for me, thanks) Why not allow this with `undefined` by default?

Hi,
So, How did you fix it? When i use null i get output like
key1: null

**Comment by patarapolw** [comment]
> Ok, currently I worked it around by using `JSON.parse(JSON.stringify(obj))` which removes `undefined`.

It is safer to remove `undefined` using https://stackoverflow.com/questions/286141/remove-blank-attributes-from-an-object-in-javascript/57625661#57625661

```javascript
matter.stringify(
          content,
          Object.entries(
            programmaticallyGeneratedData,
          ).reduce((a, [k, v]) => (v === undefined ? a : { ...a, [k]: v }), {}),
        )
```

However, if you need to remove deep undefined, you might need https://github.com/patarapolw/deepfind#patarapolwdeepfind then `delete obj[k]`.
