### ISSUE TITLE
How to force | block scalar?

### ISSUE THREAD

**Issue by codyspring** [nodeca/js-yaml#357]
Hey all. I'm parsing a string value and it's being exported like:
```YAML
key: >-
  Here is a pretty cool example string
  that extends multiple lines?
```

Is it possible to force it to either A: store the string as:
```YAML
key: Here is a pretty cool example string that extends multiple lines?
```

Or specify which type of block scalar it's using? Such as:
```YAML
key: >
  Here is a pretty cool example string
  that extends multiple lines?
```

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#safedump-object---options- increase `lineWidth`

**Comment by codyspring** [comment]
Oh, god that's simple; sorry I missed it. Thanks for the pointer! :D
