### ISSUE TITLE
YAML export is slow compared to JSON

### ISSUE THREAD

**Issue by Talljoe** [nodeca/js-yaml#362]
With a [large data set](https://github.com/Talljoe/steno-dictionary/blob/master/dictionaries/main-meta.json) (17MB JSON, 69k objects in an array) js-yaml `safeDump` is considerably slower than `JSON.stringify`.

```
> time lsc main-to-meta.ls # YAML w/ node v6.1.1
lsc main-to-meta.ls  59.78s user 0.27s system 100% cpu 59.980 total
> time lsc main-to-meta.ls # YAML w/ node v8.2.1
lsc main-to-meta.ls  53.34s user 0.34s system 100% cpu 53.454 total
> time lsc main-to-meta.ls # JSON w/ node v6.1.1
lsc main-to-meta.ls  1.91s user 0.28s system 101% cpu 2.155 total
> time lsc main-to-meta.ls # JSON w/ node v8.2.1
lsc main-to-meta.ls  1.70s user 0.41s system 104% cpu 2.025 total
```

Code is equivalent:
```
fs.write-file-sync file, JSON.stringify(data, null, 2)

fs.write-file-sync file, js-yaml.safeDump(data)
```
I think it's due to O(n<sup>2</sup>) string allocations.

**Comment by puzrin** [comment]
It should be slower, because it makes a lot of check to select proper quoting, folding etc. See sources.  If you need high speed for big files, you could write your own simplified dumper without all those features.

**Comment by Talljoe** [comment]
Thank you for your help tracking down the slowness. You're right, the problem was in the duplicate-checking code:
```
[JavaScript]:
   ticks  total  nonlib   name
  63160   93.2%   93.8%  LazyCompile: *inspectNode /home/talljoe/dev/steno-dictionary/tools/node_modules/js-yaml/lib/js-yaml/dumper.js:763:21
    419    0.6%    0.6%  Function: ~writeNode /home/talljoe/dev/steno-dictionary/tools/node_modules/js-yaml/lib/js-yaml/dumper.js:675:19
    238    0.4%    0.4%  LazyCompile: *detectType /home/talljoe/dev/steno-dictionary/tools/node_modules/js-yaml/lib/js-yaml/dumper.js:637:20
    176    0.3%    0.3%  LazyCompile: *chooseScalarStyle /home/talljoe/dev/steno-dictionary/tools/node_modules/js-yaml/lib/js-yaml/dumper.js:250:27
    134    0.2%    0.2%  LazyCompile: *isBoolean /home/talljoe/dev/steno-dictionary/tools/node_modules/js-yaml/lib/js-yaml/type/bool.js:20:19
    117    0.2%    0.2%  LazyCompile: *writeBlockMapping /home/talljoe/dev/steno-dictionary/tools/node_modules/js-yaml/lib/js-yaml/dumper.js:563:27
    117    0.2%    0.2%  LazyCompile: *<anonymous> /home/talljoe/dev/steno-dictionary/tools/node_modules/prelude-ls/lib/List.js:308:35
```
I set `noRefs: true` since I don't have duplicates and the speed increased significantly:
```
lsc main-to-meta.ls  3.65s user 0.16s system 106% cpu 3.592 total
```

It looks like the duplicate-checking algorithm is the bottleneck. I have an [experimental patch](https://github.com/Talljoe/js-yaml/tree/optimize-dupe-checking) which increases the algorithm significantly:
```
lsc main-to-meta.ls  5.94s user 0.88s system 102% cpu 6.658 total
```
But it currently doesn't pass all tests and likely doesn't pass your muster. Feel free to adapt it to your code base.

**Comment by puzrin** [comment]
Do i understand right, that idea is to replace `Array` with `Set` for dupe checks?

**Comment by Talljoe** [comment]
That's one solution. The current implementation does O(n<sup>2</sup>) or worse lookups into the `objects` and `duplicateObjects` array. By switching to a set the lookup is like a hashtable (O(log<sub>n</sub>) or better). A couple of downsides is that the set is implemented by JSON-ifying the object in order to create a string key.

**Comment by puzrin** [comment]
Unsafe hacks like `JSON.stringify()` for keys can not be used here, because this package pretend to "follow standard". But if anyone decides to suggest more correct implementation with legacy fallback, that will be accepted.

From the other hand... nobody cares... because dumping huge objects is very rare case for yaml, and `noRefs` option is enougth in real world.

**Comment by puzrin** [comment]
May be, it worth add comment to README, that `noRefs` can improve speed significantly for big objects.

**Comment by Talljoe** [comment]
Cool, no worries. I'm unblocked by using `noRefs` and understand that JS doesn't give a lot of good solutions for things like this. Cheers.
