### ISSUE TITLE
Keep metadata for every entity

### ISSUE THREAD

**Issue by KOLANICH** [nodeca/js-yaml#366]
Yaml is meant to be a config file. So it can contain incorrect config. So we would like to know the lines where a config is incorrect. Yaml parser cannot decide that. So we need not just parsed representation, but also AST with all metadata, such as lines numbers and char positions. So if we know yaml path (we know it) it would be easy to find the line where incorrect data sits and highlight it in the text editor.

**Comment by puzrin** [comment]
That's out of this project scope, sorry.

**Comment by kachkaev** [comment]
@KOLANICH have you found any yaml AST extractors by a chance? Also looking for this.

**Comment by KOLANICH** [comment]
@kachkaev, no.
