### ISSUE TITLE
Support encoding emojis without encoding as surrogate pairs

### ISSUE THREAD

**Issue by tech4him1** [nodeca/js-yaml#368]
Currently, if an emoji is in a YAML string, and run through `safeDump`, it will be converted into escaped surrogate pairs (i.e. `thiskey: "😀"` is dumped as `thiskey: "\uD83D\uDE00"`). This is caused by [lib/js-yaml/dumper.js#L468](https://github.com/nodeca/js-yaml/blob/bd32506/lib/js-yaml/dumper.js#L468), as using JS `charCodeAt` returns surrogate pairs by default (see https://mathiasbynens.be/notes/javascript-unicode). Would you be willing to at least make this configurable, so that we could choose whether to convert into surrogate pairs or write the emojis directly? If you want a PR, I can help with that as well, just wanted to see what your thoughts were.

**Comment by puzrin** [comment]
What yaml spec says about astrals encoding?

**Comment by puzrin** [comment]
http://www.yaml.org/spec/1.2/spec.html#Characters seems spec does not allow what you requested

**Comment by tech4him1** [comment]
@puzrin I'm sorry, I don't understand which part of the spec that you linked means that astrals *must* be encoded as surrogate pairs. Could you explain to me why YAML astrals *have* to be surrogate pairs.

**Comment by puzrin** [comment]
There is list of allowed codes. Astrals are not there.

> To ensure readability, YAML streams use only the printable subset of the Unicode character set. The allowed character range explicitly excludes the C0 control block #x0-#x1F (except for TAB #x9, LF #xA, and CR #xD which are allowed), DEL #x7F, the C1 control block #x80-#x9F (except for NEL #x85 which is allowed), the surrogate block #xD800-#xDFFF, #xFFFE, and #xFFFF.

**Comment by tech4him1** [comment]
The section that you quoted there say that that is the *excluded* range; " The allowed character range explicitly excludes". I thought that means that those are the non-printable characters, and the rest could be printed?

**Comment by puzrin** [comment]
That's a reason why surrogates are hex-encoded. And there are no guarantee that astrals will be printable, because that depends on unicode support in OS.

I short - i can understand your request and have no principal objections is it follows spec. But someone should contact spec authors to clarify details.

**Comment by tech4him1** [comment]
@puzrin Thank you. Would you be willing to have an option whether to encode as a 32-bit escape instead of surrogate pairs ("\U0001F600" instead of "\uD83D\uDE00"), or do you think that would have the same problem?

**Comment by puzrin** [comment]
I don't care at all :). If someone will give a ready recipe how to do it without breaking spec, it should not be difficult to implement. But i can't participate in this investigation - have to do another projects.

**Comment by tech4him1** [comment]
@puzrin Thank you for your time,  really appreciate it! I will get a PR ready and you can look at it then.

**Comment by puzrin** [comment]
UPD: from 4.0 pairs are not encoded anymore (emojies pass as is).
