### ISSUE TITLE
js-yaml adds single quotes around aliases

### ISSUE THREAD

**Issue by jithin1987** [nodeca/js-yaml#372]
Pasting a snippet from yaml which `js-yaml` generates.

```
         steps:
      -    - '&prepublish echo prepublish'
      -    - '&new_step echo new_step'
      +    - &prepublish echo prepublish
      +    - &new_step echo new_step
```

First two lines are `js-yaml ` output and next two are expected output, having quotes in the array value does not make it an alias, but just a string. How can I make `js-yaml` output correct data for `alias` ?

**Comment by puzrin** [comment]
I'm not sure dumper supports aliaces at all. Could you provide more detailed example (code)

**Comment by jithin1987** [comment]
@puzrin This is what I am trying to do
```
newsupply-lm:js-yaml-dump jithine$ cat index.js
'use strict';

const JSYAML = require('js-yaml');

const js = {
  stepTmpl: '&new_step echo new_step',
  step2: '*new_step'
};


console.log(JSYAML.dump(js));

newsupply-lm:js-yaml-dump jithine$ node index.js
```

Actual Output

```
stepTmpl: '&new_step echo new_step'
step2: '*new_step'
```

Expected Output
```
stepTmpl: &new_step echo new_step
step2: *new_step
```

**Comment by puzrin** [comment]
Your expectations are not right. Dumper works exactly as expected - write properly escaped strings.

**Comment by jithin1987** [comment]
@puzrin My expectation is for `js-yaml` to understand that `stepTempl` defines an `anchor` and `step2` `aliases` it. Is there anyway for `js-yaml` to dump "Expected output" I've given above ?

**Comment by puzrin** [comment]
No. There are no ways to define aliases & anchors in dumper. Only [noRefs](https://github.com/nodeca/js-yaml#safedump-object---options-) option.
