### ISSUE TITLE
option for dashes at top of file

### ISSUE THREAD

**Issue by Celadora** [nodeca/js-yaml#376]
Our convention for YAML files is to begin with three dashes, and then to begin at a single indentation level.
```
---
  a: a
  b: b

```

When we dump an object literal like {a: 'a', b: 'b'}, the resulting file does not have the three dashes we expect. Is there an option to enable that type of behavior? Our workaround is to simply add that line, and indent every subsequent line, after dumping the object as YAML.

Thank you for your advice!

**Comment by fincrypchain001** [comment]
Hello its a same code

**Comment by aschrab** [comment]
The default configuration of [yamllint](https://github.com/adrienverge/yamllint) will warn if the three dashes aren't present at the start. That does *not* expect that all content will be indented.

**Comment by rlidwka** [comment]
> Is there an option to enable that type of behavior?

No such option is available as far as I remember. 

I'd suggest to add it manually, since the task is rather trivial:

```js
let obj = { a: 'a', b: 'b' };
console.log(yaml.safeDump(obj).replace(/^(?!$)/mg, '  ').replace(/^/, '---\n'));
```

**Comment by nuest** [comment]
I don't know if this changed in the meantime, but when I check the rules of yamllint here https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start the default seems to be different:

<img width="747" height="783" alt="Image" src="https://github.com/user-attachments/assets/ef9612e6-0281-4093-8621-ca287601f959" />
