### ISSUE TITLE
Support 'require' in JS-Functions

### ISSUE THREAD

**Issue by megastef** [nodeca/js-yaml#379]
Hi, is there a way to support Node 'require' in functions defined in JS-YAML? 
We use JS-YAML to define log parser rules and allow data transformation via JS functions, in some situations it would be helpful to load external modules like `moment` for date parsing or any other npm module. 

See e.g. https://github.com/sematext/logagent-js/issues/100

**Comment by puzrin** [comment]
Hm... you can try provide your own schema via options, with customized function type.

https://github.com/nodeca/js-yaml/blob/master/examples/custom_types.js

**Comment by puzrin** [comment]
Close as rejeced. No plans turn yaml into programming language. If you wish - provide your own schema as been mentioned.
