### ISSUE TITLE
Improper handling of character range `#x10000-#x10FFFF` (UTF16)

### ISSUE THREAD

**Issue by tedivm** [nodeca/js-yaml#380]
According to the [YAML spec](http://yaml.org/spec/1.2/spec.html#Characters) the characters `#x10000-#x10FFFF` do not need to be escaped, yet this library is doing so.

As a second bug, the characters in this range are being encoded in a way that is not compatible with javascript. For example, that character `🎁` should be represented to javascript as `\uD83C\uDF81` or `\u{1F381}` but is instead being sent as `\U0001F381`.

**Comment by puzrin** [comment]
Are you speaking about loader or dumper? Loader should support both forms. Dumper has no options to generate JS. Last change was in https://github.com/nodeca/js-yaml/pull/369 and i see no problems with it.

Please, provide mode details, what is wrong (because everthing seems to be ok)

**Comment by puzrin** [comment]
close - no feedback.
