### ISSUE TITLE
Math equation in Yaml

### ISSUE THREAD

**Issue by nomi-ramzan** [nodeca/js-yaml#382]
Hi i wanted to know is there any ways to give a math simple equation in yaml
Here is my code example 

```
---
defaults:
 - $var1 1

use: *var1 + 1
# or
use: !!js/yield *var1

```
Or any batter way to do that ?
Thank you

**Comment by puzrin** [comment]
To such ways. IMHO that's a common mistake try use yaml as programming language.

**Comment by nomi-ramzan** [comment]
Hey that is why I created issue here, I solved my problem with custom type

```
var YieldYamlType = new yaml.Type('!yield', {
  kind: 'mapping',
  construct: function (data) {
    try {
      const { val, inc = 1} = data;
      if (val instanceof Serial) {
        return val.next(inc);
      }
      return Number(val) + inc
    }catch(exp){ return data }
  },
});
``` 
And you can use it like this
value: !yield { val: 5, inc: 10 } // ==> 5 +10

Thank you

**Comment by puzrin** [comment]
You can add some magic via custom types, but result will be more complicated than separate post-processing, and less portable. Of cause i can not prohibit you to do so :)

**Comment by puzrin** [comment]
If you love extra flexibility in configs, try coffe-script instead of yaml. May be you find it more comfortable for your needs
