### ISSUE TITLE
int.js cannot resolve numbers like '0412345678'

### ISSUE THREAD

**Issue by mariamare** [nodeca/js-yaml#386]
The thing is that the function resolveYamlInteger infers that values starting with 0 and not followed by 'x' or 'b' are octal number system, then values like '0412345678' are not valid because it contains non octal numbers.

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=MDQxMjM0NTY3OA==

It's casted to string, not to number => works as expected. Add more details if i missunderstand something.

**Comment by mariamare** [comment]
Here is a test:

```
'use strict';

var assert = require('assert');

var resolveYamlInteger = require('../../lib/js-yaml/type/int').resolve;

test('resolveYamlInteger', function () {
  assert(resolveYamlInteger('0xFF'));
  assert(resolveYamlInteger('0b11'));
  assert(resolveYamlInteger('037'));
  assert(resolveYamlInteger('038')); //This fails
});

```

**Comment by puzrin** [comment]
I'm not sure that such partial code use is expected. Please, use online demo, as i did. At first glance, it process invalid octals according to spec.

**Comment by puzrin** [comment]
`assert(resolveYamlInteger('038')); //This fails`

i see no problem with this, since `038` is not valid octal and not valid decimal, fallback to string happens.

**Comment by mariamare** [comment]
ECMAScript 6 specify that Octal literals have the prefix 0o or 0O.
Also, `parseInt('000435458', 10) => 435458`

I am not trying to convince you, but to understand what should be the expected result.

**Comment by puzrin** [comment]
AFAIK, expected result is fallback to more generic type. More generic type is string. As i showed on demo, result is string - as expected.

Anyway, support is very limited due lack of time, and i can not discuss yaml in general here. I can only help, if real bug found, with detailed report (what is wrong, what is expected, with reference to spec & other implementations as proof).
