### ISSUE TITLE
Support for ES6 in `js/function` YAML type

### ISSUE THREAD

**Issue by julien-c** [nodeca/js-yaml#389]
```yaml
function: !!js/function >
  () => 'Wow! JS-YAML Rocks!';
```

**Comment by puzrin** [comment]
Looks reasonable. PR will be accepted.

**Comment by kivlor** [comment]
I've had a crack at adding support for ES6 arrow functions, see - https://github.com/nodeca/js-yaml/pull/393

For the moment, dumped arrow functions are just 'standard' functions. JS doesn't seem to have an `ArrowFunction` class so I couldn't see a way to dynamically create them.

I could use `eval`? (joking, not joking...)

**Comment by aengl** [comment]
I tried to support arrow functions without block statements, feedback welcome:

https://github.com/nodeca/js-yaml/pull/421
