### ISSUE TITLE
dump fails to quote strings with leading zeros if any chars are non-octal

### ISSUE THREAD

**Issue by tavisrudd** [nodeca/js-yaml#394]
```
jsyaml = require('js-yaml');
console.log(jsyaml.dump("007"));
console.log(jsyaml.dump("008"));
```
Should output 
```
'007'

'008'
```
but it outputs 
```
'007'

008
```

I'm running into this with AWS account ids that start with two leading 0s and this is causing issues with CloudFormation templates as CloudFormation then mangles the numbers further.

This case should be handled in the `testAmbiguousType` function passed to `chooseScalarStyle` in `dumper.js`.

**Comment by tavisrudd** [comment]
It looks like the fix needs to go here https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/dumper.js#L343

**Comment by puzrin** [comment]
Everything works as expected. Quotes are not used when not needed.

**Comment by tavisrudd** [comment]
They are needed in this case. If the number isn't quoted downstream tooling fails as it is ambigous. I'm going to need to hack around this and am happy to provide a PR.

**Comment by puzrin** [comment]
Could you provide a proof with refer to spec or well known parser implementations? 008 is NOT a valid octal number.

**Comment by tavisrudd** [comment]
You're missing the point, I'm not suggesting 008 is a valid octal number. Rather, CloudFormation and probably other tools are parsing it as number when not quoted. If js-yaml were to quote such strings, this bad interaction could be avoided.

**Comment by puzrin** [comment]
> Rather, CloudFormation and probably other tools are parsing it as number when not quoted.

IMHO it's much better idea to report broken yaml parser in CloudFormation tool, instead of suggest adding kludge to working and correct implementation.

**Comment by tavisrudd** [comment]
I'll be reporting it to CloudFormation as well. However, I'd still consider it a valid enhancement to your library. Which strings to consider ambiguous and needed quoting, what flow style to use, when to line wrap, etc. are stylistic choices js-yaml is making rather than strict adherence to the YAML spec.

**Comment by puzrin** [comment]
I respect your opinion, but that's subjective and not enough for changes.

**Comment by puzrin** [comment]
If you need quick and dirty workaround - use JSON.stringify(), it's compatible with yaml.

**Comment by tavisrudd** [comment]
Would you be open to a dump option to always force quoting of single line strings? That feels in line with the types of control the existing options provide?

**Comment by puzrin** [comment]
> Would you be open to a dump option to always force quoting of single line strings?

I'm ok about any option if there are strong arguments why this option is nice & useful for all. But options "just for fun" are rejected to keep api simple.

**Comment by wyardley** [comment]
We have a similar issue... we have some templates that do some replacement and then write out a yaml file for a Kubernetes config that has a value mapping to a Git commit hash (we need the value to be a string, and we don't know the value in the original template, though we do quote it). When we pass in the value as a string, certain values end up getting quoted and others not, as described above.

```javascript
jsyaml = require('js-yaml');
const numberString = '037887453';
process.stdout.write(jsyaml.dump('0123456'));
process.stdout.write(jsyaml.dump('077777'));
process.stdout.write(jsyaml.dump('037887'));
process.stdout.write(jsyaml.dump('037887453'));
process.stdout.write(jsyaml.dump(numberString));
console.log(typeof(numberString));
```

```
'0123456'
'077777'
037887
037887453
037887453
string
```

If I'm understanding how you're suggesting to use `jsonStringify()`, that ends up getting me
(e.g.) `'"037887"'`, which doesn't work in certain cases, especially when we're also building strings with the same replaced value in other places.
