### ISSUE TITLE
Not passing an iterator to safeLoadAll and/or loadAll throws an error

### ISSUE THREAD

**Issue by Valandur** [nodeca/js-yaml#395]
Hello :)

Not passing an iterator to the `safeLoadAll` or `loadAll` functions used to return the loaded documents as an array.
Since one of the newer versions (I'm not quite sure starting at which version, but tested on the newest one) not passing a second argument to those functions throws a `TypeError: iterator is not a function`, even though the documentation still states `Applies iterator to each document if specified, or returns array of documents.`

Did something change in the behavior of those functions, or did I miss something?

**Comment by puzrin** [comment]
Please add a code sample how to reproduce.

**Comment by Valandur** [comment]
I was using js-yaml inside grunt, but after reinstalling the module it seems to work properly. I must have messed up the dependencies on my end somehow. Weird that it didn't show up as a "module not found" error though, and seemed to be partly working.

Consider this issue solved, and I apologize for the inconvenience
