### ISSUE TITLE
require yaml config file in multi nodejs files

### ISSUE THREAD

**Issue by bi-kai** [nodeca/js-yaml#396]
My yaml configure is written with `js-yaml`, and I'm using this config in multi nodejs scripts, will there be any performance problems with this calling?
```
var config = yaml.safeLoad(fs.readFileSync('./config.yml', 'utf8'));
```
will this lead to read `config.yml` multi times?
or I'm free to use this multi times no matter in one file and multi files?

Looking forward to your reply.

**Comment by puzrin** [comment]
No ideas. Parser do parse on every call. You can add cache in outer code, but that's out of this tracker topic.

**Comment by bi-kai** [comment]
@puzrin Ok, I see. But it will be called about ten times in my program in this way.
