### ISSUE TITLE
Add function to load file directly for convenience

### ISSUE THREAD

**Issue by KSXGitHub** [nodeca/js-yaml#402]
Every time I want to load a yaml file, I have to either:

1. Write this ugly and complicated script:

```javascript
import * as yaml from 'js-yaml'
import * as fs from 'fs'
const object = yaml.safeLoad(fs.readFileSync('file.yaml', 'utf8'))
```

2. Use an intermediate [module](https://github.com/linusu/load-yaml-file) which unnecessarily pollutes `package.json`:

```javascript
import * as yaml from 'load-yaml-file'
const object = yaml.sync('file.yaml')
```
So I wish js-yaml just provide these little functions for sake of developers' convenience and laziness:

```javascript
import * as yaml from 'js-yaml'
yaml.loadFile('file.yaml') // -> Promise
yaml.safeLoadFile('file.yaml') // -> Promise
yaml.loadFileSync('file.yaml') // -> Parsed result
yaml.safeLoadFileSync('file.yaml') // -> Parsed result
```

**Comment by puzrin** [comment]
Close - rejected. Write your own wrapper instead.
