### ISSUE TITLE
the string of 'True' and 'False' after safeDump has  quotation marks

### ISSUE THREAD

**Issue by wescai** [nodeca/js-yaml#409]
the object is
{ 
a : 'a',
b: 'True',
c: 'False'
}

after safeDump , the yaml file is like this:
![image](https://user-images.githubusercontent.com/20497367/37633242-8a3ad924-2c2c-11e8-9ea2-6ab37e959028.png)

What is special of 'True' and 'False'？

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=cXVvdGVkOiAiVHJ1ZSIKbm9xdW90ZTogVHJ1ZQ==

**Comment by wescai** [comment]
I mean why ‘a’ has convert to a（no quotation marks），but ‘True’ convert to ‘True’（has quotation marks）

**Comment by puzrin** [comment]
Because quotes are skipped when possible. And not skipped when impossible.
