### ISSUE TITLE
condenseFlow in combination with flowLevel 0 is broken

### ISSUE THREAD

**Issue by arabold** [nodeca/js-yaml#412]
Simple sample code:

```
var jsYaml = require("js-yaml")
console.log(jsYaml.safeDump({ a: "a", b: "b", c: "c" }, { flowLevel: 0, condenseFlow: true }))
```

This results in a broken string like this:
```
{"a":a", b":b", c":c}\n
```

Without condense flow the result works as expected:
```
{a: a, b: b, c: c}\n
```

**Comment by puzrin** [comment]
Those params should not be combined together. If one wish to use both - that's not our client :)
