### ISSUE TITLE
Multiple << are not resolving correctly

### ISSUE THREAD

**Issue by radmen** [nodeca/js-yaml#413]
Test file:

```js
const yaml = require('js-yaml');

const doc = `
foo: &VARS_FOO
  IMAGE: A

bar: &VARS_BAR
  IMAGE: B

test:
  <<: *VARS_FOO
  <<: *VARS_BAR
`

var r = yaml.safeLoad(doc);
console.log(r);
```

Output:

```
{ foo: { IMAGE: 'A' },
  bar: { IMAGE: 'B' },
  test: { IMAGE: 'A' } }
```

Expected result:

```
{ foo: { IMAGE: 'A' },
  bar: { IMAGE: 'B' },
  test: { IMAGE: 'B' } }
```

Node version: v9.7.1
js-yaml version: 3.11.0

**Comment by puzrin** [comment]
AFAIK, duplicated props behaviour is not specified and left to devs choice. Do you have a link to spec that says opposite?

**Comment by radmen** [comment]
> AFAIK, duplicated props behaviour is not specified and left to devs choice. Do you have a link to spec that says opposite?

ah, didn't know that. Guess I got tricked by other apps that do support such things.

I've tried to look at the spec and didn't find anything in this case so I guess that my report is not a valid issue. Will close it.

Thanks!
