### ISSUE TITLE
Getting 'Unexpected identifier' when function has await 

### ISSUE THREAD

**Issue by kiran-z** [nodeca/js-yaml#414]
Unable to load the .yml when a function has await keyword.

``` 
function: !!js/function > 
            async function() {
              let b = new Promise(function(resolve, reject) {
                resolve('a');
              })
              await b;
          }
```

`SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at Type.constructJavascriptFunction [as construct] (/Users/admin/node_modules/js-yaml/lib/js-yaml/type/js/function.js:69:10)`

Are AsyncFunctions supported?

**Comment by puzrin** [comment]
1. You have wrong location of last comma. Correct will be [this](http://nodeca.github.io/js-yaml/#yaml=ZnVuY3Rpb246ICEhanMvZnVuY3Rpb24gPiAKICAgICAgICAgICAgYXN5bmMgZnVuY3Rpb24oKSB7CiAgICAgICAgICAgICAgbGV0IGIgPSBuZXcgUHJvbWlzZShmdW5jdGlvbihyZXNvbHZlLCByZWplY3QpIHsKICAgICAgICAgICAgICAgIHJlc29sdmUoJ2EnKTsKICAgICAgICAgICAgICB9KQogICAgICAgICAgICAgIGF3YWl0IGI7CiAgICAgICAgICAgIH0=)
2. Anyway, async/await seems not supported. PR welcome.

**Comment by puzrin** [comment]
Close as rejeced: https://github.com/nodeca/js-yaml/pull/496 after talk in PR - please do that via custom schema. No wish to fill core with js-specific progamming things.
