### ISSUE TITLE
Links to `gulp-yaml`

### ISSUE THREAD

**Issue by ehmicky** [nodeca/js-yaml#415]
Hi there!

I'm a collaborator on [`gulp-yaml`](https://github.com/crissdev/gulp-yaml) which is the main Gulp plugin for `js-yaml`.

I would like contribute a PR with links in `README.md` to tools related to `js-yaml` (including `gulp-yaml`) and wanted your green light before sending this PR.

**Comment by puzrin** [comment]
Sorry, let's keep readme clean

**Comment by ehmicky** [comment]
What about the wiki or another Markdown file?

It's not just for `gulp-yaml` but for the rest of the ecosystem based on `js-yaml`. Most open-source projects feature links to related or dependent projects.

**Comment by puzrin** [comment]
js-yaml has too many dependants to track links manually. It's better to search packages via npm registry.
