### ISSUE TITLE
Mapping key syntax error parsed as if there is no issue

### ISSUE THREAD

**Issue by shockey** [nodeca/js-yaml#418]
`js-yaml` appears to be treating badly-formed mapping keys as if they're well-formed.

This was originally raised as a Swagger-Editor issue (https://github.com/swagger-api/swagger-editor/issues/1740).

### Example

```js
var jsYaml = require("js-yaml")

const str = `
myObj:
  a: "something"
  b: "some other thing" c: "third thing"
`

jsYaml.safeLoad(str)
```

### Expected result

An error, maybe something along the lines of `bad indentation of a mapping entry at line 4, column 24`?

### Actual result

```js
{  
  myObj:{  
    a:'something',
    b:'some other thing',
    c:'third thing'
  }
}
```

**Comment by webron** [comment]
@puzrin - while this is not a critical issue, it does pose challenges to our users from time to time. Any idea if you'll have to look into it? We'd look into submitting a fix ourselves too, just don't want to duplicate the efforts.

**Comment by puzrin** [comment]
I'd prefer to wait for PR. But prior to do something, there should be clear understanding what spec says about such thing. Probably, the most easy way is to check libyaml-based parsers.

**Comment by ingydotnet** [comment]
libyaml reports:
```
      did not find expected key

  was found at document: 1, line: 3, column: 25
  while parsing a block mapping at line: 2, column: 3
```

**Comment by puzrin** [comment]
@ingydotnet thanks!

**Comment by ingydotnet** [comment]
@perlpunk found this test suite case https://github.com/yaml/yaml-test-suite/blob/master/test/JY7Z.tml

**Comment by rlidwka** [comment]
Fixed in https://github.com/nodeca/js-yaml/commit/f0f205bd20534bfd31f12a29d23c1d7cf60fc899 (currently in `dev` branch).
