### ISSUE TITLE
Indented tables are ignored

### ISSUE THREAD

**Issue by wpomier-devfactory** [nodeca/js-yaml#419]
When the table is indented (e.g. inside an unordered list), it's ignored.

## Example
```
* Marked doesn't work with indented tables like this:

  | column1 | column2 |
  |---|---|
  | value1 | value2 |
  | value3 | value4 |
```
It should render to:
* Marked doesn't work with indented tables like this:

  | column1 | column2 |
  |---|---|
  | value1 | value2 |
  | value3 | value4 |

See the same example in the [Marked Demo page](https://marked.js.org/demo/?text=*%20Marked%20doesn%27t%20work%20with%20indented%20tables%20like%20this%3A%0A%0A%20%20%7C%20column1%20%7C%20column2%20%7C%0A%20%20%7C---%7C---%7C%0A%20%20%7C%20value1%20%7C%20value2%20%7C%0A%20%20%7C%20value3%20%7C%20value4%20%7C%0A%0A)

**Comment by puzrin** [comment]
I guess, you posted to wrong repo

**Comment by wpomier** [comment]
I'm so sorry. Wrong browser tab.
