### ISSUE TITLE
Saving to a file

### ISSUE THREAD

**Issue by happilymarrieddad** [nodeca/js-yaml#420]
Hey guys,

I'm not seeing a way to save a yaml file after being edited. Can you please give me an example of how to do this? Thanks!

**Comment by happilymarrieddad** [comment]
fs.writeFileSync('./peer.yaml',yaml.safeDump(doc))

This works.

**Comment by tricoos** [comment]
I was also wondering why there is no `yaml.save` method if there is a `yaml.load` method. I think many people also might want to save the file instead of dumping only so why not add a simple `save` method with that content?
Would make code utilizing this library a lot more readable.
