### ISSUE TITLE
When splitting text across a line in an array: YAMLException: missed comma between flow collection entries

### ISSUE THREAD

**Issue by jrop** [nodeca/js-yaml#422]
First of all, thank you so much for this amazing lib!

In the following scenario, I get the following error:

```js
const s = `key: [ Some text here
and another line here ]`
safeLoad(s)
// throws YAMLException: missed comma between flow collection entries at line 2, column 1
```
Although the [online YAML parser](https://yaml-online-parser.appspot.com/) parses this as:

```json
{
  "key": [
    "Some text here and another line here"
  ]
}
```

**Comment by perlpunk** [comment]
The flow content `[...]` needs to be indented:
```
key: [ Some text here
  and another line here ]
```
This way js-yaml accepts it.

Note that many parsers accept unindented flow content, but the spec says otherwise.
So the behaviour is correct.

**Comment by jrop** [comment]
@perlpunk In that case I am angry at other parsers for being forgiving...as I have no control over my input text (sadly).  It was YAML generated from PyYAML, and has unindented flow content.

**Comment by perlpunk** [comment]
@jrop it was generated by PyYAML? that's surprising.
I get this:
```
foo = { 'x': ["aaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccc ddddddddddddddddddddddddd eeeeeeeeeeeeeeeee"] }
print(yaml.dump(foo))
OUTPUT:
x: [aaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccc ddddddddddddddddddddddddd
    eeeeeeeeeeeeeeeee]

```

**Comment by jrop** [comment]
@perlpunk To be fair, I am not sure where the source of generation is: I should clarify.  I am trying to parse YAML that exists in some Python source-code inside a comment.  I guess I had assumed it had been generated, but your most recent comment makes me think that perhaps it was hand-written and just has invalid syntax.

**Comment by puzrin** [comment]
Is this still actual?

**Comment by puzrin** [comment]
Close as outdated
