### ISSUE TITLE
Set output file via API versus position in cmd

### ISSUE THREAD

**Issue by tim-digitized** [nodeca/js-yaml#423]
Hi - Not an issue, but maybe a feature request... :)

I wanted to check if there's a way to set the output file via the API instead in the positional command as I'm trying to use fs.watch to detect changes in my yaml files and want to use your script to re-build my master file. 

Is this supported with your project?

**Comment by puzrin** [comment]
No, this project does not know anything about files at all. It gets string on input, and return string on output. I think it worth to solve file-related issues in external wrapper, not here.
