### ISSUE TITLE
dump adds >- at long lines 

### ISSUE THREAD

**Issue by lakshaygaur** [nodeca/js-yaml#424]
In my yaml file if theres long line of characters , dump method starts the line value with >- 
How do I use regexp to change the >- to just \n 

Original Yaml file : 
```
tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
```

What dump method gives : 
```
tlsCACerts:
      path: >-
        artifacts/channel/crypto-config/peerOrganizations/org3.example.com/ca/ca.org3.example.com-cert.pem
```

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#safedump-object---options-

Try to increase `lineWidth`

solved?
