### ISSUE TITLE
determining order of insertion

### ISSUE THREAD

**Issue by GeekyDeaks** [nodeca/js-yaml#426]
This is somewhat related to #211 

I found there is an undocumented option called 'listener' which seems to be called during the parsing of the YAML.  I was hoping to be able to do something during the load in which I could reliably maintain the order of the root elements (i.e. those at lineIndent === 0) e.g.

    const order = []
    function listener(op, state) {
        if(op === 'open' && state.lineIndent === 0 && state.kind === 'scalar')
             order.push({ key: state.result, line: state.line })
    }
    yaml.load(text, { listener })

This seems to work, but I wanted to check my understanding was correct and I can always expect that the listener() function is called in order of parsing.

**Comment by puzrin** [comment]
Seems not actual (outdated)
