### ISSUE TITLE
Generating a source map

### ISSUE THREAD

**Issue by marjan-georgiev** [nodeca/js-yaml#428]
Is there a way to generate a source map when parsing YAML strings? Similar to what https://github.com/epoberezkin/json-source-map does?

I have a YAML editor, which is converted to JSON using this library, which is then validated against a JSON schema using ajv, so I would like to track back the validation errors to a line and column number in the original YAML string, so I can highlight it in the editor.

**Comment by puzrin** [comment]
No way. This parser is not suited for such thing.

**Comment by 1e1f** [comment]
@marjan-georgiev there is a listener property on the loader options that provides meta-data from the parser as it goes -- but you have to manually build up a sourcemap using that. I'm working on using that for a specific use case I have, but presently it's a bit of a hack and doesn't solve the general case. If I get a solid middleware that does that I'll share it and see if js-yaml wants to include it here. I could see both sides as to whether it's in scope for this project or not.

**Comment by marbemac** [comment]
We're very interested in this as well - @1e1f did you ever end up getting it to work?

**Comment by gentunian** [comment]
@1e1f not sure what you meant with using the listener. It's not documented but it's on the code as a valid option: https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/loader.js#L140

Anyway, I've tried a quick test: `jsyaml.safeLoad(file, { listener: callback })` but nothing happened. Is that what you meant?
