### ISSUE TITLE
Loading a swagger yaml doc / $ref / paths relative to js module

### ISSUE THREAD

**Issue by aprixon01112017** [nodeca/js-yaml#429]
Hi

I am loading a swagger yaml document with js-yaml that contains references 

$ref: 'definitions/definition.yaml#/ObjectDefinition'

And apparently the paths need to be relative to the js module the root yaml document is loaded from.

It certainly would be nice to have the paths relative to the including yaml document, though.

In case this is relative to js-yaml I would like to request to change that.

**Comment by k-j-kleist** [comment]
Is the use of `$ref` pointers supported by js-yaml? Or even by yaml? I believed it was a Swagger extension:

https://swagger.io/docs/specification/using-ref/

Might also be interesting:

https://github.com/json-schema-org/json-schema-spec/issues/514

The tool "JSON Schema $Ref Parser" seems to do the work, also for yaml files (I haven't tried it myself): https://apidevtools.org/json-schema-ref-parser/

**Comment by puzrin** [comment]
This it not related to this package.
