### ISSUE TITLE
Loading files with unrecognized tags

### ISSUE THREAD

**Issue by drdavella** [nodeca/js-yaml#433]
Often I find that I want to be able to load YAML files even if they contain unrecognized tags. Currently, attempting to do so will result in an error, although I'm not sure why that should be the case. Instead of throwing an error for an unrecognized tag, it seems perfectly reasonable to issue a warning and simply return a raw data structure rather than a constructed instance of some type.

The change log says that warnings were changed to errors for unrecognized tags in version 3.4.0. What was the reasoning for this? Are you willing to revert to the old behavior? A better solution might be to add an optional argument to the `load*` functions that controls whether unrecognized tags cause warnings or errors.

If this seems like a reasonable approach, I am potentially willing to submit a PR with the necessary changes.

**Comment by puzrin** [comment]
I don't remember reasons, but there are no plans to revert.

Probably, because behaviour with those tags was undefined and we have no plans to support forgiving parser.

**Comment by drdavella** [comment]
You won't even consider accepting a PR that will add an option to continue parsing in the presence of unrecognized tags?

**Comment by puzrin** [comment]
I can not promis anything about code in advance. Any feature should be discussed first, to understand how it goes with existing spec and & parser architecture.

As far as i understand, libyaml/pyyaml have different solution for such situation https://github.com/yaml/pyyaml/issues/86. If you are ready to spend your time for investigations, and can prove that suggested solution is not "quick hack" - then open a new issue with details.

**Comment by bigunyak** [comment]
I'm here just to mention that the requested feature is a very typical use case for someone who simply wants to load a yaml file with some tags to only change a few parameters and dump the data again.
As an example, I hit that problem with `unrecognized tags` when tried to load my AWS CloudFormation template which contains `!Ref` and `!GetAtt` tags to only change a few parameters and dump it again.
Please, consider the original request and maybe reopen the issue.

**Comment by andrewryan1906** [comment]
I'm encountering EXACTLY this; I need to simply modify some data in an existing CloudFormation script and resave it. 

@bigunyak have you found a solution to this? I'm stuck and will likely have to go hunting for another parser.

**Comment by bigunyak** [comment]
@andrewryan1906 no, I used other approaches. First, I used awk to edit original template and it worked fine but then I realised that [CloudFormation Parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) is the cleanest way to solve my task.
