### ISSUE TITLE
digit ends up being .nan

### ISSUE THREAD

**Issue by scheiblr** [nodeca/js-yaml#437]
Hi, 

I'm using this amazing library to read and write yaml files. I just wrote code which gets some user input and writes it to a yaml file. Therefore, I'm using `parseInt` in order to convert the input, which first is a string gets converted to a int. Unfortunately, this ends up being `.nan` in the yaml file. I further tried the conversion with `new Number(input)` and ended with the same result.

Maybe someone can help me out with that?

**Comment by puzrin** [comment]
I can't understand anything and is this related to this package.

**Comment by scheiblr** [comment]
I guess it's not the issue of the lib.
