### ISSUE TITLE
Parsing strangely with simple object

### ISSUE THREAD

**Issue by mnalsup** [nodeca/js-yaml#438]
Strange behavior observed with both the web app and with the nodeJS library.

**Input:**
trigger:
  type: webhook
  uri: https://api.aws.net/webhooks/webhook/test

**expected output:**
{ trigger: 
   { type: 'webhook',
     uri: 'https://api.aws.net/webhooks/webhook/test' } }

**actual output:**
{ trigger: null,
  '  type': 'webhook',
  '  uri': 'https://api.aws.net/webhooks/webhook/test' }

When I retype the spaces it works as expected.

js-yaml web link: http://nodeca.github.io/js-yaml/#yaml=dHJpZ2dlcjoKwqAgdHlwZTogd2ViaG9vawrCoCB1cmk6IGh0dHBzOi8vYXBpLmF3cy5uZXQvd2ViaG9va3Mvd2ViaG9vay90ZXN0

**Comment by puzrin** [comment]
i guess, you used non standard spaces (0x20)

**Comment by perlpunk** [comment]
It seems you used non breaking spaces. It might look weird, but they are allowed as content of plain scalars, so what you see is actually correct and most YAML processors show the same result.

btw, you might want to use ``` (3 backticks) to mark your examples, for readability

**Comment by puzrin** [comment]
Close (not a bug)
