### ISSUE TITLE
Cannot resolve js/function types in browser

### ISSUE THREAD

**Issue by ThomasBrierley** [nodeca/js-yaml#439]
`!!js/function` works fine in NodeJS but not in the browser, is this expected? e.g

NodeJS:
```js
const jsyaml = require('./node_modules/js-yaml/dist/js-yaml.js');

jsyaml.load(`
function: !!js/function >
  function foobar() {
    return 'Wow! JS-YAML Rocks!';
  }
`);
```

Browser:
```html
<!doctype html>
<script src="./node_modules/js-yaml/dist/js-yaml.js"></script>

<script>
jsyaml.load(`
function: !!js/function >
  function foobar() {
    return 'Wow! JS-YAML Rocks!';
  }
`);
</script>
```

This throws the following error in the browser (tested latest FireFox and Chromium):
`cannot resolve a node with !<tag:yaml.org,2002:js/function> explicit tag`

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/js/function.js#L3-L19

Yes, you should include esprima into your code somewhere. It's a bit big to add it by default in browser builds.

**Comment by ThomasBrierley** [comment]
Thanks, that's understandable. Are there any other dependencies left out of the browser build worth knowing about?

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#bundled-yaml-library-for-browsers

**Comment by ThomasBrierley** [comment]
Oh... sorry! I swear I skimmed the readme at least 5 times, think it's because I was looking for bower. I'll leave you alone now :smile:
