### ISSUE TITLE
Incorrect parsing of array key

### ISSUE THREAD

**Issue by vfonic** [nodeca/js-yaml#440]
Hi,

I'm having issues parsing this kind of yaml:

```yaml
[First, Second]:
  allow: true
```

This is parsed to JSON like this:

```json
{
  "First, Second": {
    "allow": true
  }
}
```

Instead of:

```json
{
  "First": {
    "allow": true
  },
  "Second": {
    "allow": true
  }
}
```

Am I doing something wrong?

**Comment by puzrin** [comment]
AFAIK, complex keys are not supported due language restrictions. Only some value transforms exist (for omap, set, etc.)

**Comment by vfonic** [comment]
Thanks @puzrin!

I'm just thinking that it would be "more correct" to transform the keys like I suggested above. Because, if there's a comma in the key, it won't be possible to parse it unambiguously.

For example:

```yaml
['First, key', 'Second key']:
  allow: true
```

This is parsed to JSON like this:

```json
{
  "First, key, Second key": {
    "allow": true
  }
}
```

Instead of:

```json
{
  "First, key": {
    "allow": true
  },
  "Second key": {
    "allow": true
  }
}
```

You can't re-construct the `['First, key', 'Second key']` correctly anymore, if you use the current implementation.

**Comment by puzrin** [comment]
That's not a question to be based on opinions :). You can ask yaml guys about recommended behaviour. This repo is about implementation, not about standard.

**Comment by vfonic** [comment]
Thanks @puzrin!

I think the implementation might be wrong. I'm saying "I think" because my knowledge of YAML standard is limited and am asking for the clarification from people who maintain this library and most probably have better understanding of the standard.

Here's my reasoning:
Please check the "Example 2.11. Mapping between Sequences" on the following page: http://yaml.org/spec/1.2/spec.html

As you can see, the standard allows having arrays for keys.
```yaml
? - Detroit Tigers
  - Chicago cubs
:
  - 2001-07-23
```

This is a YAML file with the key array: `['Detroit Tigers', 'Chicago cubs']` which has value (array) `['2001-07-23']`.

If we were to have a comma in the key array:

```yaml
? - Detroit, Tigers
  - Chicago cubs
:
  - 2001-07-23
```

It should convert it into: `['Detroit, Tigers', 'Chicago cubs']`. However, this package doesn't convert it to this syntax correctly. It converts it into: `'Detroit, Tigers,Chicago cubs'`. There are no quotes between the keys, the whole key is considered to be a key.

This website seems to convert it correctly:
https://www.json2yaml.com/

From YAML:
```yaml
? - Detroit, Tigers
  - Chicago cubs
:
  - 2001-07-23
```

To JSON:
```json
{
  "[\"Detroit, Tigers\", \"Chicago cubs\"]": [
    "2001-07-23"
  ]
}
```

What do you think @puzrin?
I believe this is a faulty behavior.

**Comment by puzrin** [comment]
> What do you think @puzrin?

I think you ask wrong person :). You should ask guys, who write yaml spec, not me. If someone trustable confirm that processing should be changed - no problem. But i can't spend time for participation in such discussions.

**Comment by perlpunk** [comment]
Hi,
the YAML spec doesn't say anything about this case.
Javascript and other languages only support strings as keys, YAML does.
An author of a YAML processor in such a language has to decide what to do with complex keys.

I think it's a good thing if it supports loading the YAML instead of returning an error, but there is no standard on how to convert the complex key.

In any case, information will be lost. If you convert it to a string `["Detroit, Tigers", "Chicago cubs"]`, then you have no information if this was a sequence or this exact string in the original YAML file.

If you actually want to process such YAML in a language that doesn't support complex keys, you would need a processor that supports an option on how to stringify such keys, or that devides its loading process into parsing (event based, for example, like libyaml) and constructing and provides an API, so that you can construct the data yourself.

So the behaviour of js-yaml is not a bug. Providing an option for how to stringify would probably be a nice enhancement.

**Comment by perlpunk** [comment]
@vfonic ruby is a different case, because it supports any kind of object as mapping/hash keys. Javascript does not.

**Comment by vfonic** [comment]
> In any case, information will be lost. If you convert it to a string ["Detroit, Tigers", "Chicago cubs"], then you have no information if this was a sequence or this exact string in the original YAML file.

@perlpunk can you please provide the examples of how this can be interpreted differently?

I guess I might be wrong as my understanding was that this would solve that exact ambiguity issue.
In my understanding, that would always convert back to:
```yaml
["Detroit, Tigers", "Chicago cubs"]: ...
```
or
```yaml
? - Detroit, Tigers
   - Chicago cubs
: ...
```
which is the same, just different format.

**Comment by perlpunk** [comment]
@vfonic 
Let's say this is your original YAML:
```
---
[a, b]: value
```

The resulting data in JSON could be, like you suggested:
```
{
  "[\"a\", \"b\"]": "value"
}
```
So you have a string as a key.
If you convert it back to YAML, it would look like this:
```
---
'["a", "b"]': "value"
```
How can you tell that the string key was an array originally?

**Comment by vfonic** [comment]
@perlpunk you're right. For me, it would still be better if:
```yaml
---
['First, key', 'Second key']: value
```
would convert into:
```json
{
  "[\"First, key\", \"Second key\"]": "value"
}
```
insead of (as it is now) converting into:
```json
{
  "[First, key, Second key]": "value"
}
```

In the first option, if I'd have that "domain logic" of knowing/expecting that the key should be an array, I could get the keys out, while in the current implementation, I lose that possibility.

I understand this might be beyond the scope of this package.

Thanks for all the clarifications @puzrin and @perlpunk!

**Comment by perlpunk** [comment]
@vfonic I agree that `"[\"First, key\", \"Second key\"]` would be better than the current `First, key, Second key`. It could probably be even done without an option. I can't imagine anyone relying on the current behaviour.
Just wanted to point out that there's no way to provide a general solution for converting that back to YAML.
