### ISSUE TITLE
block scalars without indicator are parsed correctly

### ISSUE THREAD

**Issue by danadam** [nodeca/js-yaml#442]
As far as I know block scalars require an indicator if it is folded (`>`) or literal (`|`) block, so this is valid:

    key: >
        foo
        bar

and this should not be:

    key:
        foo
        bar

js-yaml seems to parse the latter as correct: [demo](http://nodeca.github.io/js-yaml/#yaml=dmFsaWRfZmxvd19zY2FsYXI6IGZvbwogICAgYmFyCgp2YWxpZF9ibG9ja19zY2FsYXIxOiB8CiAgICBmb28KICAgIGJhcgoKdmFsaWRfYmxvY2tfc2NhbGFyMjogPgogICAgZm9vCiAgICBiYXIKCnNob3VsZF9iZV9pbnZhbGlkOgogICAgZm9vCiAgICBiYXIK), and the same example in [codebeautify validator](https://codebeautify.org/yaml-validator/cb75e841).

**Comment by puzrin** [comment]
I have no ideas about codebeautify. Other online parsers accept yous example without errors. Please, add reference to official spec, where indicators are said to be mandatory for text scalars, to reopen this issue.

**Comment by perlpunk** [comment]
@danadam  This is valid YAML.
See also:
* Example 2.18 Multi-line Flow Scalars http://yaml.org/spec/1.2/spec.html
* my article on strings in YAML: http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

**Comment by danadam** [comment]
Interesting. So in my case 4 results from the first page of google search results for "yaml online parser" have it wrong.
