### ISSUE TITLE
tags for regex?

### ISSUE THREAD

**Issue by albertlinga** [nodeca/js-yaml#444]
parsing a property with a regex value doesn't seem to work and is treated as a string.

e.g. 
myProperty: /\.com$/

when parsed the value becomes a string instead of an instance of regexp

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/

There is example for regexp. https://github.com/nodeca/js-yaml#supported-yaml-types

**Comment by albertlinga** [comment]
I seem to be getting this error 

YAMLException: unknown tag !<tag:yaml.org,2002:RegExp>

**Comment by albertlinga** [comment]
Disregard, it does support regexp using load instead if safeload. Thank you
