### ISSUE TITLE
safeDump Automatic conversion - followup

### ISSUE THREAD

**Issue by guanw** [nodeca/js-yaml#445]
Posted question regarding the behavior of js-yaml with safeDump, we have a yaml editor which use the following method to generate yaml from js object:
```
self.generateYAML = function (graph) {
                if (graph === undefined) {
                    return '';
                }
                try {
                    return jsyaml.safeDump(graph, {
                        noCompatMode: true // fix auto quoting 'y'.
                    }).trim();
                } catch (e) {
                    var error = 'YAML validation error: ' + e.message;
                    console.log(error);
                    return '';
                }
            };
```

graph is passed with an object that has the following content:

```
'Fn::Base64':

  'Fn::Join':

    - "\n"

    -

      - scriptFile=~/createSchema.sh

      - scriptLog=~/createSchema.log

      - rm -f ${scriptFile}

      - touch ${scriptFile}

      - touch ${scriptLog}

      - echo "sqlplus / as sysdba << EOF" >> ${scriptFile}

      - echo "drop user c##myappuser cascade;" >> ${scriptFile}

      - echo "create user c##myappuser identified by ${schemaPassword};" >> ${scriptFile}

      - echo "grant create session, create table, unlimited tablespace to c##myappuser;" >> ${scriptFile}

      - echo "quit" >> ${scriptFile}

      - echo "EOF" >> ${scriptFile}

      - sh ${scriptFile} >> ${scriptLog}

```

Somehow after safedump, the line break was reformated (though it's still correct) and yaml becomes the following
![image](https://user-images.githubusercontent.com/7311035/45368994-deb4d800-b5b2-11e8-963b-584b0ecfda56.png)

The version we used is 3.10.0. Please let me know if there's anything I can do to disable this automatic transformation. Thanks.

* Update:

I tried the solution @puzrin by setting `lineWidth` to `Infinity` but doesn't work. Also I notice if I replace `"\n"` with `'\n'` there won't be automatic conversion. Please let me know if this is a config issue or actual bug in js-yaml. Thanks.

**Comment by puzrin** [comment]
Please, don't duplicale issues. Add valuable info to old one instead.
