### ISSUE TITLE
Feature request: allow custom "non printable" in literals

### ISSUE THREAD

**Issue by eriklax** [nodeca/js-yaml#446]
Would a PR to have an option to allow eg tabs (\t) in block scalars (STYLE_LITERAL) be accepted? As far as I can find the standard recommends \t to be escaped, but it's not required (would not break the format). I want to easily present data with tabs (tab indented source code) in YAML. I believe an "allowNonPrintableLiteral" (array of chars) option could be a good idea which then could be set to [9].

```
code: |
  if (true)
  <tab>echo "hello";
```

**Comment by puzrin** [comment]
1. I'd like to avoid new options if possible.
2. Any new feature should have some explanation, why it's useful for all.

**Comment by eriklax** [comment]
I found a YAML package which supported tabs in literal block scalars https://www.npmjs.com/package/yaml
