### ISSUE TITLE
Allow (and ignore as opaque) `!include`

### ISSUE THREAD

**Issue by MikeTaylor** [nodeca/js-yaml#450]
I need to parse a RAML file just to the point of seeing the schema mapping:
```
schemas:
  - topSchema: !include schemas/top.json
```
But js-yaml rejects my file because it recognises that `!include` is a tag but does not support it. For my purposes, I'd be perfectly happy for it to appear simply as an opaque value `!include schemas/top.json`.

Could we add support for a new option:
```
﻿﻿  const yamlStruct = yaml.load(yamlText, { ignoreInclude: true });
```
or similar?

If I made a PR that implemented this, would you merge it?

**Comment by puzrin** [comment]
That's out of project scope.

**Comment by MikeTaylor** [comment]
... which is why, for every perfecly simply task like "parse YAML", there are half a dozen competing projects to choose from. Oh well.

**Comment by puzrin** [comment]
I'd say, all problems come when people tend to use yaml as programming language. Just use it as human-readable JSON, and everything become easy.

**Comment by jaulz** [comment]
Here I implemented it as a custom type: https://www.npmjs.com/package/js-yaml-type-include

**Comment by MikeTaylor** [comment]
@jaulz Nice!
