### ISSUE TITLE
why some integer string dump without double quote

### ISSUE THREAD

**Issue by Fndroid** [nodeca/js-yaml#457]
It might not be a bug.

**There is no double quote after integer string ``"0648909140"`` was dump to a file.**

Like this:

![image](https://user-images.githubusercontent.com/16091562/48496004-0dc61f00-e86c-11e8-8cce-fbecf4f9c5d2.png)
![image](https://user-images.githubusercontent.com/16091562/48496170-6ac1d500-e86c-11e8-8fd1-0b5d95fb45ba.png)

**But when I try a larger or a smaller one, double quotes are back**, why?

**Comment by puzrin** [comment]
Integer can not start with zero, so it can be detected as string without quotes.

**Comment by Fndroid** [comment]
> Integer can not start with zero, so it can be detected as string without quotes.

![image](https://user-images.githubusercontent.com/16091562/48524071-c1a1cb80-e8b9-11e8-9d01-ed2615b7aa29.png)

**I tried with ``012345``, but quotes shown up**

**Comment by puzrin** [comment]
Because your second sample means number in OCTAL format. You can find all details in yaml spec.

**Comment by Fndroid** [comment]
It seems that YAML 1.2 allows leading zero integer http://yaml.org/type/int.html

Is that means  string like ``0648909140``(with no quotes) would be loaded as an Integer? 

I tried ``noCompatMode: true``, but still no quotes.

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=bm90X29jdGFsOiAwNjQ4OTA5MTQwCiMgbm8gOCwgbm8gOQpvY3RhbDogMDY0NTYwNzE0MA==

**Comment by Fndroid** [comment]
> http://nodeca.github.io/js-yaml/#yaml=bm90X29jdGFsOiAwNjQ4OTA5MTQwCiMgbm8gOCwgbm8gOQpvY3RhbDogMDY0NTYwNzE0MA==

I know ``js-yaml`` works fine between yaml and javascript object.

But when I use this file in programs written with Go(https://gopkg.in/yaml.v2), it takes that string as a ``float``.

Because YAML 1.2(http://yaml.org/type/int.html) check float like this.
```
/[-+]?(\.[0-9]+|[0-9]+(\.[0-9]*)?)([eE][-+]?[0-9]+)?/  | tag:yaml.org,2002:float (Number)
```

**Comment by puzrin** [comment]
I feel this talk endless without clear goal. It's certainly not good idea to write here about problems with go packages, or discuss yaml spec in abstract.

**Comment by frankmariette** [comment]
@puzrin I am having a similar issue of strings being parsed as integers. Is there a way to have a string of "01" be outputted as a string with quotes? js-yaml also converts "01" to an unquoted `1` which causes error with the API I am calling.

**Comment by puzrin** [comment]
@frankmariette i'm not sure that's possible now. May be worth to report bug to that service.

**Comment by frankmariette** [comment]
@puzrin this is an issue with the library performing type coercion on a JSON object, changing a string into an integer. Why is it not possible to simply have strings retain their type and only treat non-string numerics as numbers?

**Comment by puzrin** [comment]
> js-yaml also converts "01" to an unquoted 1 which causes error with the API I am calling.

That's not true.

```
node -e "console.log(require('js-yaml').safeDump('01'))"
'01'

node -e "console.log(require('js-yaml').safeDump(01))"
1
```

Dumper result is correct. Quotes added when required only. Please, provide executable sample, easy to reproduce, if you think dumper has error (but i'm sure it's not).

**Comment by veloso-raro** [comment]
node -e "console.log(require('js-yaml').safeDump("01"))"
1

**Comment by rlidwka** [comment]
> problem is using double quotes, like this:

@veloso-raro your double quotes in the example above are interpreted by `bash` as `console.log(require('js-yaml').safeDump(` + `01` + `))`. They don't make it into executable javascript, which means 01 is parsed as an integer.
