### ISSUE TITLE
Using HTML in YML yields [Objcet Object]

### ISSUE THREAD

**Issue by itsPR** [nodeca/js-yaml#459]
Using HTML in YML yields [Objcet Object]

YML
```
context:
      fieldLabel: |
                   <strong>
                       Some Bold Text
                   </strong> and now normal continued.
```
It's rendering as 

```
context:
fieldLabel: ",[object Object], and now normal continued.↵"
```
but I want my output should be

`context: { fieldLabel: '<strong>\n    Some Bold Text\n</strong> and now normal continued.\n' },`

**Comment by puzrin** [comment]
[Can not reproduce](http://nodeca.github.io/js-yaml/#yaml=Y29udGV4dDoKICAgICAgZmllbGRMYWJlbDogfAogICAgICAgICAgICAgICAgICAgPHN0cm9uZz4KICAgICAgICAgICAgICAgICAgICAgICBTb21lIEJvbGQgVGV4dAogICAgICAgICAgICAgICAgICAgPC9zdHJvbmc+IGFuZCBub3cgbm9ybWFsIGNvbnRpbnVlZC4K). Everything works as expected.

**Comment by itsPR** [comment]
@puzrin Yes, its works on online of JS-Yaml.

But when I using in my JS code as follows it throws object:

My YML : 

```
context:
      fieldLabel: |
                   <strong>
                       Some Bold Text
                   </strong> and now normal continued.
```

My JS Code : 

```
const tests = YAML.safeLoad(this.props.children,{json:true});
console.log("tests",...tests)
```

Console output :

```
context:
fieldLabel: ",[object Object], and now normal continued.↵"
```

It is coming as [object Object] instead of <strong>\n Some Bold Text\n</strong>

**Comment by puzrin** [comment]
Could you create a minimal executable sample?
