### ISSUE TITLE
What does listener param do on Load? 

### ISSUE THREAD

**Issue by diberry** [nodeca/js-yaml#465]
related to #426 

 I would like to use it but not sure what it does. If #426 is correct, can I add a PR for docs?

**Comment by puzrin** [comment]
To be honest, i have no idea why it was accepted and how consistent is it :). This parser has no right AST/Events layer and i would not recommend use related features. IMO it doesn't worth to promote this in docs.

**Comment by dinofx** [comment]
Would be nice to see this documented so it can end up in the typescript definitions.

**Comment by puzrin** [comment]
> Would be nice to see this documented so it can end up in the typescript definitions.

It's not documented because we don't like to promote it. It works "as is", without any guarantees.
