### ISSUE TITLE
Dumping add quote to string even it is not necessary

### ISSUE THREAD

**Issue by joshuaavalon** [nodeca/js-yaml#470]
As title.

### Test Code

```javascript
const jsYaml = require("js-yaml");
const fs = require("fs");
const yamlStr = jsYaml.dump({ url: "https://github.com/nodeca/js-yaml" });
fs.writeFileSync("foo.yml", yamlStr, { encoding: "utf8" });
```
### Expected Result

```yaml
url: https://github.com/nodeca/js-yaml
```

### Actual Result

```yaml
url: 'https://github.com/nodeca/js-yaml'
```

### Problem 

https://github.com/nodeca/js-yaml/blob/b6d260927b875404eac8b5e610f41d2f8fbe2425/lib/js-yaml/dumper.js#L294

https://github.com/nodeca/js-yaml/blob/b6d260927b875404eac8b5e610f41d2f8fbe2425/lib/js-yaml/dumper.js#L192-L205

All of these characters ( except`0xFEFF` ) are safe inside string. Only colon cannot be followed by space or placed at the end of line.

**Comment by diberry** [comment]
This is the same as #466. Perhaps we can have a new setting to handle the quoting issue?

**Comment by puzrin** [comment]
@joshuaavalon "unquoting" quality is limited only by authors time. If anyone has time to improve it - PR is welcome.

**Comment by diberry** [comment]
@puzrin I'll make a PR this weekend, if no one does it before then.

**Comment by diberry** [comment]
[PR 454 seems related](https://github.com/nodeca/js-yaml/pull/454)

**Comment by diberry** [comment]
@puzrin Are these tests all valid/correct? 

`test.only('should not unnecessaryly apply quotes', function () {

  var expected = 'url: https://github.com/nodeca/js-yaml\n';
  var actual = yaml.dump({ url: 'https://github.com/nodeca/js-yaml' });

  assert.strictEqual(actual, expected);
});
test.only('should not unnecessaryly apply quotes - ', function () {

  var expected = 'url: https://github.com/nodeca/js-yaml\n';

  var obj = {};
  obj['url']='https://github.com/nodeca/js-yaml';

  var actual = yaml.dump(obj);

  assert.strictEqual(actual, expected);
});

test.only('should not unnecessaryly apply quotes - space then /\n at end of value', function () {

  var expected = 'url: \'https://github.com/nodeca/js-yaml \'\n';

  var obj = {};
  obj['url']='https://github.com/nodeca/js-yaml ';

  var actual = yaml.dump(obj);

  assert.strictEqual(actual, expected);
});
test.only('should not unnecessaryly apply quotes - space after colon', function () {

  var expected = 'url: \'https: //github.com/nodeca/js-yaml\'\n';
  var actual = yaml.dump({ url: 'https: //github.com/nodeca/js-yaml' });

  assert.strictEqual(actual, expected);
});
`

**Comment by puzrin** [comment]
Could you format you message and add proper land type for highlight?

**Comment by zeropc** [comment]
Having a same problem here. Since only colon and hash characters are limited in flow scalars, is a PR still welcome by now?

**Comment by Giszmo** [comment]
@zeropc I would appreciate a fix but but not speaking for the project. Crossing fingers :D

**Comment by rlidwka** [comment]
Fixed in https://github.com/nodeca/js-yaml/commit/db3f52985ba6f3076e6fb4318ca0c5c3c578ccba (in **dev** branch currently, to be released later).

**Comment by mgiamberardino** [comment]
I'm experiencing a related issue but not entirely sure is the same one. 

We have some cases where the object is like:
`{ "CC#": "some data" }`

And right now this is being confused with a comment in the library. Is this fix related or should I create a new issue?

**Comment by rlidwka** [comment]
> And right now this is being confused with a comment in the library. Is this fix related or should I create a new issue?

This fix is not related, so it's a new issue.

But I'm not entirely sure what you're talking about. `#` symbol is required to have a space/tab/newline before it to be a comment.

If you just put `CC#`, it's not parsed as a comment:

```js
> require('js-yaml').dump({"CC#": "some data"})
'CC#: some data\n'

> require('js-yaml').load('CC#: some data\n')
{ 'CC#': 'some data' }
```
