### ISSUE TITLE
2019-03-22 20:18:42 +0100 interpreted as a string

### ISSUE THREAD

**Issue by DirtyF** [nodeca/js-yaml#477]
`2019-03-13 20:18:42 +0000` is a date format considered valid in Jekyll, when switching to 11ty, it's not. (see: https://github.com/11ty/eleventy/issues/413#issuecomment-475832065)

`space separated:  2001-12-14 21:59:43.10 +0000` returns  a string on https://nodeca.github.io/js-yaml/

http://www.yamllint.com/ will add a colon after parsing: `2019-03-13 20:18:42 +00:00`

**Comment by puzrin** [comment]
This package is about yml standard, not about jekyll.  If you think js-yaml does not conform spec, please give URL to spec details. Also, reference implementation is pyyaml, if you need to compare.

**Comment by josephholsten** [comment]
Just found this and I've got to say, the spec is way to ambiguous on its definition of timestamps. [YAML 1.2 §10.1. Failsafe Schema](https://yaml.org/spec/1.2.2/#101-failsafe-schema) doesn't actually provide any guidance about what to do with [Example 2.22 Timestamps](https://yaml.org/spec/1.2.2/#example-timestamps) even though it's implied that it shouldn't need an explicit tag. As an editor of other specs, I'd call this a spec bug, not just an implementation one. So congrats, you're both right!

I'm inclined to say we should defer to [RFC 3339 Date and Time on the Internet: Timestamps §5.6 Internet Date/Time Format](https://www.rfc-editor.org/rfc/rfc3339#section-5.6), which covers the `canonical`, `iso8601` and `date` examples, but I really don't know what to do about `spaced: 2001-12-14 21:59:43.10 -5`. If it were me, I'd say allowing space would go from RFC 3339's:
```
   time-numoffset  = ("+" / "-") time-hour ":" time-minute
   time-offset     = "Z" / time-numoffset

   partial-time    = time-hour ":" time-minute ":" time-second
                     [time-secfrac]
   full-date       = date-fullyear "-" date-month "-" date-mday
   full-time       = partial-time time-offset

   date-time       = full-date "T" full-time
```

to instead have:
```
   full-time       = partial-time [" "] time-offset
   date-time       = full-date ("T" / "t" / " ") full-time
```

But then we don't either allow `2019-03-13 20:18:42 +0000` (no colon) or `2001-12-14 21:59:43.10 -5` (not even remotely close to a `time-offset`).

So I guess I'm off to speak with the editors!

**Comment by josephholsten** [comment]
Ah, looks like this example is likely to be removed: https://github.com/yaml/yaml-spec/issues/268
