### ISSUE TITLE
how to dump blank when value is null

### ISSUE THREAD

**Issue by 8427003** [nodeca/js-yaml#478]
i have a js data:
`
{aaaa: null}
`
i wan't get yaml
```
aaa:
```
not wan't to get 
```
aaa: null
```
because in react, delete the last character, the null show!

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#safedump-object---options-

You can replace it only to `~`. Dumping as blank not supported.

**Comment by eternalmatt** [comment]
You can use `{ styles: { '!!null': 'empty' } }` as of js-yaml@4.0.0
