### ISSUE TITLE
Forcing quotation of strings

### ISSUE THREAD

**Issue by furstenheim-geoblink** [nodeca/js-yaml#482]
Hi,
Is it possible to configure js yaml to always quote strings?
Say that I have {include_lines: ['a', 'b']} I'd like it to be dumped as:
```
-include_lines
  - 'a'
  - 'b'
```
At the moment it does not get quoted. My use case is filebeat, which does not recognized unescaped fields

**Comment by puzrin** [comment]
This dupes #454.

You can just write JSON and rename it to `.yml` for your task.

**Comment by rlidwka** [comment]
Added `forceQuotes` option in https://github.com/nodeca/js-yaml/commit/7b256d7612a4c29cdf5dfd48a15e01c8dbbb5291 (currently in **dev** branch).
