### ISSUE TITLE
Question on the code: what is the definition of flow vs block? Is flow ever executed?

### ISSUE THREAD

**Issue by RonWang** [nodeca/js-yaml#488]
New to the codebase so I have a quick question: When will the "block" value be false in code https://github.com/nodeca/js-yaml/blob/665aadda42349dcae869f12040d9b10ef18d12da/lib/js-yaml/dumper.js#L703? Since writeNode is only called in dump function and the level is set to 0, will there be any chance that the block variable be a false value?

**Comment by dota17** [comment]
writeNode function will be called by other functions , eg. writeBlockSequence function. so, the "block" value can be false in other function call.

**Comment by rlidwka** [comment]
see above

In addition to that, `flowLevel` is a user-defined variable, which can also set block to `false` in the following example:

```js
require('js-yaml').dump({a:{b:{c:4}}},{flowLevel:2})
```
