### ISSUE TITLE
Dump function not working with custom tag

### ISSUE THREAD

**Issue by RonWang** [nodeca/js-yaml#489]
First thanks for the great library! 

I'm trying to build a YAML-JSON tool but got some trouble on the JSON->YAML part.
Following the example, I build the custom type like below:
```
function ACustomTag(value) {
    this.klass = 'ACustomTag';
    this.value = value;
}
const customtagYamlType = new yaml.Type('!ACustomTag', {
    kind: 'scalar',
    resolve: data => !!data && typeof data === 'string' && data.trim(),
    construct: data => new ACustomTag(data),
    instanceOf: ACustomTag,
    represent: customTag => customTag.value
});
```
The JSON->YAML part works great, it translates my yaml file, which contains a !ACustomTag to the correct JSON object like
```
key: {
  klass: ACustomTag,
  value: 1
}
```
But when I try to use this result to serialize it back to YAML, this part is not recognized as a ACustomTag class instance. And the yaml result is like
```
key:
  klass: ACustomTag,
  value: 1
```
Instead of expection:
```
key: !AcustomTag 1
```
Is it some configuration part that I need to set to allow it converting custom tag back to YAML?

**Comment by GeekyDeaks** [comment]
I tried you code snippet and it worked for me.  Did you set the `schema` during the call to `dump()`?

https://github.com/nodeca/js-yaml/blob/665aadda42349dcae869f12040d9b10ef18d12da/lib/js-yaml/dumper.js#L810-L813

You can see the options here:

https://github.com/nodeca/js-yaml/blob/665aadda42349dcae869f12040d9b10ef18d12da/lib/js-yaml/dumper.js#L107-L118

**Comment by hakimio** [comment]
@GeekyDeaks for me schema config like described [here ](https://stackoverflow.com/questions/40977113/js-yaml-issue-with-tags) doesn't seem to work at all. It still throws the same `Error: unknown tag !<!ImportValue>`.
I've tested it with load() and safeLoad() functions on the latest version.

**Comment by GeekyDeaks** [comment]
Hi @hakimio - I noticed you are referring to `load()` and this issue is to do with the serialisation via `dump()` as the parsing is working - if your problem is actually related to `load()` can you start another issue and also include some code and YAML to show what you are doing and how you are using the schema?  I'm not a maintainer btw, just a user of the module, but I'll try and help if I can

**Comment by dota17** [comment]
you need to set **schema** to let Dump function work well with custom tag.
```js
function ACutomTag(value){
    this.klass = 'ACustomTag';
    this.value = value;
}

var customtagYamlType = new yaml.Type('!ACustomTag',{
    kind:'scalar',
    resolve:data => !!data && typeof data === 'string' && data.trim(),
    construct: data => new ACutomTag(data),
    instanceOf: ACutomTag,
    represent: customTag => customTag.value
});

// create schema
var schema = yaml.Schema.create([customtagYamlType]);

var obj = new ACutomTag('1');

// set schema
yaml.dump(obj, {schema: schema});
// !<!ACustomTag> '1'
```

**Comment by puzrin** [comment]
Close (not a bug)
