### ISSUE TITLE
Feasible to publish safeLoad and safeDump separately?

### ISSUE THREAD

**Issue by mk-pmb** [nodeca/js-yaml#490]
Hi! Usually I only use the safeLoad function, and very rarely safeDump, so would it be easily feasible to publish them individually? It would also shield me from false-positive npm audit warnings that [only target the unsafe load function](https://www.npmjs.com/advisories/813). Of course I wish us all that it was the last incident, but the future is hard to predict.

**Comment by puzrin** [comment]
No, because that's not convenient and problem is artificial.

**Comment by mk-pmb** [comment]
Thanks for the quick reply.
