### ISSUE TITLE
Is it possible to create an !import tag which will include the data of another file?

### ISSUE THREAD

**Issue by tom-sherman** [nodeca/js-yaml#498]
My use case is this for example:

`foo.yml`

```yml
data: !include bar.yml
```

`bar.yml`

```yml
- 1
- 2
- 3
```

Output:

```json
{
  "data": [1, 2, 3]
}
```

I've started to create a new Type but hit an early stumbling block in that there seems to be no way to access the current file path from within `construct` or similar.

Is there any way to achieve this behaviour currently? If not, would you consider a PR to support this functionality?

**Comment by puzrin** [comment]
Such PR can not be accepted, but seems someone did plugin https://www.npmjs.com/package/yaml-import

**Comment by tylerssn** [comment]
It's unfortunate that this won't be pulled in here. I'm attempting to accomplish the same as described [here](https://docs.platform.sh/configuration/yaml.html#includes) with:

```yaml
web:
    locations:
        '/': !include "main.yaml"
```
