### ISSUE TITLE
Latest 0 will dismiss if use number as item value

### ISSUE THREAD

**Issue by ADU-21** [nodeca/js-yaml#501]
![image](https://user-images.githubusercontent.com/17849012/58251224-b9a97380-7d95-11e9-8671-42f9fc2ae9ae.png)

Refer to my pic, if you put an item value like "balala.10", the latest 0 will gone and only "balala.1" left

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=dmVyc2lvbjogMS4xMAp2OiAnMS4xMCcKYmFsYTogYmFsYWxhLjEw

Everything works as expected.
