### ISSUE TITLE
Preserving order of fields when parsing

### ISSUE THREAD

**Issue by atsepkov** [nodeca/js-yaml#503]
I understand that `Object` in JS has no concept of order, but `Map` does. Since the keys in config yaml file are listed in certain order, there are times when that order matters (i.e. if the yaml file is a set of instructions rather than config). Is there a way to tell the parser to preserve that order and store the data in `Map` instead of `Object`? I was hoping for something like a flag/option to `safeLoad`, but did not see one.

**Comment by puzrin** [comment]
Please provide real example when order is not preserved http://nodeca.github.io/js-yaml.

**Comment by atsepkov** [comment]
It's not so much that it's not preserved, but that its preservation is a side-effect of current implementation on a particular platform. It's not guaranteed to be preserved because Object has no concept of order: https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order. If Object.keys/entries/values() implementation were to change tomorrow in node/Firefox/Chrome, or is implemented using a different algorithm in another JS environment, the order may come out differently. This could result from something as simple as `Object.keys()` deciding to sort results by key's hash value rather than key itself.

It is one of the main reasons Map (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) was added into the spec, which works the same way but guarantees order. I understand that the logic within js-yaml already scans keys in the same order as they are listed in the yaml file, but once that data goes into `{}`, js-yaml can't guarantee that the underlying JS engine won't do something funky with it (i.e. WebAssembly integration/optimization).

Looking under the hood (and sorry if I'm wrong), it looks like js-yaml uses traditional `Object` (https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/dumper.js#L692) to represent the underlying node structure. If there was a flag to switch the underlying structure to a `Map` (with all other things being the same), then the user could guarantee order on any version of JS.

**Comment by puzrin** [comment]
Please, just provide one example from real world, as been requested. This repo is not for discussion about JS, and there are no plans to add maps just for fun.

**Comment by hrj** [comment]
I don't think @atsepkov is discussing JS here. Rather, it is the API contract of this library that is being discussed. The contract is not reliable currently since it depends on non-standardized behaviour of the underlying engines.

**Comment by aeneaswiener** [comment]
> Please provide real example when order is not preserved http://nodeca.github.io/js-yaml.

We are experiencing this issue in the real world 🙂 

We have a yaml based online configuration editor which our users are using to configure our system. They like to preserve the order of their keys in yaml, as they treat the yaml in our editor a bit like they would a programming language. 

When storing to our backend we send JSON. So to save the user's yaml edits, we have to dump the yaml to JSON first, store in the server, load back the JSON from the server, and load it back into yaml string so we can show it to the user in the monaco online editor.

Are you aware of a way to dump the yaml to a json string, whilst preserving the order of the keys as they were in the yaml?

**Comment by AGMETEOR** [comment]
@puzrin it right it actually does preserve the order. I think the confusion comes when you console.log to the browser console and view the object, the object keys appear in a different order.
