### ISSUE TITLE
safeLoad return type error

### ISSUE THREAD

**Issue by fabiospampinato** [nodeca/js-yaml#507]
The docs say that `safeLoad` "Returns a JavaScript object or throws YAMLException on error", but this doesn't seem to be the case to me.

The following returns undefined to me:

```js
require ( 'yaml' ).safeLoad ( '' )
```

The following returns a string even:

```js
require ( 'yaml' ).safeLoad ( 'foo' )
```

**Comment by puzrin** [comment]
That's both correct yamls. Proof:

```
node -e "console.log(require('js-yaml').safeDump('foo'))"
```

**Comment by fabiospampinato** [comment]
Doesn't matter, the docs are saying that when when it doesn't throw an exception an object is returned, so can the docs be updated at least?

**Comment by puzrin** [comment]
I don't understand you. Could you provide a sample, what should be updated and how?

**Comment by fabiospampinato** [comment]
Yes sorry I should have explained myself better.

What I'm saying is that the readme, [here](https://github.com/nodeca/js-yaml/blob/master/README.md#safeload-string---options-), says the following about the `safeLoad` method:

> Returns a JavaScript object or throws YAMLException on error. 

But with the sample code I provided in my first post you can see that `safeLoad` can actually also return `undefined` or `string` values.

The readme should be updated mentioning all the possible types that could be returned by `safeLoad` (object, undefined, string... I'm not sure if it can return any other kind of values).

The problem is that I was relying on the information provided in the readme, i.e. I was excepting `safeLoad` to either return an object or throw an exception, but in some scenarios it can return other types, and that broke my code.

**Comment by puzrin** [comment]
As far as i know `undefined` and `String` are objects in context of JS.

**Comment by fabiospampinato** [comment]
I don't think so, the `String` constructor itself maybe can be considered an object in a broader sense, but `safeLoad` is not returning `String`. 

Check the following examples:

```
typeof undefined // => 'undefined'
typeof 'foo' // => 'string'
typeof {} // => 'object'
typeof String('foo') // => 'string'
```

I think the readme should definitely be fixed mentioning that it can either return a "plain object" (this makes it clearer what we are talking about), "undefined" or a "string", if those are all the possible return types.

**Comment by puzrin** [comment]
I don't think it's needed, but if you do PR with proposed changes, it will be accepted.

**Comment by fabiospampinato** [comment]
I don't pretty much anybody would ever consider `undefined` an "object" to me honest. That sentence being present in the readme is very misleading.

I'll work on  PR 👍
