### ISSUE TITLE
more than one empty line at the end of a file causes parsing to fail

### ISSUE THREAD

**Issue by perpetualgrimace** [nodeca/js-yaml#509]
At [Datawheel](https://github.com/Datawheel/canon) we use this library for setting up design tokens in our build process. We were scratching our heads yesterday because it was reporting that the file didn't exist (it did). After removing extra empty lines from the end of the yaml file, the build passed.

@davelandry may be able to provide more context if needed.

**Comment by davelandry** [comment]
The extra empty lines were at the end of the file. If the yaml file has one empty line at the end, if works fine, but any more than that results in an error.

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=Zm9vOiBiYXIKCgo=

Since this package is not about files, and we can not debug your software, it would be nice if you could provide a minimal possible executable sample to reproduce your problem. Ideally - via online demo.

**Comment by rlidwka** [comment]
```js
console.log(require('js-yaml').safeLoad('foo: bar\n\n\n\n\n\n\n\n'))
// prints { foo: 'bar' }
```

can't reproduce (tried with various `\r\n` combinations), please re-open if you find any test-case for this
