### ISSUE TITLE
paser behavior oddly

### ISSUE THREAD

**Issue by 9k01** [nodeca/js-yaml#510]
```
yaml
-----
a:
- c + 1
output
-----
{ a: [ 'c + 1' ] }

yaml
-----
a:
- 1 + "c"
output
-----
{ a: [ '1 + "c"' ] }

yaml
-----
a:
- "c" + 1
output
-----
bad indentation of a sequence entry at line 2, column 7:
    - "c" + 1
expect
-----
{ a: [ '"c" + 1' ] }
```

https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/loader.js#L1363
readPlainScalar
https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/loader.js#L1375

**Comment by puzrin** [comment]
1. `"c" + 1` is invalid.
2. https://yaml-online-parser.appspot.com/ with reference pyyaml behind, behave the same.
