### ISSUE TITLE
String with leading zeros loses the surrounding quotes and the leading zero

### ISSUE THREAD

**Issue by nulltoken** [nodeca/js-yaml#512]
Hello,

During the json->yaml conversion, the code below seems to show that a string property with a leading zero is altered.

**Using js-yaml version 3.13.1:**
```
$ node -e "console.log(require('js-yaml').safeDump({a: "01"}))"
a: 1
```

I would have expected the following output:
```
a: "01"
```

That looks like an unexpected behavior to me. Any help to keep the quotes and the leading zero during the conversion would be greatly appreciated.

Thanks in advance.

**Comment by puzrin** [comment]
You use wrong quotes combination in shell. This works as expected:

```
node -e 'console.log(require("js-yaml").safeDump({a: "01"}))'
a: '01'
node -e "console.log(require('js-yaml').safeDump({a: '01'}))"
a: '01'
```
