### ISSUE TITLE
Unicode escape sequences not being decoded?

### ISSUE THREAD

**Issue by ronklogan** [nodeca/js-yaml#516]
I have some YAML source files that contain escaped Unicode sequences, as allowed by the YAML specs: \uHHHH (https://yaml.org/spec/1.0/#id2568446). I read the source file, then I pass the content to safeLoad. But the object that comes back has the escape sequences _escaped_, not decoded. 

For example, if test.yml contains:

```
codeDesc: \u4E88\u7D04\u756A\u53F7
```
And I read and process the file like:

```
const fs = require('fs');
const yml = require('js-yaml');
fs.readFile('test.yml', 'utf8', (err, dataYaml) => {
  if (err) { console.error(`${err}`); return; }
  const object = yml.safeLoad(dataYaml);
  console.log(JSON.stringify(object, null, 2));
});
```

The output is (note the escaped escape sequences):

```
{
  "codeDesc": "\\u4E88\\u7D04\\u756A\\u53F7"
}
```

Shouldn't the parsed object have a codeDesc property that is a string containing three decoded Unicode characters (not 24)?

**Comment by ronklogan** [comment]
Heh. That should be "containing FOUR decoded Unicode characters." It's Monday....

**Comment by perlpunk** [comment]
put the escapes in double quotes.
```
codeDesc: "\u4E88\u7D04\u756A\u53F7"
```

Double quotes is the only form of quoting where escape sequences are recognized.

**Comment by ronklogan** [comment]
Makes sense! Thanks!
