### ISSUE TITLE
Esprima is deprecated, Espree is the replacement

### ISSUE THREAD

**Issue by cmstead** [nodeca/js-yaml#518]
Hi,

I'm not sure whether someone else has let you know, but Esprima is not longer being supported.  I don't know what you are using it for, but if you need a JS parser that is actively being supported, Espree is the replacement.

Espree is ESTree compliant so it is an acceptable drop-in replacement.

Thanks for all your work.  Cheers!

**Comment by puzrin** [comment]
Where can i read announces about stopping esprima support?

**Comment by cmstead** [comment]
Oh, my apologies! Esprima apparently is still being supported. 

However, projects like eslint are moving away from Esprima because of their lagging support for ES standards. Below is where the ESLint team explains:

https://eslint.org/blog/2014/12/espree-esprima

Sorry for the mistake. You're welcome to close this if you like.
