### ISSUE TITLE
Support ES6 Import Syntax

### ISSUE THREAD

**Issue by KingDarBoja** [nodeca/js-yaml#531]
It is possible to support the ES6 import syntax with this package?

I tried using on some typescript package and then installed such package on another one, but getting the following error:
```console
error TS7016: Could not find a declaration file for module 'js-yaml'. 'path/to/custom/package/node_modules/js-yaml/index.js' implicitly has an 'any' type.
  Try `npm install @types/js-yaml` if it exists or add a new declaration (.d.ts) file containing `declare module 'js-yaml';
```

I did used:
`import * as jsyaml from 'js-yaml';`
or
`import { safeLoad, safeDump } from 'js-yaml';` 

But none of them works, even with `@types/js-yaml` installed as devDependency but still doesn't work.

Of course, the default way does work but was looking for some ES6 import syntax support.

Cheers!

**Comment by puzrin** [comment]
There no plans to rewrite syntax to es6, until node starts officially support import and tools become stable.

You can try to bundle package yourself via rollup.js.

**Comment by steren** [comment]
Node.js [officially supports `import`](https://nodejs.org/api/esm.html) and the entire JS ecosystem is progressively moving towards import.

Would it be possible to re-open this feature request?

It would notably allow to load `js-yaml` in browsers in a more robust way than by loading it as a global variable.

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/package.json#L31

**Comment by steren** [comment]
Nice, in a browser, I confirm am able to do:

```
import { load, dump } from 'https://cdn.jsdelivr.net/npm/js-yaml@4.1.0/dist/js-yaml.mjs';
```

**Comment by keisanng** [comment]
> Node.js [officially supports `import`](https://nodejs.org/api/esm.html) and the entire JS ecosystem is progressively moving towards import.
> 
> Would it be possible to re-open this feature request?
> 
> It would notably allow to load `js-yaml` in browsers in a more robust way than by loading it as a global variable.

^
