### ISSUE TITLE
__proto__ vulnerability

### ISSUE THREAD

**Issue by KSXGitHub** [nodeca/js-yaml#533]
```javascript
const { load, safeLoad } = require('js-yaml')
const yamlText = '__proto__: { evil: true }'
const a = load(yamlText)
const b = safeLoad(yamlText)
console.log(a.evil, b.evil)
```

**Expect:** `undefined undefined`
**Received:** `true true`

If I use `js-yaml` to process user's input, it would allow malicious users to inject object prototype into my server.

**Comment by puzrin** [comment]
1. This dupes #164.
2. This is NOT vulnerability, because does not affects other objects.
