### ISSUE TITLE
loading non-string keys with JSON_SCHEMA should error?

### ISSUE THREAD

**Issue by notEthan** [nodeca/js-yaml#538]
hi nodeca friends. I am trying to restrict the documents a tool can parse to those compatible with JSON. for values not supported by JSON, js-yaml will raise `YAMLException`, which is what I would expect. but for keys, it silently stringifies them.

```javascript
yaml.safeLoad("1: 'one'", {schema: yaml.JSON_SCHEMA})
// returns { '1': 'one' }
```

is it possible to detect and reject documents which do not have JSON compatible keys using js-yaml?

**Comment by notEthan** [comment]
I'm realizing, actually, looking through YAML's [JSON schema](https://yaml.org/spec/1.2/spec.html#id2803231), it doesn't actually say anything about mapping keys, meaning the failsafe definition would apply ("YAML places no restrictions on the type of keys; in particular, they are not restricted to being scalars"). despite that not being compatible with JSON.

so this issue isn't really about JSON_SCHEMA, I guess. maybe a more generic option to reject key types which cannot be represented in JS, rather than stringifying, is appropriate?

**Comment by dota17** [comment]
> hi nodeca friends. I am trying to restrict the documents a tool can parse to those compatible with JSON. for values not supported by JSON, js-yaml will raise `YAMLException`, which is what I would expect. but for keys, it silently stringifies them.
> 
> ```js
> yaml.safeLoad("1: 'one'", {schema: yaml.JSON_SCHEMA})
> // returns { '1': 'one' }
> ```

as i know, even if for values not supported by JSON, js-yaml will not raise `YAMLException`,either. Can you show your error value case ?

**Comment by notEthan** [comment]
the readme notes in section [safeLoad](https://github.com/nodeca/js-yaml/#safeload-string---options-) some cases where `YAMLException` is raised. I'm trying to detect and reject documents which do not have JSON compatible keys - `YAMLException` might be the correct vehicle to do that, or maybe a different control flow would be more appropriate.

**Comment by puzrin** [comment]
js-yaml does NOT throw exception for valid yaml. Because valid yaml must be loaded. But some types are loaded different https://github.com/nodeca/js-yaml#supported-yaml-types. Keys are stringified somehow.

Restriced schema will cause just more plain scalars. IMO your question is not specific to this package

**Comment by dota17** [comment]
use [custom type](https://github.com/nodeca/js-yaml/wiki/Custom-types) to detect unvalid keys and throw Error.
```js
var JsonKeyType = new yaml.Type('!JsonKey',{
    kind:'scalar',
    resolve:function(data){
        // you need to custom regx to detect invalid keys
        var regx = /[0-9]+/;
        if(regx.test(data)){
            throw new Error('invalid numeric key')
        }
        return true;
    },
    construct: function(data){
        return data;
    }
})

var schema = yaml.Schema.create(yaml.JSON_SCHEMA, [JsonKeyType]);
var input = "? !JsonKey 1: one";
yaml.safeLoad(input, {schema: schema});
//Error: invalid numeric key
```

**Comment by notEthan** [comment]
> js-yaml does NOT throw exception for valid yaml

this is not the case when using safeLoad with a type it doesn't support; it raises `YAMLException`. this seems good, and a way non-string keys could be handled (optionally of course).

> Restriced schema will cause just more plain scalars. IMO your question is not specific to this package

I'm not sure what this means. this package is the one parsing the yaml and silently stringifying keys. I am seeking a way to handle non-string keys differently.

@dota17 I appreciate the suggestion but the yaml being parsed is not under my control to apply custom types to it. I am trying to reject user-supplied yaml containing non-string keys.

**Comment by puzrin** [comment]
> I'm not sure what this means. this package is the one parsing the yaml and silently stringifying keys. I am seeking a way to handle non-string keys differently.

I'd suggest you try one of libyaml wrappers. This parser was written in more simple way, and is a bit limited.
