### ISSUE TITLE
Large ini content should not be using folded style blocks >

### ISSUE THREAD

**Issue by brandonkal** [nodeca/js-yaml#539]
For the most part, `>` should be avoided.

Here is an example of the beginning of a dumped yaml string. Note that it is using folded style instead of literal newlines. This is not how a human would write the contents.
This particular file contents is 1,242 lines long. It would be half that if `|` was used instead.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  app.ini: >
    ; This file lists the default values used by Gitea

    ; Copy required sections to your own app.ini (default is
    custom/conf/app.ini)

    ; and modify as needed.


    ; see https://docs.gitea.io/en-us/config-cheat-sheet/ for additional
    documentation.


    ; App name that shows in every page title

    APP_NAME = foobar
```

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/dumper.js#L274

Everything is already supported and works as expected. Just set high max line length limit.

**Comment by brandonkal** [comment]
My longest line is 194. But the other 600+ are around 80. I would hope the logic would take that into account.
