### ISSUE TITLE
Exception thrown on reload

### ISSUE THREAD

**Issue by shooshx** [nodeca/js-yaml#546]
I'm using this in a browser and its quite a pain that there's a exception thrown when the code is loading.

**Comment by puzrin** [comment]
Such not concrete bug reports are not accepted. If ou think problem is with this package - provide a minimal possible code sample, without extra packages.

**Comment by shooshx** [comment]
Are you kidding? What's not concrete about "exception is thrown when code is loading"?
The minimal possible code sample is:
`<script src="js-yaml.js"></script>`
If you put that in an html file, load it in a browser with "Pause on caught exceptions" as one would do when debugging a web page, you would see the code in js-yaml.js throwing an exception due to modules "buffer" and "esprima" not being present.
This makes working with this module a pain for web developers.
If you don't want to fix it, don't, I don't care, I already fixed the local copy I'm using. I just thought to help out the next person that thinks this is a pain.

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#bundled-yaml-library-for-browsers

This module is stable, and works in browser. Instead of writing many words you could provide repo with reproducible sample, if you need help.

**Comment by shooshx** [comment]
I didn't say it doesn't work. I said it throws an exception on load, and then catches it, and that disrupts the debugging workflow of a web developer.
This also happens in the "Online Demo" linked from your README.md.
If you open the online demo in chrome, open developer tools (F12), mark the "Pause on caught exception" on the top right corner and reload the page, you would see an exception thrown when doing require("buffer").

It's strange that you insist on dissing and ignoring someone who wants to help you make your library better instead of trying to understand what I'm saying.

**Comment by puzrin** [comment]
> I didn't say it doesn't work. I said it throws an exception on load, and then catches it, and that disrupts the debugging workflow of a web developer.

That's expected behaviour, used to detect existing modules.

> It's strange that you insist on dissing and ignoring someone who wants to help you make your library better instead of trying to understand what I'm saying.

Please, stop brainfucking. If you have default permission to post in this tracker, that does not means any your posting is welcome.
