### ISSUE TITLE
RegExp support for custom tag

### ISSUE THREAD

**Issue by tianranwangcs** [nodeca/js-yaml#552]
Say there is a set of custom tags like `!customTag1`, `!customTag2`, `!customTag3` ... in the yaml file. We don't know the number of such tags before loading it. Is there a way to use RegExp `/!customTag[\d]*/` when creating schemas?

**Comment by puzrin** [comment]
This parser does not use regexp, but your demand can be done via #385 when complete.

**Comment by rlidwka** [comment]
Added in https://github.com/nodeca/js-yaml/commit/73ef02cfcb63d9f1c5932dadc1fc35f05a25fdbc (currently in `dev` branch).

See an example how to do it here:
https://github.com/nodeca/js-yaml/blob/a0d0caa5aa0f5354fefa9c637cfb7c4c17ef7d02/examples/handle_unknown_types.js

Note that it works using prefix, not RegExp.
