### ISSUE TITLE
Is there any way to add array item as [] rather than collection of -

### ISSUE THREAD

**Issue by gauravsourcefuse** [nodeca/js-yaml#553]
I need to convert JSON array to flow-style array element.
Input json:
```
{ name: 'bundle', x: ['one', 'two', 'three'] }
```
Output YAML;
```
name: 'bundle'
x:
- one
- two
- three
```
Expected:
```
name: 'bundle'
x: [one, two, three]
```

**Comment by gauravsourcefuse** [comment]
I need to convert JSON array to flow-style array element.

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#safedump-object---options-

try `{ flowLevel: 1 }`, no more options about that.
