### ISSUE TITLE
Supported Node.js versions

### ISSUE THREAD

**Issue by jlenos-inflight** [nodeca/js-yaml#556]
I just saw this line in the CHANGELOG.md for v3.14.0:
"CI: drop outdated nodejs versions."

Does this imply that the package now only supports Node.js 12 and up?
If so, shouldn't the release have been a major release?

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/.eslintrc.yml#L4

It's still validated to be es5. Fresh node required for testing instruments only (mocha, eslint).

**Comment by jlenos-inflight** [comment]
Thanks for clarifying 👍
