### ISSUE TITLE
Error expanding anchors

### ISSUE THREAD

**Issue by OnkelTem** [nodeca/js-yaml#559]
For some reason **js-yaml** fails on parsing this valid YAML:
```yaml
devs:
  - &dev1  Alice
  - &dev2  Bob
  - &devop Jane
time:
  - name: Project 1
    devs:
      *dev1: 120 hours
      *devop: 32 hours 
  - name: Project 2
    devs:
      *dev2: 154 hours
      *devop: 21 hours 
```
which should render into this structure:
```json
{
  "devs": [
    "Alice", 
    "Bob", 
    "Jane"
  ], 
  "time": [
    {
      "devs": {
        "Jane": "32 hours", 
        "Alice": "120 hours"
      }, 
      "name": "Project 1"
    }, 
    {
      "devs": {
        "Jane": "21 hours", 
        "Bob": "154 hours"
      }, 
      "name": "Project 2"
    }
  ]
}
```
But it just fails to parse: 
```
unidentified alias "dev1:" at line 8, column 13:
          *dev1: 120 hours
                ^
```
[Demo link](http://nodeca.github.io/js-yaml/#yaml=ZGV2czoKICAtICZkZXYxICBBbGljZQogIC0gJmRldjIgIEJvYgogIC0gJmRldm9wIEphbmUKdGltZToKICAtIG5hbWU6IFByb2plY3QgMQogICAgZGV2czoKICAgICAgKmRldjE6IDEyMCBob3VycwogICAgICAqZGV2b3A6IDMyIGhvdXJzIAogIC0gbmFtZTogUHJvamVjdCAyCiAgICBkZXZzOgogICAgICAqZGV2MjogMTU0IGhvdXJzCiAgICAgICpkZXZvcDogMjEgaG91cnMgCgoK)

Another example I tried — PHP original YAML parser (PHP 7.2.24):

```php
<?php

$yaml = "
devs:
  - &dev1  Alice
  - &dev2  Bob
  - &devop Jane
time:
  - name: Project 1
    devs:
      *dev1: 120 hours
      *devop: 32 hours 
  - name: Project 2
    devs:
      *dev2: 154 hours
      *devop: 21 hours 
";

$res = yaml_parse($yaml);

print_r($res);
```
makes:
```
Array
(
    [devs] => Array
        (
            [0] => Alice
            [1] => Bob
            [2] => Jane
        )
    [time] => Array
        (
            [0] => Array
                (
                    [name] => Project 1
                    [devs] => Array
                        (
                            [Alice] => 120 hours
                            [Jane] => 32 hours
                        )
                )
            [1] => Array
                (
                    [name] => Project 2
                    [devs] => Array
                        (
                            [Bob] => 154 hours
                            [Jane] => 21 hours
                        )
                )
        )
)
```

**Comment by perlpunk** [comment]
There must be a space after an `*alias` key.
libyaml and PyYAML (and probably all libs originating from them) are doing this wrong and accept this invalid YAML.

**Comment by OnkelTem** [comment]
@perlpunk Thank you Tina! I was sure that PyYaml was sort of a bugs-free :)

[Corrected demo link](http://nodeca.github.io/js-yaml/#yaml=ZGV2czoKICAtICZkZXYxICBBbGljZQogIC0gJmRldjIgIEJvYgogIC0gJmRldm9wIEphbmUKdGltZToKICAtIG5hbWU6IFByb2plY3QgMQogICAgZGV2czoKICAgICAgKmRldjEgOiAxMjAgaG91cnMKICAgICAgKmRldm9wIDogMzIgaG91cnMgCiAgLSBuYW1lOiBQcm9qZWN0IDIKICAgIGRldnM6CiAgICAgICpkZXYyIDogMTU0IGhvdXJzCiAgICAgICpkZXZvcCA6IDIxIGhvdXJzIAoKCgk=)

I'm closing it.
