### ISSUE TITLE
Strings starting with 0 and containing 8 or 9 do not get quoted

### ISSUE THREAD

**Issue by ndchelsea** [nodeca/js-yaml#562]
Strings starting with 0 and containing 8 or 9 do not get quoted.

For example, 018561471342 (string) does not get quoted, which means that in many 1.2 compliant parsers will read it as 18561471342 (number).

The yaml 1.2 spec (https://yaml.org/spec/1.2/spec.html#id2761292 for reference) states that an octal number is formed 0o##### which is different from the 1.1 spec in which the "o" would be absent, which is the reason this same issue has been closed multiple times in the past.

Would either a strict 1.2 compliance mode or just generally quoting strings be acceptable? If so, I can send a pr. (preferably the latter because I don't know the whole spec and the former sounds like a huge can of worms ;) )

**Comment by perlpunk** [comment]
here are the 1.1 and 1.2 schemas in a compact form: https://perlpunk.github.io/yaml-test-schema/schemas.html
also examples: https://perlpunk.github.io/yaml-test-schema/data.html

hope that helps

**Comment by ndchelsea** [comment]
that sounds great - i am not sure how to configure that but will look at it when I have a chance - thanks for the help!
