### ISSUE TITLE
newline between siblings dump option?

### ISSUE THREAD

**Issue by gentunian** [nodeca/js-yaml#563]
Hi there,

I'm not finding if there's an option that adds newlines between siblings while dumping.

Consider this simple JSON: 
```
{
  foo: "this is foo",
  bar: "this is bar"
}
```

will be dumped as:

```
foo: this is foo
bar: this is bar
```

When yml is tiny it may be easy to read, but when yml is more complex and with nested values, it would be nice that siblings or root levels be newline-separated.

```
foo: this is foo

bar: this is bar 
```

is this possible?

**Comment by j0urneyK** [comment]
@gentunian Did you find a way?
I was also looking for such an option.

**Comment by gentunian** [comment]
Hi @j0urneyK I did not. I have closed it mainly because 
two reasons. To be kind with the project and maybe this "feature/option" may not be a parser responsibility after reading another responses that makes sense to me.

But I could be wrong. Glad to know I wasn't the only one. :)

**Comment by j0urneyK** [comment]
@gentunian Thanks for the reply!
