### ISSUE TITLE
Dump for multi-documents

### ISSUE THREAD

**Issue by MelMacaluso** [nodeca/js-yaml#564]
Hi there,

Is this feature supported? I didn't find it in the docs.

Had to do a temp string variable and append to it from the `safeLoadAll()` array joining it with `---\n`

If needed I can do a PR.

**Comment by puzrin** [comment]
IMO it's too trivial and almost never needed. You could do:

```js
[docs_to_dump].map(doc => yaml.safeDump(doc)).join('---\n');
```

**Comment by MelMacaluso** [comment]
Too trivial yes, almost never needed no, if you want to edit a parsed javascript object from a multi-document yaml sometimes you want to get it back as a multi-document.

Adding a method for this, overkill agreed, what about a param in safeDump?

**Comment by puzrin** [comment]
safeDump is for single doc, it should not accept multiple.

**Comment by manuth** [comment]
in this case I recommend adding a method `safeDumpAll` and `dumpAll`.

**Comment by puzrin** [comment]
Close (no need to spoil api when trivial solution exists)

**Comment by MichaelSp** [comment]
Adding this trivial solution to the README would be a good idea though

**Comment by MelMacaluso** [comment]
> Adding this trivial solution to the README would be a good idea though

No is too trivial even for that 😂 /sarcasm

**Comment by CiscoRob** [comment]
Lots of "that is trivial" to do ... but I think those pointing out the trivial way to do it already know that there is no built-in way to do it.

For an API that has "load" and "loadAll" but only a single "dump" with no explicit options parameter to identify saving as multiple documents. 

That just sounds like a bad API design. Intuitively speaking if I was under the context of a single document I'd expect:

- load
- dump

When working with multi-document files you've already _explicitly_ created "loadAll". No options provided to the load function.

The matching named function I looked for immediately was:

- loadAll
- dumpAll

Failing to find a reason why `LoadOptions` didn't have an optional "multi-document" identifier and you only realize `loadAll` is needed after using `load` and receiving a failure about additional data in the stream.

Now, it may seem trivial, but based on the inconsistent naming an _expectation_ was established that working with a single file requires load.

If you want to talk about trivial:

```
export function load(str: string, iterator?: null, opts?: LoadOptions): unknown[];
export interface LoadOptions {
    . . . 
    /** read all documents in file */
    multiDocumentFile?: boolean | undefined
}

export function dump(obj: any, opts?: DumpOptions): string;
export interface DumpOptions {
    . . . 
    /** if true, save each entity as a single document instead of an array of entities */
    multiDocumentFile?: boolean | undefined;
}
```

Now, that's trivial. Plus it doesn't pollute the existing API, removes a misleading `loadAll` that creates an expectation of a `dumpAll`, and solves the problem with "well if there is a load all - how do you save all?" question that prompted me to find this issue.

**Comment by pkit** [comment]
Yeah, `loadAll` is there but no `dumpAll`. Tactical facepalm.
