### ISSUE TITLE
empty string should return empty object instead of undefined

### ISSUE THREAD

**Issue by gentunian** [nodeca/js-yaml#565]
Is there  any good reason why `yaml.safeLoad("")` returns `undefined` instead of `{}`?

It looks to me that emtpy string should match empty object. Also, an empty file say `file.yml` may be empty and loading it should return the emtpy object also.

Looks to me that undefined may refer to more than one semantics and may be ambiguos, say an error or whatever the `safeLoad()` method does inside that honestly I don't care what it does in detail, but I care the "contract" of its use.

**Comment by puzrin** [comment]
This parser is about yaml spec, not about about community-voted opinion :). When you create such requests, you are expected refer to yaml spec, reference libyaml implementation and so on.

https://yaml-online-parser.appspot.com/?yaml=&type=json

pyyaml implemenaion returns null (but no object).

**Comment by gentunian** [comment]
thanks for the comment and feedback, I agree with specs should be used.

As a opinionated issue, `null` and `undefined` to me should not map to a valid input, such as empty string or empty file. Empty string is not an absence of string and empty file is not an absence of a file. They exists are are valid.

And looking into specs for what a null type means in yaml I found: https://yaml.org/type/null.html

> A null value is used to indicate the lack of a value. This is typically converted into any native null-like value (e.g., undef in Perl, None in Python). Note that a null is different from an empty string and that a mapping entry with some key and a null value is valid and different from not having that key in the mapping.

**Comment by perlpunk** [comment]
An empty **string** in YAML is expressed like this: `''`, `""`.
The YAML document you are showing is completely empty, that means, it contains an empty **scalar node**, not an empty **string**.
Empty scalars are resolved as `null`, like specified in the 1.1 spec https://yaml.org/type/null.html and in the 1.2 spec https://yaml.org/spec/1.2/spec.html#id2805071.

**Comment by puzrin** [comment]
@perlpunk thank you! created #567

**Comment by perlpunk** [comment]
@puzrin sorry, my explanation was incorrect! I edited it. Hope it's clearer now.

**Comment by puzrin** [comment]
NP. Closed :)

**Comment by rlidwka** [comment]
> However, loadAll should return an empty list, which is not the case right now I think.

Checked, `loadAll('')` returns an empty list, see https://github.com/nodeca/js-yaml/issues/567#issuecomment-692826761 for details.

**Comment by puzrin** [comment]
@perlpunk, is it correct to throw an exception for empty input for `.load()` single document? That should solve the problem "how to return nothing". Technically, that's a bad input ~ the same problem as bad formatting.

For `.loadAll` things stay the same - empty array.
