### ISSUE TITLE
'duplicated mapping key' error with unique keys

### ISSUE THREAD

**Issue by MGough** [nodeca/js-yaml#573]
I think I've found an issue when dealing with a YAML mapping containing a large number of keys. 

This can be reproduced by running this minimal example through the [JS-YAML Demo](http://nodeca.github.io/js-yaml/)

This is my minimal example (I'm not including it as a code block here due to the number of lines):
https://gist.github.com/MGough/e38b2cf7b41c151ba8216b77a08c9177

It looks almost like a hash conflict, once the final key/value pair is removed the issue goes away. You can remove a different key value pair and the issue persists. From what I can tell there aren't any duplicate keys. This was also an issue when there were more keys after the final one in this example, I've just removed them as they were redundant.

**Comment by MGough** [comment]
Seems like it's not specific to the number of keys, I'm guessing it's something else I've missed perhaps like a whitespace issue. Although other YAML validators online show it as valid

**Comment by puzrin** [comment]
[Minimized example](https://nodeca.github.io/js-yaml/#yaml=YToKICAxMDUxMzQ3ODUwODE2Nzc4MUU1ODQ1NTogMjMzNQogIDExMTkzNDMwNjQ0MzUyODMyRTExMjgxOiAyNDUyCg==)

```yaml
a:
  10513478508167781E58455: 2335
  11193430644352832E11281: 2452
```

**Comment by MGough** [comment]
> [Minimized example](https://nodeca.github.io/js-yaml/#yaml=MTA1MTM0Nzg1MDgxNjc3ODFFNTg0NTU6IDIzMzUKMTExOTM0MzA2NDQzNTI4MzJFMTEyODE6IDI0NTIK)
> 
> ```yaml
> 10513478508167781E58455: 2335
> 11193430644352832E11281: 2452
> ```
> 
> both keys => big integers in scientific notation (10513478508167781 e 58455) => `Infinity` => duplicated infinity.
> 
> Seems work as expected. Who generated this yaml data? I would strongly recommend to quote keys. May be other langs can each huge numbers, but JS - no.

Thank you! Apologies for bringing you an issue that's ultimately not yours, my lack of JS expertise would've had me working on that for days 😆 . I hadn't spotted the `E` at all.

As for where it came from, it was actually generated using the python `yaml` library. I think what has happened is that the python `yaml` library quite happily serialized a python dict, which can have any object as a key, rather than serializing JSON.

**Comment by puzrin** [comment]
https://github.com/yaml/pyyaml/issues/173 AFAIK, there may be difference between spec and real code due need of JSON compatibility. But i don't remember details.

In theory, according to spec, your dump is correct, because scientific notation must have sign before exponent: `1e+5`. BUT json is ok without sign too (and YAML is declared as JSON-compatible):

```sh
node -e 'console.log(JSON.parse("1e5"))'
```

If anyone wish dive into spec sugges changes - i'm open to suggesion.
