### ISSUE TITLE
Support for ansible vault content

### ISSUE THREAD

**Issue by Knskan3** [nodeca/js-yaml#580]
At the moment when trying to read a yaml file with ansible `vault` values, it will throw an exception
```YAMLException: unknown tag !<!vault>```

https://docs.ansible.com/ansible/latest/user_guide/vault.html#ansible-vault

Thanks

**Comment by puzrin** [comment]
Custom tags shold be implemened at user side, here is nothing to add. Ignoring nimplemed ags will be possible when #385 done.

**Comment by bignose-debian** [comment]
> Custom tags shold be implemened at user side, here is nothing to add.

At the 'js-yaml' project there appears to be no clear guidance how the "user side" should do this. Can you reply here and link to comprehensive documentation so people can implement this as you say?
