### ISSUE TITLE
escaping and text

### ISSUE THREAD

**Issue by dcsan** [nodeca/js-yaml#583]
I'm trying to get an output which is like `\#something`
but having a hard time. It seems to get converted to something double-escaped `\\#`

I've tried combinations using single and double quotes without luck

```yaml
        long:
          join \#team-01 to start
```

result

```
'join \\#team-01 to start'
```

this:
```yaml
long: "join \#team-01 to start"
```

gives a parser error unless I double escape it inside the double quotes `"\\#team-01"

with a single quote I 

```
        long: 'join \#team-01 to start'
```
I still get a double escaped output

```
'join \\#team-01 to start'
```

is there a way to get a parsed result with just a single backslash?

**Comment by perlpunk** [comment]
FYI: https://stackoverflow.com/questions/64240124/yaml-output-with-single-escape

**Comment by puzrin** [comment]
Close as nothing to solve.
