### ISSUE TITLE
Cannot escape cron expression

### ISSUE THREAD

**Issue by shusson** [nodeca/js-yaml#584]
json: 

```
schedule: "0 03 * * *"
```

yaml dump:

```
schedule: 0 03 * * *
```

As described [here](https://support.asg.com/mob/mvw/10_0/mv_ag/using_quotes_with_yaml_special_characters.htm)

> It is not necessary to use quotes when a single special character is surrounded by spaces...
> Use quotes if a special character is part of a longer string. For example, the cron string */5 * * * * requires quotes ("*/5 * * * *").

Is there a way to force the dump to escape the cron sequence?

**Comment by perlpunk** [comment]
Quotes are not necessary here. The example in the link says:
`For example, the cron string */5 * * * * requires quotes ("*/5 * * * *")`
This needs quotes, because it starts with a `*`, which is special.

(See also my tutorial on quoting: https://www.yaml.info/learn/quote.html)

**Comment by shusson** [comment]
Thanks @perlpunk , it was an issue with how we were parsing the string.
