### ISSUE TITLE
flow style and block style arrays in yaml

### ISSUE THREAD

**Issue by charithreddyv** [nodeca/js-yaml#586]
Is there a way to support both flow style and block style arrays in same yaml 
JSON:

`{
   "flow_choices" : [ 1, 2 ], 
   "block_choices": [4, 5]
}`

to 

YAML:

 `flow_choices: [1, 2]`
 `block_choices:` 
   `- 4`
   `- 5`

**Comment by rlidwka** [comment]
There is no specific way to mix styles in API currently. We would like to keep dumper as simple as possible, so we can't add every formatting option any person asks for.

If you really really want to use different styles in the same document, you can play around with this:

```js
const yaml = require('js-yaml');

function CustomDump(data, opts) {
  if (!(this instanceof CustomDump)) return new CustomDump(data, opts);
  this.data = data;
  this.opts = opts;
}

CustomDump.prototype.represent = function () {
  let result = yaml.dump(this.data, Object.assign({ replacer, schema }, this.opts));
  result = result.trim();
  if (result.includes('\n')) result = '\n' + result;
  return result;
}


let CustomDumpType = new yaml.Type('!format', {
  kind: 'scalar',
  resolve: () => false,
  instanceOf: CustomDump,
  represent: d => d.represent()
});


let schema = yaml.DEFAULT_SCHEMA.extend({ implicit: [ CustomDumpType ] });

function replacer(key, value) {
  if (key === '') return value; // top-level, don't change this
  if (key === 'flow_choices') return CustomDump(value, { flowLevel: 0 });
  if (key === 'block_choices') return CustomDump(value, { flowLevel: Infinity });
  return value; // default
}

console.log(CustomDump({ "flow_choices" : [ 1, 2 ], "block_choices": [4, 5] }).represent().trim());

/* Returns:

flow_choices: [1, 2]
block_choices:
- 4
- 5
*/
```

**Comment by pokey** [comment]
Fwiw [here](https://github.com/cursorless-dev/cursorless/blob/b639e42c6776cf758b758d5f9affbc0f1abb47a5/src/testUtil/serialize.ts) is an example of using @rlidwka's code above to inline simple objects / lists (ie all their children are scalar), as well as to inline the value at a particular key (`fullTarget`).  We added some types as well
