### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by arcanis** [nodeca/js-yaml#591]
Ref: https://github.com/nodeca/js-yaml/issues/345#issuecomment-734812253

> We're using `js-yaml` on Yarn (our lockfiles are now regular Yaml), and to make our users' life easier we try to gracefully recover from lockfile merge conflicts (basically we parse both current and incoming versions of the lockfile, then merge them together). It turns out that in some circumstances Git will generate a [bogus lockfile](https://gist.github.com/arcanis/3778f61718474f0e647f847986895077) that duplicates some keys.

Since js-yaml doesn't support duplicated keys and aborts as soon as it sees one, we can't apply this auto-merge process when this situation happens (in our case, a valid strategy would be to simply ignore the duplicates, as they are assumed to have the same content).

While thinking about this problem I think one possible alternative would be for our project to hack our way around by using a regex to add the line number in front of each top-level key, parsing the files, then removing the number prefixes 🤔 It's sounds quite the ugly workaround though 😅

**Comment by rlidwka** [comment]
I've just found this by accident going through documentation:

> json (default: false) - compatibility with JSON.parse behaviour. If true, then duplicate keys in a mapping will override values rather than throwing an error.

```js
> require('js-yaml').load('foo: 3\nfoo: 4')
Thrown:
{ YAMLException: duplicated mapping key at line 2, column 1 }

> require('js-yaml').load('foo: 3\nfoo: 4', { json: true })
{ foo: 4 }
```

**Comment by puzrin** [comment]
@arcanis seems we can close that?
