### ISSUE TITLE
Convert library code to ESM to improve generated ESM exports

### ISSUE THREAD

**Issue by realityking** [nodeca/js-yaml#598]
Right now `js-yaml` is written in CommonJS and rollup is used to generate ES Modules from it.

This generates a somewhat unfortunate export for the ESM version where it generates a default export that should not be present:

```
var jsYaml = {
	Type: Type$1,
	Schema: Schema$1,
	FAILSAFE_SCHEMA: FAILSAFE_SCHEMA,
	JSON_SCHEMA: JSON_SCHEMA,
	CORE_SCHEMA: CORE_SCHEMA,
	DEFAULT_SCHEMA: DEFAULT_SCHEMA,
	load: load$1,
	loadAll: loadAll$1,
	dump: dump$1,
	YAMLException: YAMLException$1,
	safeLoad: safeLoad,
	safeLoadAll: safeLoadAll,
	safeDump: safeDump
};

export default jsYaml;
export { CORE_SCHEMA, DEFAULT_SCHEMA, FAILSAFE_SCHEMA, JSON_SCHEMA, Schema$1 as Schema, Type$1 as Type, YAMLException$1 as YAMLException, dump$1 as dump, load$1 as load, loadAll$1 as loadAll, safeDump, safeLoad, safeLoadAll };
```

Worse, this carries forward to the UMD build since rollup's internal representation is based on ESM. It creates a `default` property of its own:

```
var jsYaml = {
  	Type: Type$1,
  	Schema: Schema$1,
  	FAILSAFE_SCHEMA: FAILSAFE_SCHEMA,
  	JSON_SCHEMA: JSON_SCHEMA,
  	CORE_SCHEMA: CORE_SCHEMA,
  	DEFAULT_SCHEMA: DEFAULT_SCHEMA,
  	load: load$1,
  	loadAll: loadAll$1,
  	dump: dump$1,
  	YAMLException: YAMLException$1,
  	safeLoad: safeLoad,
  	safeLoadAll: safeLoadAll,
  	safeDump: safeDump
  };

  exports.CORE_SCHEMA = CORE_SCHEMA;
  exports.DEFAULT_SCHEMA = DEFAULT_SCHEMA;
  exports.FAILSAFE_SCHEMA = FAILSAFE_SCHEMA;
  exports.JSON_SCHEMA = JSON_SCHEMA;
  exports.Schema = Schema$1;
  exports.Type = Type$1;
  exports.YAMLException = YAMLException$1;
  exports.default = jsYaml;
  exports.dump = dump$1;
  exports.load = load$1;
  exports.loadAll = loadAll$1;
  exports.safeDump = safeDump;
  exports.safeLoad = safeLoad;
  exports.safeLoadAll = safeLoadAll;
```

The easiest solution to this would be to convert the code of the library itself to ESM. From experience I know that ESM will also generate somewhat more optimized code in this situation and reduce the size of the generated code by a couple of percent.

Would you be open to a PR to do this?

**Comment by puzrin** [comment]
> Would you be open to a PR to do this?

Sorry, not now. Current mode is used because no time to experiment with development process change in multiple maintained repos.

Could you explain, what's exactly wrong with exported `.default`? Does it prevent use package, break tree-shaking, or something else?

**Comment by realityking** [comment]
This creates two problems:

1. It becomes part of the public interface and needs to be taken into account in future iterations of `js-yaml`
2. It affects tree shaking with _some_ bundlers.

To quantify the impact I created a quick & dirty ESM conversion and created a bundle based on the following entry point:

```js
import { dump } from './dist/js-yaml.mjs';

console.log(dump);
```

and this webpack config:

```
module.exports = {
  mode: "production",
  entry: "./test.mjs",
  output: {
    path: __dirname,
    filename: 'bundle.js'
  }
}
```

These were the resulting file sizes for the bundle:

Branch/Bundler | Webpack 4 | Webpack 5
------------ | ------------- | -
master (using CJS) | 42K | 42K
dev | 36KB | 19KB
esm | 19KB | 19KB

We're still using Webpack 4 in our app so I hadn't noticed yet that Webpack 5 got significantly better at removing unused code. I suspect it's due to a newer version of Terser being bundled.

**Comment by realityking** [comment]
Regarding:

> Current mode is used because no time to experiment with development process change in multiple maintained repos.

Since `js-yaml` is already using rollup, the necessary changes to get this working were fairly small. Happy to post them in case you're interested.

**Comment by puzrin** [comment]
> Since `js-yaml` is already using rollup, the necessary changes to get this working were fairly small. Happy to post them in case you're interested.

If this can be done via rollup config tweaks (without rewrite sources to modules), PR is welcome. If not - IMO it would be better to report about problem with tree shaking to bundler's tracker.

**Comment by realityking** [comment]
> If this can be done via rollup config tweaks (without rewrite sources to modules), PR is welcome. If not - IMO it would be better to report about problem with tree shaking to bundler's tracker.

Sorry, I was unclear. I meant the changes to the build/test/lint system are fairly small. The source code itself would have to be migrated.

**Comment by puzrin** [comment]
Could you provide all details at once? At current moment reasons of this issue look very artificial in my eyes.

**Comment by realityking** [comment]
> Could you provide all details at once? 

I don't think I was holding anything back. I just clarified that the minimal changes are to the build/test/lint system.

> At current moment reasons of this issue look very artificial in my eyes.

I came here because I saw your starting to ship an ESM module and discovered that it doesn't tree shake as well as it could (using an admittedly out of date Webpack version as that's what we're still on). If you don't want to facilitate that case that's up to you but I don't appreciate having stuff called "artificial" after I went through the effort of testing and showing data.

**Comment by puzrin** [comment]
IMO it's logical to start things from use-cases. I see only one use case - bad tree shake in some tool (self-fixed in new version). IMO promoting this as need of rewrite to esm is not correct. Declaring existing default as bad - also not correct.

As a result i call reasons of "need to change development process" artificial. Those are not bad, but improperly addressed (IMO). I'm sorry, if this term was used improperly. English is not my native language. If you know more appropriate terms do describe "creating unneeded logical relation between two independent statements" - let me know.

I'm closing this issue as "not enough reasons for rewrite to esm". But this may change if new info appears (just because the world is changing fast too).
