### ISSUE TITLE
Problem with lessthan operator (<)

### ISSUE THREAD

**Issue by charithreddyv** [nodeca/js-yaml#599]
Consider this object:
```
{
"lessThan":  "<",
"greaterThan": ">",
"lessThanEqual": "<=",
"greaterThanEqual": ">="
}
```

Output:
```
lessThan: <
greaterThan: ">"
lessThanEqual: <=
greaterThanEqual: ">="
```
using `safeDump` there is some inconsistency with characters starting with `<` symbol.

if lessThan (<, <=) is treated as an operator is there a way to remove quotes for other symbols like (>, >=, =, !=, ...)

**Comment by puzrin** [comment]
1. ">" must be quoted
2. https://nodeca.github.io/js-yaml/#yaml=bGVzc1RoYW46IDwKZ3JlYXRlclRoYW46ID4KbGVzc1RoYW5FcXVhbDogPD0KZ3JlYXRlclRoYW5FcXVhbDogIj49Ig== here is online demo for experiments + yaml spec.
