### ISSUE TITLE
Emoji 🦐 escaped

### ISSUE THREAD

**Issue by cristianvasquez** [nodeca/js-yaml#600]
Hello, 

Thanks for js-yaml!.

My report: 

```javascript
const jsYaml = require('js-yaml');
console.log(jsYaml.safeDump({'key': "🦐"}))
// outputs:
// key: "\U0001F990"
```

I expect to have the 🦐 back.

**Comment by rlidwka** [comment]
This is going to be fixed in 4.0.0 (you can look it up now in `dev` branch in this repository).

closing as duplicate of https://github.com/nodeca/js-yaml/issues/587

**Comment by cristianvasquez** [comment]
Thanks @rlidwka !

**Comment by cristianvasquez** [comment]
Hello @rlidwka what happened with the dev branch of this repo?

**Comment by puzrin** [comment]
It's merged to master. Your request should be in released v4.

**Comment by cristianvasquez** [comment]
Thanks! :)
