### ISSUE TITLE
Numbers with leading 0 parsed as number

### ISSUE THREAD

**Issue by Morton** [nodeca/js-yaml#601]
Hi folks,
not sure if this is intended but after switching from 3.14.0 to 4.0.0 following line is parsed differently:
`token: 0987654321`

In 3.14.0 it resolved to a string `"0987654321"`
In 4.0.0 it resolves to a number `987654321`

Not sure which one is actually correct by YAML-spec but just wanted to make sure this was intended ;)

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/commit/19185199e0cc6357869afde7194bb2239ef67917

That's intended. See changelog and migration guide.
