### ISSUE TITLE
unknown tag !<tag:yaml.org,2002:js/regexp> in

### ISSUE THREAD

**Issue by dmvict** [nodeca/js-yaml#602]
Hello. 

Today, I found an error in parsing my YAML file 
```
unknown tag !<tag:yaml.org,2002:js/regexp> in
```

The problem is custom tags with regexps.
I'd researched the problem and found the problem - the module was split into two parts. 
And a submodule was not published. 
Please, publish submodule `js-yaml-js-types`. 

===

And I have one question.
Does the new version of module `js-yaml` save back compatibility with version 3.14.1?

**Comment by puzrin** [comment]
Ups... sorry, publised. Thanks for report.

For migration see https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md and changelog.
