### ISSUE TITLE
Unable to reference "js-yaml/lib/" files with webpack 5

### ISSUE THREAD

**Issue by OpportunityLiu** [nodeca/js-yaml#603]
In v4.0.0, `"exports"` is added in package.json

> When the exports field is specified, only these module requests are available. Any other requests will lead to a ModuleNotFound Error.

https://webpack.js.org/guides/package-exports/

**Comment by puzrin** [comment]
Could you explain, which files you need an why? All important should be available via `module.export`.

**Comment by OpportunityLiu** [comment]
I'm building my own schema baesed on `JSON_SCHEMA`, adding `timestamp` and `merge`, and other JS types such as typed array.

It's ok to start with `DEFAULT_SCHEMA`, just ignore the explict types.

**Comment by puzrin** [comment]
Is it ok to close then?

Or i could add `module.export.types` with content of https://github.com/nodeca/js-yaml/tree/master/lib/type. This has not been done before, because i was not clear if required after rewrite (with new improved schemas)
