### ISSUE TITLE
JS to YML Dump - Nesting of quotes

### ISSUE THREAD

**Issue by dhruvdutt** [nodeca/js-yaml#604]
- Version: `js-yaml@4.0.0`

- Method: `dump` for converting JS to YML.

There's an issue with nesting of quotes.

Input - Outer **single** quotes and inner **double** quotes:
![image](https://user-images.githubusercontent.com/5961873/104339053-2c440580-551d-11eb-8d90-8d30997e2eaa.png)

Output - Expected output ✅ 
![image](https://user-images.githubusercontent.com/5961873/104339076-3108b980-551d-11eb-8192-ac4a9207c54f.png)

---

Input - Outer **double** quotes and inner **single** quotes:
![image](https://user-images.githubusercontent.com/5961873/104339243-631a1b80-551d-11eb-9c21-a26d8c3e5b13.png)

Output - Unexpected output ❌ 
![image](https://user-images.githubusercontent.com/5961873/104339334-7b8a3600-551d-11eb-98ac-f2fa970c1351.png)

**Comment by rlidwka** [comment]
It's expected. Inside single-quoted scalar a single quote is encoded as `''`, as [per spec](https://yaml.org/spec/1.2/spec.html#id2788097).

You can set `quotingType='"'` if you want double quotes instead, but there's no other way to encode single quote inside single quoted string.

Also, I believe it worked the same in `yaml@3.x` as well (please tell if something serialized differently here).
