### ISSUE TITLE
v3 -> v4: empty objects and arrays are now dumped differently

### ISSUE THREAD

**Issue by adrai** [nodeca/js-yaml#605]
Is this behaviour expected?

Should {} be dumped as nothing? "" instead of "{}"?
Should [] be dumped as nothing? "" instead of "[]"?

```js
const jsyaml = require('js-yaml');

console.log(jsyaml.dump({ test: {} })) // result: "test: {}"
console.log(jsyaml.dump({ test: [] })) // result: "test: []"

console.log(jsyaml.dump({})) // result: "{}"
console.log(jsyaml.dump([])) // result: "[]"
```

If not, is there an option that could be used to dump {} and [] like in v3?

**Comment by puzrin** [comment]
Dumped data MUST be loadable back to the same result. If you need something different - you should pre-process your data or may be use `replacer` option.
