### ISSUE TITLE
How to validate against JSON Schema

### ISSUE THREAD

**Issue by mbazalik** [nodeca/js-yaml#606]
Hi there

I am having a CI service that validates YAML files using JSON schema. The solution works by firstly converting the YAML to JSON using `js-yaml` and then by checking the schema using `ajv`

sample code:

```typescript
import { load } from 'js-yaml';
import { default as Ajv } from 'ajv';
import schema from '../../schema.json';

const ajv = new Ajv({
    strict: false
});

export const validate = (file: { content: string }) => {
    const parsed = load(file.content) as unknown;
    const valid = ajv.validate(schema, parsed);

    if (!valid) throw new Error(ajv.errorsText());
}
```

I would like to extend this solution to report back with the error Line and Column. 

Is there a way to instruct `js-yaml` to follow a particular JSON schema (the `load` method `schema` option seems to be used for something different ☹️)?
If not Is there a way of exposing AST produced by `js-yaml` so it can be combined with the output of `ajv` to produce an accurate error location?

**Comment by puzrin** [comment]
1. https://github.com/nodeca/js-yaml#load-string---options- schema can be set via options
2. This parser has no ast, sorry

**Comment by mohdashraf010897** [comment]
@puzrin Can you elaborate what do you mean when you say _This parser has no ast, sorry_?

Also, https://github.com/mulesoft-labs/yaml-ast-parser 👈 can this package achieve what @mbazalik is trying to do?

**Comment by perlpunk** [comment]
Have a look at https://github.com/eemeli/yaml
It passes most of the official test suite and provides much more custom options. And it provides an AST.

**Comment by mohdashraf010897** [comment]
@perlpunk Thanks for the suggestion. I just have a straightforward question even now.

Is it possible to do what @mbazalik has originally asked?
