### ISSUE TITLE
how to make object value not to add single quote

### ISSUE THREAD

**Issue by jerryc127** [nodeca/js-yaml#607]
how to make object value not to add single quote

Look like

```
path:  window.location.pathname
````

It will show `'path': 'window.location.pathname'`
i want to `'path':  window.location.pathname`

**Comment by rlidwka** [comment]
Why do you want to use quotes in `'path'`, but not in location?

yaml does not add any single quotes by default:

```js
console.log(require('js-yaml').dump({path: 'window.location.pathname'}))
// prints:
// path: window.location.pathname
```

you can force quotes with `forceQuotes: true` for both key and value, but we don't have an option to force them on keys and values separately
