### ISSUE TITLE
js-yaml -> Parse ruby types

### ISSUE THREAD

**Issue by sancarn** [nodeca/js-yaml#608]
This question was originally posted on [stackoverflow](https://stackoverflow.com/questions/51300365/js-yaml-parse-ruby-types)

I have the following YAML:

```yaml
---
- !ruby/class 'Test'
- !ruby/object:Test {}
```

When I try to parse this with JS-YAML we get the following error:

```
unknown tag !<!ruby/class> at line 2, column 21:
    - !ruby/class 'Test'
                 ^
```

I believe this is happenning because YAML in JavaScript doesn't have Ruby types! I've seen that one solution is to create new YAML types to handle this data:

```js
var RubyClassType = new jsyaml.Type('!ruby/class', {
  kind: 'class'
});
```

However, in an ideal world I wouldn't have to define each all ruby types. In an ideal world, I could tell JS-YAML how to handle all unknown types and/or they are treated as yaml sequences.

Is there functionality in JS-YAML to define how to handle all unknown types?

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/examples/handle_unknown_types.js
