### ISSUE TITLE
safeLoad(): Make options optional

### ISSUE THREAD

**Issue by mk-pmb** [nodeca/js-yaml#61]
When calling YAML.safeLoad(content) without a second argument (options), I get this error:

```
/foobar/node_modules/js-yaml/lib/js-yaml/common.js:50
  var index, length, key, sourceKeys = Object.keys(source);
                                              ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
```

Passing an empty object literal ({}) fixes the problem but looks out of place.

```
$ npm ls js-yaml
/foobar
+-- js-yaml@2.0.0
```

**Comment by rblakeley** [comment]
In the README example code, a second argument is passed to `safeLoad` which is a string and not an object:
```
// Get document, or throw exception on error
try {
  var doc = yaml.safeLoad(fs.readFileSync('/home/ixti/example.yml', 'utf8'));
  console.log(doc);
} catch (e) {
  console.log(e);
}
```
That code gives me the same error `[TypeError: Object.keys called on non-object]`.
But when I remove `, 'utf8'`, it's all good. Why is that happening?
