### ISSUE TITLE
Schema prop - other than default, not working?

### ISSUE THREAD

**Issue by abrezuica** [nodeca/js-yaml#610]
Trying to give a value to the schema prop in dump() results in the following error:

![schemaError](https://user-images.githubusercontent.com/59456269/111137120-1b4c5a80-8587-11eb-8e17-37075186b42b.PNG)

From what I've seen, the State function in dumper is expecting the schema itself as a prop, not a string with its name (as I supposed). It would be nice to have it conditionally load a schema by name.

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/ee74ce4b4800282b2f23b776be7dc95dfe34db1c/index.js#L16-L21

All schema-related things are exported. Value can not be string.
