### ISSUE TITLE
YAML key getting cased incorrectly after using yaml.load

### ISSUE THREAD

**Issue by jon-van** [nodeca/js-yaml#619]
I have some yaml that looks similar to this:
```
True:
  isTrue: true
```
however, after using `yaml.load` to load this yaml, the resulting JSON is converted to:
```
{
  "true": {
    "isTrue": true
  }
}
```

Is there a way to preserve the casing on the `True:` object besides adding quotes around it like so: `"True:"`? Thanks.

**Comment by rlidwka** [comment]
> Is there a way to preserve the casing on the True: object besides adding quotes around it like so: "True:"? Thanks.

No. Why do you need that? `true` and `True` have the same exact value (boolean truth), and all information about original markup is lost on `load()`.

*Well actually, there's a way. You can use custom schema instead of boolean to load and serialize that value however you want. It depends on your use-case.*

**Comment by jon-van** [comment]
My program that I am using converts the key name (in this case `True`) to a string that gets used later for other processing. So when the yaml is loaded and `True` gets turned to `true` for the key in the JSON, it then causes issues for me since an object im trying to find an item of `true` on doesnt have it, since it has `True` only. Thanks for the info on the custom schema, i'll give that a look.

**Comment by rlidwka** [comment]
It works with failsafe schema for example:

```
> yaml=require('js-yaml')
> yaml.dump(yaml.load('True'))
'true\n'
> yaml.dump(yaml.load('True',{schema:yaml.FAILSAFE_SCHEMA}),{schema:yaml.FAILSAFE_SCHEMA})
'True\n'
```

It doesn't have integers and such, but you can add them (see docs).

**Comment by jon-van** [comment]
Awesome, thanks a lot for the help!
