### ISSUE TITLE
Handle helm chart values references

### ISSUE THREAD

**Issue by pascalre** [nodeca/js-yaml#620]
Consider this snippet:
```
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
app: clientsso
name: {{ .Values.ui.environment.keycloakClientId }}
namespace: {{ required "Keycloak namespace required" .Values.keycloak.namespace }}
```
When loading this with the provided function `.load()`, the helm chart references are not loaded correctly as string, but more as empty object: `{[object Object]: null}`. Dumping this snippet results in:

```
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
app: clientsso
name: '[object Object]': null
namespace: '[object Object]': null
```

Is there any way to get this working?

**Comment by puzrin** [comment]
`{}` without commas is interpreted as JSON object. See yaml spec.

also fails: https://yaml-online-parser.appspot.com/?yaml=apiVersion%3A+keycloak.org%2Fv1alpha1%0Akind%3A+KeycloakClient%0Aapp%3A+clientsso%0Aname%3A+%7B%7B+.Values.ui.environment.keycloakClientId+%7D%7D%0Anamespace%3A+%7B%7B+required+%22Keycloak+namespace+required%22+.Values.keycloak.namespace+%7D%7D%0A&type=json

valid: https://nodeca.github.io/js-yaml/#yaml=YXBpVmVyc2lvbjoga2V5Y2xvYWsub3JnL3YxYWxwaGExCmtpbmQ6IEtleWNsb2FrQ2xpZW50CmFwcDogY2xpZW50c3NvCm5hbWU6ICd7eyAuVmFsdWVzLnVpLmVudmlyb25tZW50LmtleWNsb2FrQ2xpZW50SWQgfX0nCm5hbWVzcGFjZTogJ3t7IHJlcXVpcmVkICJLZXljbG9hayBuYW1lc3BhY2UgcmVxdWlyZWQiIC5WYWx1ZXMua2V5Y2xvYWsubmFtZXNwYWNlIH19Jw==
