### ISSUE TITLE
How to handle empty arrays?

### ISSUE THREAD

**Issue by timtribers** [nodeca/js-yaml#621]
Hi,

I have lots of YAML files which contain constructs like:

```
   mapping:
      this: [foo , bar]
      that: [ , ]
```

They worked fine when I read them using Grunt, but now that I use js-yaml they blow up with the error:

**Error YAMLException: expected the node content, but found ','**

I don't really want to reformat LOTS of yaml files.  Is there a way to get js-yaml to handle these empty values?

Thanks,

**Comment by puzrin** [comment]
https://yaml-online-parser.appspot.com/?yaml=%5B+%2C+%5D&type=json

I'm not sure this notation is valid, pyyaml also fails.

**Comment by perlpunk** [comment]
Empty values in flow style are not valid. Most yaml parsers out there return an error for this. Only yaml-cpp allows it.

The only thing allowed is a trailing comma, e.g. `[ foo, ]`

**Comment by timtribers** [comment]
Thanks @puzrin for the quick response.

I'm quite sure you're right.  I have found that rewriting my yaml as:

```
   mapping:
      this:
         - 
         - 
```

or even

```
   mapping:
      this: ['', '']

```
both work fine.  But I just wondered if there was a smart way to help me avoid editing LOTS of yaml files?

**Comment by timtribers** [comment]
Thanks @perlpunk - what a responsive community there is around this library 👍
