### ISSUE TITLE
Feature request - Can we preserve comments in YAML file

### ISSUE THREAD

**Issue by cheitya** [nodeca/js-yaml#624]
I have a YAML file with comments.
I want to parse it to JSON, mutate the JSON object for adding values and dump it back to YAML but with COMMENTS preserved in YAML.

**Comment by puzrin** [comment]
Sorry, that's impossible without full parser rewrite. See the same questions in older issues.

**Comment by cyrus-za** [comment]
I came to this issue wanting the same result. I ended up solving my specific scenario by doing a string replacement

Pasting here in case it helps others
```js
#!/usr/bin/env node

import { load } from 'js-yaml'
import { readFileSync, writeFileSync } from 'fs'

const [, _, projectName, version] = process.argv

const filePath = `./infra/invisible-app/values.${projectName}.yaml`
const file = readFileSync(filePath, 'utf8')

function setVersion() {
  const data = load(file)

  if (!data?.image?.tag) throw new Error('no image tag in yaml')

  const oldTag = data.image.tag
  writeFileSync(filePath, file.replace(`tag: '${oldTag}'`, `tag: '${version}'`))
}

setVersion()

```
