### ISSUE TITLE
[help-needed]: Is there a way to parse and dump a yaml file and preserving the format of array/sequence?

### ISSUE THREAD

**Issue by oscard0m** [nodeca/js-yaml#626]
I would like to know if it's possible to pass options to the `parser` and/or the `dump` methods to preserve the format of the arrays and sequence as it is originally in the file. Right now , when running the dump, I get the following transformation:

```yaml
node_version: ["12", "14"]
```

to

```yaml
node_version:
          - "12"
          - "14"
```

Example: https://github.com/oscard0m/octoherd-script-replace-all-repository-topics/pull/14/files

**Comment by puzrin** [comment]
This parser does not preserve formatting info by design. You can only tune dumper options.

**Comment by oscard0m** [comment]
> This parser does not preserve formatting info by design. You can only tune dumper options.

Bus is there an option for my usecase I did not find myself? @puzrin 

Thanks for the quick response

**Comment by puzrin** [comment]
May be  `flowLevel`

**Comment by rlidwka** [comment]
@oscard0m , yes and no.

`node_version: ["12", "14"]` is parsed into JS object `{ node_version: [ 12, 14 ] }`, which does not have the information about formatting, as you can see yourself.

However, you can override yaml types to make `node_version: ["12", "14"]` to parse to whatever you like, and store format information somewhere there.

Look at custom types, might find a few ideas here:
https://github.com/nodeca/js-yaml/issues/613#issuecomment-814319894

**Comment by oscard0m** [comment]
> @oscard0m , yes and no.
> 
> `node_version: ["12", "14"]` is parsed into JS object `{ node_version: [ 12, 14 ] }`, which does not have the information about formatting, as you can see yourself.
> 
> However, you can override yaml types to make `node_version: ["12", "14"]` to parse to whatever you like, and store format information somewhere there.
> 
> Look at custom types, might find a few ideas here:
> [#613 (comment)](https://github.com/nodeca/js-yaml/issues/613#issuecomment-814319894)

Thanks for sharing this detailed explanation @rlidwka. I ended up using another library for the project I was working on but I will check custom types if I get this problem again in the future.

Thanks for your assistance 💪🏽

**Comment by stefanbuck** [comment]
@oscard0m, do you remember which alternative library you ended up using?

**Comment by oscard0m** [comment]
> @oscard0m, do you remember which alternative library you ended up using?

I used this in the past: https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action/blob/main/utils/yaml-parser.js (I don't remember if it solved this concrete use case or not). Let me know your findings @stefanbuck

**Comment by stefanbuck** [comment]
https://eemeli.org/yaml/#working-with-cst-tokens

I ended up using the yaml package which provides access to the concrete syntax tree (CST) 

> For most use cases, the Document or pure JS interfaces provided by the library are the right tool. Sometimes, though, it's important to keep the original YAML source in as pristine a condition as possible. For those cases, the concrete syntax tree (CST) representation is provided, as it retains every character of the input, including whitespace.
