### ISSUE TITLE
Non-breaking space is replaced with \_ when dumping

### ISSUE THREAD

**Issue by artuska** [nodeca/js-yaml#633]
Unicode character '[NO-BREAK SPACE](https://www.fileformat.info/info/unicode/char/00a0/index.htm)' is replaced with `\_`. Is it expected YAML behaviour? All other UTF-8 symbols are not escaped.

**Comment by rlidwka** [comment]
`\_` represents non-breaking space in yaml, as per https://yaml.org/spec/1.2/spec.html, section 5.7. "Escaped Characters"

other UTF-8 symbols may be escaped too, such as `\n` for line feed, `\t` for tab or `\\` for backslash itself *(YAML escape list is a superset of that in JSON, and slightly different from JS)*
