### ISSUE TITLE
Quoting is still `'` for some strings when dumping even if `quotingType: '"'` is set in `dump` config

### ISSUE THREAD

**Issue by artuska** [nodeca/js-yaml#634]
My `js-yaml` config for dumping is:

```
dump: {
  lineWidth: -1,
  quotingType: '"',
  sortKeys: true,
},
```

I'm still getting single quoted strings.

For example, look at this dumped output:

```
option:
  - Keeps people safe
  - 'Prevents flight diversions, delays or cancellations'
  - Detects in and around the airport territory
```

Why second option is quoted? (Just because of comma?) And why it is quoted in single quotes?

**Comment by rlidwka** [comment]
this:

```js
console.log(require('js-yaml').dump({
  option: [
    'Keeps people safe',
    'Prevents flight diversions, delays or cancellations',
    'Detects in and around the airport territory'
  ]
}, {
  lineWidth: -1,
  quotingType: '"',
  sortKeys: true
}))
```

prints this:

```
option:
  - Keeps people safe
  - Prevents flight diversions, delays or cancellations
  - Detects in and around the airport territory
```

without any quotes in current js-yaml 4.1.0

please provide a code sample we can reproduce

**Comment by rlidwka** [comment]
uh... I believe you're using js-yaml version 3.14.1 or earlier, which doesn't have `quotingType` option at all

please upgrade to the latest one, it won't quote commas anymore
