### ISSUE TITLE
Error when using `js-yaml` together with `js-yaml-js-types`

### ISSUE THREAD

**Issue by SolomoN-ua** [nodeca/js-yaml#637]
Hi guys,

After update to latest `js-yaml` version (4.1.0) inside of our project [load-grunt-config](https://github.com/firstandthird/load-grunt-config) some of our users started receiving following error:
```
>> YAMLException: Schema.extend argument should be a Type, [ Type ], or a schema definition ({ implicit: [...], explicit: [...] })
Warning: Task "default" not found. Use --force to continue.
```

code that we are using is quite simple:
``` javascript
var yaml = require('js-yaml');
var schema = yaml.DEFAULT_SCHEMA.extend(require('js-yaml-js-types').regexp);
```
you can find it [here](https://github.com/firstandthird/load-grunt-config/blob/1d2d7d00e92643e7cf4219e85a21a27abbbbb924/lib/readfile.js#L16)

After some investigation looks like the issue is with the following [check](https://github.com/nodeca/js-yaml/blob/2cef47bebf60da141b78b085f3dea3b5733dcc12/lib/schema.js#L70)
```javascript
if (definition instanceof Type) {
```

Looks like the possible reason is multiple versions of `js-yarn` (including old 3.x.x) inside the `node_modules`, because of different other dependencies. Maybe it could be fixed by adding `js-yarn` as non-dev dependency inside of `js-yaml-js-types`, but that is just an idea. Or maybe the check itself should be improved somehow. 

Could you please help us to resolve this issue?

Some other details:
js-yaml: 4.1.0
js-yaml-js-types: 1.0.0
link to the original issue: https://github.com/firstandthird/load-grunt-config/issues/194

**Comment by puzrin** [comment]
IMO npm's dependency graph is a bit out of scope. You could delete deps, lockfile and install deps from scratch.

If you try to report a bug - then create a minimalistic example, confirming unexpected behavior (without extra dependencies).
