### ISSUE TITLE
how to get json string by  double quote

### ISSUE THREAD

**Issue by phpiscute** [nodeca/js-yaml#638]
It is a  `json object` , I want to get a `json string` ,  key and value is double quote in demo.

I hope you can response , thx. 

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/87626576/131216237-7966f934-f933-4de3-968e-5d31857cc12c.png">

https://nodeca.github.io/js-yaml/

**Comment by puzrin** [comment]
In json all strings are quoted. IMO your question is not specific to this package.

**Comment by phpiscute** [comment]
Hi, puzrin~,  It is at your program demo : https://nodeca.github.io/js-yaml/

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/87626576/131238636-4182cdfb-deae-47f0-ab4f-e7332ed0bb1a.png">

**Comment by puzrin** [comment]
I don't understand you. Demo is just a quick-work to demonstrate features, it's not related how package works.

**Comment by phpiscute** [comment]
Thanks for you answer.

I want use Demo to help me to debug the yaml about k8s,  and  learn  YAML grammer, because I have some json skill.

So, How to change some config of Demo? to let Demo show json string,  not json object.

**Comment by puzrin** [comment]
I guess, demo is not suitable for your demands.

**Comment by phpiscute** [comment]
Haha.
puzrin~, Demo is cute, great, it is  suitable for your demands.

Could you can help me~~

**Comment by puzrin** [comment]
Sorry, due time constrains i can't help with generic programming question :(

**Comment by phpiscute** [comment]
thx.
I attempt to get it to use `JSON.stringify()` .
thx.
