### ISSUE TITLE
Difference with some other parsers

### ISSUE THREAD

**Issue by AaronDewes** [nodeca/js-yaml#657]
For JS-YAML, this

```
a: yes
b: "yes"
```

For pyaml, 

```
yaml.safe_load("a: yes\nb: 'yes'")
```

Evaluates to `{'a': True, 'b': 'yes'}`

This causes issue when a yaml file which contains a value yes is used by multiple yaml parsers.

I'm for example using js-yaml to automatically upgrade docker containers in a docker-compose.yml. One of the containers containts an env var whhich is set to yes. When loading this in JS-YAML

```
value: "yes"
```

and re-exporting, it ets exported as

```
value: yes
```

When loading that with most other yaml parsers, these things are different. `"yes"` is a string, but `yes` is a boolean.

I'm not sure which parser is correct here.

**Comment by puzrin** [comment]
http://nodeca.github.io/js-yaml/#yaml=YTogeWVzCmI6ICJ5ZXMi

This is yaml 1.2 parser. `yes` is `true` in 1.1. I strongly suggest to force python's package use 1.2, and not use `yes` in files (+ auto-convert old versions of those).

Difference between 1.1 & 1.2 - some garbage removed. In your case - multiple variants of Boolean representation.

**Comment by AaronDewes** [comment]
Thank you! I wasn't aware of that change in the specM Sorry for the spam issue then
