### ISSUE TITLE
Is there a way to preserve null array elements? 

### ISSUE THREAD

**Issue by ajordaan** [nodeca/js-yaml#658]
If I have a YAML file like this: 

```
root:
  array:
    - null
    - null
    - null
```

Then the dumper will output this: 

```
root:
  array:
    - null
```

Is there a way to preserve all of the null elements? The reason for this is I am trying to keep multiple YAML files "in-sync" so their respective line numbers all match

**Comment by puzrin** [comment]
```
node -e "console.log(require('js-yaml').dump({ root: { array: [ null, null, null ] } }))"

=>

root:
  array:
    - null
    - null
    - null
```

can not reproduce

**Comment by ajordaan** [comment]
@puzrin I realised another part of my script was causing this, not the dumper. Sorry!
