### ISSUE TITLE
[writer] Implement full-weight scalar style resolver.

### ISSUE THREAD

**Issue by dervus** [nodeca/js-yaml#66]
It should resolve scalars to all available YAML scalar styles: [plain](http://www.yaml.org/spec/1.2/spec.html#id2788859), [single-quoted](http://www.yaml.org/spec/1.2/spec.html#id2788097), [double-quoted](http://www.yaml.org/spec/1.2/spec.html#id2787109), [folded](http://www.yaml.org/spec/1.2/spec.html#id2796251), and [literal](http://www.yaml.org/spec/1.2/spec.html#id2795688).

Examples:
``` yaml
text: Simple string.
```
``` yaml
text: 'String with trailing spaces...  '
```
``` yaml
text: "String with unprintable (\0, \uFFFE) characters."
```
``` yaml
text: "String with \"quotation\" 'mark' characters."
```
``` yaml
# Folded style: there is only one line break after the title.
text: >
  Multiline string.

  This is very a long
  text. It contains no
  line breaks. So it
  is better to use
  folded style here.
```
``` yaml
# Literal style: there is a line break after _each_ actual line.
text: |
  This text contains
  a lot of short lines.
  So, it is better to
  use literal style here.
```

Note. The actual resolver makes only rough choose between plain and double-quoted styles.

**Comment by isaacs** [comment]
So, it seems like the logic would be:

```
if (contains linebreaks) {
  if (any individual line is longer than LIMIT)
    use '>'
  else
    use '|'
  if (last char is \n)
    add '-'
} else if (contains unprintables or single-quotes)
  use double-quote
else if (has trailing spaces)
  use single-quote
else
  use simple-string
```

Is it sensible to use double-quotes in *any* case with trailing space/tab chars?  They're not otherwise visible in many contexts, so it seems a bit hazardous.

**Comment by puzrin** [comment]
- Exact limit not principle right now (will tune later), but it should count left indent. Propably, with some
  relax on very nested content (if indent > 40 - don't count it). I'm ok with 80 chars total, but if you think
  60 chars are better - no problem
- I think, if non trimmable spaces exists, string must be quoted.
- Double quotes looks heavy. It worth to try single quotes first (those have more limitations).

**Comment by isaacs** [comment]
@puzrin I agree with this set of requirements 100%.  Updated my pseudocode above.

I just realized that if we limit the length to 40 chars when the indent is >40, then we have a situation where it gets narrower and narrower until it's half the screen width, and then starts getting pushed off without getting any narrower, without any weird flip situation (where it's suddenly longer/shorter based on indentation).  This pleases me esthetically :)

**Comment by puzrin** [comment]
Up to you. That's a minor issue about defaults, can be tuned on last stage. Strings split and quoting is much more difficult. May be not technically difficult, but boring, because require to read yaml spec. 

Honestly, we never used yaml dumper in our projects, and we had no reason to make it as good as loader is. Result is correct, but not visually perfect.

**Comment by isaacs** [comment]
I'm using the dumper to generate "yamlish" output for a test runner, node-tap.  Since TAP is designed to be machine parseable as well as human-readable, having long multi-line stack traces and stuff presented as quoted strings is quite unpleasant.  So, I'm motivated to make it choose more humane defaults.

\o/ OSS :)

**Comment by puzrin** [comment]
__Notice for developpers. Make sure such mad string processed properly:__

```
foo foo fooo foo foo _________________________________________________ bar bra bar
```

Long line with multiple spaces somewhere inside. As possible solution - don't split such strings to multiline. Seems YAML does not allow selective quoting for multiline scalars.

**Comment by dervus** [comment]
Also note this special case for the folded style: http://www.yaml.org/spec/1.2/spec.html#more-indented//

**Comment by isaacs** [comment]
@puzrin In that comment, is the `_________________________________________________` intended to be spaces?

If so, yes, line-folding can only happen when there is a spot like `/[^ ] [^ ]/`.  If there are any non-`' '` whitespace chars (`\r` or `\n` or unicode oddnesses), then you have to fall back to quoting, I think.

**Comment by puzrin** [comment]
Yes. That were multiple spaces.

**Comment by puzrin** [comment]
May be need new ticket with the rest of possible improvments?

**Comment by dervus** [comment]
We do. I'll create it.
