### ISSUE TITLE
Preserving line and column numbers while parsing

### ISSUE THREAD

**Issue by ShishKabab** [nodeca/js-yaml#665]
I'd love to show more useful error messages in the tools I'm building on top of `js-yaml`! I may get around to implementing it for myself at some point in a fork. What would the requirements be to accept this functionality back into the your original package?

**Comment by rlidwka** [comment]
As far as I remember, js-yaml wasn't designed with it in mind, and preserving line and column numbers will require complete rewrite. And large changes are very hard to accept and review.

Can you please explain how do you plan to implement it in technical terms?

**Comment by perlpunk** [comment]
@ShishKabab maybe https://github.com/eemeli/yaml has already all you need?

**Comment by ShishKabab** [comment]
Hi @rlidwka, I wanted to ask before diving into the details to if it's worth the effort. But the library @perlpunk suggested seems to do everything I need at a glance! Thanks a lot for the suggestion!
