### ISSUE TITLE
Remove ArgParse dependecy due Python 2.0 license.

### ISSUE THREAD

**Issue by gabrielcabola** [nodeca/js-yaml#667]
@puzrin Do you consider removing argparse@2.0.1?, Since your package pretends to have an MIT license the ArgParse has a Python2.0 license which seems to require a BeOpen license (copyleft):

BeOpen hereby grants Licensee a non-exclusive, royalty-free, worldwide license to reproduce, analyze, test, perform and/or display publicly, prepare derivative works, distribute, and otherwise use the Software alone or in any derivative version, provided, however, that the BeOpen Python License is retained in the Software, alone or in any derivative version prepared by Licensee.

https://www.npmjs.com/package/argparse

**Comment by puzrin** [comment]
Please, dig closed issues in argparse tracker. Similar topic was discussed several times, licence is ok (difficult to understand, but correct). Don't worry.
