### ISSUE TITLE
the stream contains non-printable characters (demo included)

### ISSUE THREAD

**Issue by naivefun** [nodeca/js-yaml#669]
http://nodeca.github.io/js-yaml/

The source content: https://api.apis.guru/v2/specs/linode.com/4.97.2/openapi.yaml

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/10683378/167747321-7b9c3bff-dc84-4526-ab37-255e87f944c5.png">

**Comment by puzrin** [comment]
Can not reproduce:

1. Downloaded file
2. Opened in editor, CTRL+C (Unubtu 20.04 LTS, tried GEdit & VSCode)
3. CTRL+V in demo

Works as expected.

- Make sure your editor is ok.
- If you insist on error in this package - try to create test repo with minimal reproducible sample (fetch yaml + call yaml load)
