### ISSUE TITLE
yaml.dump(obj) - weird formatting?

### ISSUE THREAD

**Issue by pxlmo** [nodeca/js-yaml#672]
I got an obj like this:
```
----
port: '3000'
```

But when I use fs.writeFile(`${mainDir}/test.yml`, `${yaml.dump(obj)}`);

it saves it like this:

```
|-
  ---
  port: '3000'
```

how do I get rid of it?

**Comment by puzrin** [comment]
According to result, you put string into dumper, instead of object.
