### ISSUE TITLE
indents

### ISSUE THREAD

**Issue by pxlmo** [nodeca/js-yaml#673]
I tried saving yml data to a file, but it always has indents (2) , so naturally I tried to use `yaml.dump(obj, { indents: -2 })`.

while that _sort of_ works, it always leaves one indent, no matter how much I raise the number.

Am I doing something wrong?

**Comment by puzrin** [comment]
Negative indent is not allowed, you really do strange things.

**Comment by pxlmo** [comment]
> Negative indent is not allowed,

then what am I supposed to do? even indents set to 0 doesn't do anything.

**Comment by puzrin** [comment]
Debug your input data for dumper. As i said in previous issue, it's wrong. If you do `yaml.dump('foo')`, there will be no indent.

**Comment by pxlmo** [comment]
You we're right, there's no indents when I do that, I read that the default indent is set to 2 on the npmjs site, but I guess that's only when you specify the "indent" option.
Sorry for wasting your time
