### ISSUE TITLE
Parsing of numbers with leading/trailing numbers as strings

### ISSUE THREAD

**Issue by rarkins** [nodeca/js-yaml#674]
Currently `yaml.load('version: 12.10', 'utf-8')` produces `{ version: 12.1 }`. I think this is widely known and also not exclusive to this parser, but I was wondering if you were open to a feature request to accept a parsing option to parse numbers with leading or trailing zeroes as strings?

**Comment by puzrin** [comment]
We do not accept deviations from standard. But you can construct custom schema with tweaked `integer` type. I see no technical limitations about that.
