### ISSUE TITLE
Unnecessary quotes

### ISSUE THREAD

**Issue by eevleevs** [nodeca/js-yaml#679]
https://github.com/nodeca/js-yaml/blob/b946fcdc6edee8da19ab7bc5c5fa01e9ba03eb40/lib/js-yaml/dumper.js#L167

Why do we need quotes when beginning with minus?

`jsyaml.dump({"x": "-10 m"})` gives `"x: '-10 m'\n"`, but `"x: -10 m\n"` would also be valid

**Comment by puzrin** [comment]
Probably, that was done to keep `-10.2` as string, without casting to number.

**Comment by eevleevs** [comment]
Does not explain it. `jsyaml.dump({x: -10.2}) == 'x: -10.2\n'` and `jsyaml.dump({x: '-10.2'}) == "x: '-10.2'\n"` as expected. Still can't see why there should be any doubt about `-10 m` being a string. Other converters do a better job and omit the quotes.

**Comment by eevleevs** [comment]
Does not explain it. `jsyaml.dump({x: -10.2}) == 'x: -10.2\n'` and `jsyaml.dump({x: '-10.2'}) == "x: '-10.2'\n"` as expected. Still can't see why there should be any doubt about `-10 m` being a string. Other converters do a better job and omit the quotes.

**Comment by puzrin** [comment]
Existing code guarantees correctness, but does not guarantee ideal result for every possible case. If other dumper suit your needs better - nobody forces you to use this one.
