### ISSUE TITLE
Yaml Parsed Object with position information

### ISSUE THREAD

**Issue by ErasedSoul** [nodeca/js-yaml#715]
I was thinking if it is possible to provide extra information with the parsed yaml ?
Like the (position/range) of the keys and its values, it can help many to create custom extension for business logic validation.

My use case :
I am using yaml for making a Domain Specific language which will contain various other custom logic depending on keys and values. I want to show position of error by creating a Language Server protocol
So, in my case I need the position of keys and values in the source.

Is there any way to achieve this with the current js-yaml version ?

**Comment by puzrin** [comment]
That's not possible with this package. See previous issues with similar questions.
