### ISSUE TITLE
Don't rely on `Object.prototype.toString` to detect object type.

### ISSUE THREAD

**Issue by al6x** [nodeca/js-yaml#720]
I override `toString` and so YAML dump doesn't work, as it uses `toString` to detect object type.

Possible way would be to change YAML sources from:

```js
var _toString       = Object.prototype.toString;
```

to

```js
var _toString       = Object.prototype.toStringOriginal || Object.prototype.toString;
```

so it would be possible to give YAML the original `toString`.

**Comment by rlidwka** [comment]
The behavior of `Object.prototype.toString` is very strictly defined in https://262.ecma-international.org/5.1/#sec-15.2.4.2, and I believe software should trust that JS runtimes implement it correctly.

`Object.prototype.toStringOriginal` does not appear in ecmascript standards at all. If you want to be able to use it, please reach out to TS39 committee, so it can be added to the language.

**Comment by al6x** [comment]
@rlidwka thanks, I didn't realised output of toString is part of the standard. 

Issue resolved
