### ISSUE TITLE
asynchronous resolver for custom types

### ISSUE THREAD

**Issue by lalitkapoor** [nodeca/js-yaml#96]
I'd like to create some custom types, but in order to determine the value to return in the resolver I must make some asynchronous operations in some cases. It would be nice if the resolver took a callback to pass the value.

**Comment by puzrin** [comment]
> Even if hacky, is there any sort of workaround that we might apply?

Standard hack for such kind of tasks is to create a temporary markers, and do postponed async processing on secondary stage:

1. Create fake sync resolver. It should store path + initial (unparsed) content somewhere.
2. After calling loader, inspect collected content from fake resolver and do all async things you need.
3. Update data with resolved content
